### ISSUE TITLE
Add Instagram to Community social options

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1004]
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What's your request?**
Add instagram to the list of social accounts we allow communities to link to from the nav bar
**What would this feature help you accomplish, and why is that important to you?**
Requests from users; demand

**Have you considered any alternative solutions or features?**

---

**Any attachments or reference images? (Drag them here)**

**Are there any other products or services that do this well?**

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
CA/ CONL

**Comment by gabestein** [comment]
Also requested by Paige/HDSR

**Comment by gabestein** [comment]
We're going to migrate to supporting links with icons and rels in https://github.com/pubpub/roadmap-repo/issues/6.
