### ISSUE TITLE
Image editor on pages

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1043]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. When you're revising an image upload in a text block on a page, there's a bug that switches which image you're editing (re-uploading) when you click on the pencil. 
2. You then instead end up uploading the image in the wrong place
...

**What did you expect to happen?**

**What URL can we use to see the issue?**
First encountered in Entanglements https://entanglements.pubpub.org/
**What browser/operating system were you using?**
Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
Here's a video of it happening: https://recordit.co/hC79aEh8Z1
Note the image associated with the first bio at the top of the text block. When I go to change the picture for a bio further down, it ends up uploading and replacing that first image instead. 

**Who reported this? (If not you)**
CA

**Comment by coahearn** [comment]
Note: this is separate from the bug I already let Deepak know about regarding the caption editor for images and notes on pages!

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/7
