### ISSUE TITLE
Collection-level DOIs + automated citations

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1075]
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What's your enhancement request?**
Would be great if we could include collection-level DOIs in citations. For instance, some books will not have chapter-by-chapter DOIs, but instead will have a book-level DOI assigned. Including this in the citation (and on pdf exports) would be nice. Also wondering if there's a way to automatically use the most specific DOI available, so if a chapter has a DOI, use that one, but if the DOI is at the book level, use that one. 

**What would this enhancement help you accomplish?**
particularly helpful with exports and citations

---

**Any attachments or reference images? (Drag them here)**

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
me, and admins at HKS, Goldsmiths, and MITP

**Comment by gabestein** [comment]
Given that bibtex only supports a single doi per cite, Catherine and I discussed a fallback option in Slack. Basically, if there's a pub-level doi, we should use that. If not, we should use a collection-level doi if it exists.
