### ISSUE TITLE
Visibility of title 

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1079]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. When styling the title of an article in black box (white text), when you click on it to edit the title, the background turns white but the white text remain white, so you can't see anything! 
2.
...

**What did you expect to happen?**
keep black background and white text styling when editing, or invert both

**What URL can we use to see the issue?**
any?
**What browser/operating system were you using?**
chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
https://recordit.co/7QIpbPLGMM

**Who reported this? (If not you)**
CA

**Comment by gabestein** [comment]
New title editor in #2041 seems to have fixed this.
