### ISSUE TITLE
Abstract excluded in XML based Pub import

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1086]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Batch uploaded XML and figures for TMB 
2. Abstract was noticeably missing from Pub while present in PDF (referenced for comparison) and more importantly, the XML. 
...

**What did you expect to happen?**

To see the abstract in the Pub (as composed in the XML) 

**What URL can we use to see the issue?**
https://tmb.apaopen.org/pub/8aolxp51/draft (please see history slider as the issue has since been resolved - manually). 

**What browser/operating system were you using?**

Chrome

---

**Have any screenshots? (Attach them by dragging the image here)**
![image](https://user-images.githubusercontent.com/72410195/96203521-b8975a00-0f27-11eb-9390-15b67a5ad6f8.png)
![image](https://user-images.githubusercontent.com/72410195/96203443-8259da80-0f27-11eb-8ee6-fa39bdc8e22e.png)

**Who reported this? (If not you)**

**Comment by Dawit-Tegbaru** [comment]
Another XML import with a disappearing Abstract. See screenshots. Also attaching XML file to facilitate diagnostic testing. 
![image](https://user-images.githubusercontent.com/72410195/98396075-d0439900-2022-11eb-875c-a79ec1032c2b.png)
![image](https://user-images.githubusercontent.com/72410195/98396160-e8b3b380-2022-11eb-8496-0fa65066914b.png)
![image](https://user-images.githubusercontent.com/72410195/98396244-0ed95380-2023-11eb-9b80-080f8394fc07.png)

[tmb_tmb0000019.zip](https://github.com/pubpub/pubpub/files/5502622/tmb_tmb0000019.zip)

**Comment by gabestein** [comment]
I believe this is fixed in #1688.
