### ISSUE TITLE
Author byline ordering (first in -> first out) 

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1091]
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._
None so far. 
_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What's your enhancement request?**
When editing the author byline (contributors), It would be great if the ordering is set based on sequence of when contributors are added. For example: 
Testy Tester A, Testy Tester B, Testy Tester C =  Testy Tester A, Testy Tester B, Testy Tester C
Not: 
Testy Tester A, Testy Tester B, Testy Tester C =  Testy Tester C, Testy Tester B, Testy Tester A

**What would this enhancement help you accomplish?**
This will facilitate a more intuitive process for adding contributors (improved UX) and save editors time - effectively eliminating the need to manually drag and drop for contributor order corrections. As a side note: while importer improvements may reduce encounters of this question, use cases of manual contributor adds will remain common. 

**Any attachments or reference images? (Drag them here)**
![contributor add_1](https://user-images.githubusercontent.com/72410195/96312092-8b52b680-0fd0-11eb-8a7e-2418bd373aa9.png)
![contributor add_1 1](https://user-images.githubusercontent.com/72410195/96312102-90176a80-0fd0-11eb-8238-e3b3a56b73c2.png)

**What's the URL to your PubPub community?**
n/a

**Who requested this? (If not you)***

**Comment by avanouse** [comment]
YES this would be super helpful; I have often thought it would be more
intuitive if it worked this way.

**Comment by gabestein** [comment]
We fixed this!
