### ISSUE TITLE
Make it easier to see open requests for review and to make quick reviews

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1094]
As a community admin, I had 6 new pages posted for review last night.  I didn't notice while logged in and editing the community, until they wrote me to say I needed to approve those posts.  (aside: I also made them an admin, as they need a new-page-creation flag).

1a. Seeing how many open reviews, and returning the the "reviews" page, were harder than I remembered. 
* When looking at the community-admin dashboard: I can see that there are "6" reviews.  Clicking on that shows me the reviews, the first of which takes two clicks to approve: I select it, am taken to a view showing only that review, and approve it.  Now the sidebar only shows "1" review, and clicking on that keeps me there, on the list of reviews for just this Pub.  Now "Overview" in the lhs also doesn't take me back, it shows me only the Overview of ... that pub.
1b. Once I realize what has happened, it's a bit hard to get back to where I was. There is only one link on the page which will take me back to the community overview in a single click: the first small-text link in the breadcrumbs below the title of this pub.  The rest take at least a second click.
2. Reviewing more than one post takes a while, as a result.  It would be nice to have an option for selecting + reviewing many at once. 
3. Once all have been reviewed, there is no change in the way the # of reviews ("6") is presented.  I would prefer to know how many were open and pending review.
4. Finally, the list of reviews on the "reviews" page takes 4-5 line-heights per Pub, which can be a lot for a community with many pubs that get reviewed a single time.  I could use a way to have unreviewed items automatically filter to the top.

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/10
