### ISSUE TITLE
[Bug] Pub Appears in Collection When Not Actually In Collection

### ISSUE THREAD

**Issue by writingpoli** [pubpub/pubpub#1107]
**What went wrong, step-by-step?**
1. Pub is appearing in Collection though it isn't actually in Collection.

**What browser/operating system were you using?**
Chrome/Windows 10

**Have any screenshots? (Attach them by dragging the image here)**

<img width="615" alt="ZLB7Z44xrM" src="https://user-images.githubusercontent.com/3883763/97056736-4b02b380-154f-11eb-96ad-331cd54bdfd9.png">
You'll notice "Time and Arrokoth" in the above image. It shouldn't be there. But I can't figure out why it is. I looked at Collections, and don't see the Pub in our Pending Publication Collection:
<img width="918" alt="MXrUXIBPLC" src="https://user-images.githubusercontent.com/3883763/97056731-48a05980-154f-11eb-90f0-14ddeaf2cdd0.png">
Even with the drop-down selector, "Time" isn't available -- yet it still displays. 
<img width="910" alt="JJu9M0QCo9" src="https://user-images.githubusercontent.com/3883763/97056721-450cd280-154f-11eb-9b87-de3bb67c7178.png">

What am I doing wrong/missing?

**Comment by idreyn** [comment]
Hey William, thanks for the report and sorry for the trouble — I took a look at this and it seems you've hit a weird quirk of the UI where pinned Pubs that do not match the chosen Collection filter are filtered out of the Pinned Pubs list in the Page editor, but still remain in the list that the Page displays.

As it happens we've been doing quite a bit of work with the Pages editor in preparation for a big new Collections-related feature, and I think some of the code I've written for that will resolve this issue. It should land in the next week or so, but in the meantime if you encounter this problem the workaround is just to modify the Pinned Pubs list in some way (for instance by dragging a Pub into and then back out of the list) to bring it back into sync.

**Comment by writingpoli** [comment]
Ah-ha! Thank you!

William

-------- Original Message --------
