### ISSUE TITLE
Collection name not included in download as pdf

### ISSUE THREAD

**Issue by mikkelgabriel** [pubpub/pubpub#1110]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Downloading a pub as pdf. 
2. The first line entails the title of my journal. 
3. After that, it did not include the name of the collection to which I had assigned the pub.   

**What did you expect to happen?**
I expected that the first line of the pdf would include not only the title of my journal but also the collection name. 

An pubpub expert found the issue: the pub needs 1) to be defined as an article, 2) to have used as primary collection ticked and 3) republished. Then it works as expected. See screenshots. 

**What URL can we use to see the issue?**
Se screenshots below. 

**What browser/operating system were you using?**
Firefox
---

**Have any screenshots? (Attach them by dragging the image here)**
![1 Wrong definitions ](https://user-images.githubusercontent.com/73580063/97409328-b2c54f80-18fd-11eb-87ae-4110cf6bb3bd.png)
[1 Without collection title.pdf](https://github.com/pubpub/pubpub/files/5450456/1.Without.collection.title.pdf)
![2 Right definitions](https://user-images.githubusercontent.com/73580063/97409338-b8bb3080-18fd-11eb-9aa9-6c42f03ee808.png)
[2 With collection title.pdf](https://github.com/pubpub/pubpub/files/5450457/2.With.collection.title.pdf)

**Who reported this? (If not you)**
n/a

**Comment by gabestein** [comment]
This has been fixed for a long while, but I can re-confirm that it works as of #1502
