### ISSUE TITLE
Image captions for left/right aligned images a bit buggy

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1116]
See: https://baas.aas.org/pub/2020i0326/release/1

Probably related to the captions/anchors release.

@pkgw sent in!

**Comment by 3mcd** [comment]
Fixed in [732c919](https://github.com/pubpub/pubpub/commit/732c919e4281fa484ad85fed2973af0cf07d1ab1).

**Comment by pkgw** [comment]
Cool, thanks! What's the timeline for deploying such fixes to production?

**Comment by gabestein** [comment]
Hi Peter, we just deployed it. It should take effect in the next 20-30 minutes.
