### ISSUE TITLE
"Page Not Found" error misleads, especially when logged in

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1118]
"Page Not Found" errors may result from someone with access to a version of a pub sharing it with someone who does not have access.  In those cases, that error message you get when logged in is even less informative (just "PNF")  than the version you get when logged out (hinting that it may exist but you don't have access, and should try logging in).

This is particularly frustrating for readers or editors who were just working on a page by that name, and have lost access due to some combination of URL rewriting that dropped their access= key, or getting logged out.

In communities where _most_ PNF errors result from a mismatch in privileges, it is worth always providing a more detailed hint with guidance for the perplexed.

Proposed fix: A more narrative and thorough message, like you get when hitting an unknown title on Wikipedia
(https://en.wikipedia.org/wiki/Pubpub)
* If there is a release version and you are visiting a private draft version: tell the reader that!
* If there is no public pub, say that ("There is no public pub with this title")
* Offer specific alternatives, that link to a page trying that alternative:  "Try logging in", "Search for pubs with a similar title", "Other reasons you may be seeing this message" 
* Bonus: Indicate how you can ping community admins or otherwise ask for assistance.

**Comment by gabestein** [comment]
As in #597 #864, we've added to the error message to make it less confusing.
