### ISSUE TITLE
Tables Not Exporting / Columns and Rows Can't Be Adjusted

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1128]
I suspect this is related to the recent node ID/reference updates.

**What went wrong, step-by-step?**
1. Create a pub with a table (e.g. https://demo.pubpub.org/pub/2bqfqpud/draft)
2. Try to adjust the column width or row height
3. Export it to any format
4. Table does not appear (in html, it is just a blank table)

**What did you expect to happen?**
Columns and rows should be adjustable. Table should be included in export.

**What URL can we use to see the issue?**
https://demo.pubpub.org/pub/2bqfqpud/draft

**What browser/operating system were you using?**

**Comment by avanouse** [comment]
Trying to re-size cells and prompted to refresh the editor—but then the table vanishes.

https://tmb.apaopen.org/pub/gybsu0dp/draft/875?from=33156&to=33165

screen recording? https://knowledgefutures.slack.com/files/USLFEKYJW/F01ETJCV6D7/tables_probs.mp4
