### ISSUE TITLE
TMB page won't load (Application Error)

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1130]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Attempted to access https://tmb.apaopen.org/
2. Received an application error
...

**What did you expect to happen?**

**What URL can we use to see the issue?**
https://tmb.apaopen.org/

**What browser/operating system were you using?**
Tried viewing on Chrome and Edge

---

**Have any screenshots? (Attach them by dragging the image here)**
![image](https://user-images.githubusercontent.com/72410195/98563968-679e2b80-2271-11eb-9bd6-bf068b134a5c.png)

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Thanks! We had some temporary instability. Should now be back up.
