### ISSUE TITLE
New page error

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1132]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Filled in details for a new page
2. Received an error I haven't seen before
3. Tried changing the fields and removing a description but none of that helped
...

**What did you expect to happen?**

**What URL can we use to see the issue?**
https://phone-and-spear.pubpub.org/dash/pages

**What browser/operating system were you using?**
Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
<img width="1072" alt="Screen Shot 2020-11-10 at 8 21 59 AM" src="https://user-images.githubusercontent.com/32333767/98679547-320b4800-232e-11eb-872e-3c085ebbebe4.png">

**Who reported this? (If not you)**

**Comment by 3mcd** [comment]
Fixed by [832a4253](https://github.com/pubpub/pubpub/commit/832a4253e890b1ecdcdd2351b88537983627fb05).
