### ISSUE TITLE
Interactive elements not clickable

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1134]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Visit https://demo.pubpub.org/pub/2bqfqpud/release/2 and try to download the PDF
2. You can't click on the card
3. Same with playing the video.

**What did you expect to happen?**
The card is clickable. The video is playable.

**What URL can we use to see the issue?**
https://demo.pubpub.org/pub/2bqfqpud/release/1

**What browser/operating system were you using?**
Mac / Chrome latest
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Scott Jacques

**Comment by 3mcd** [comment]
Fixed in [d8f738f](https://github.com/pubpub/pubpub/commit/d8f738f403f734c9b55181f9af89baeedc2353a4).

**Comment by gabestein** [comment]
Thanks for the quick fix, Eric! One note, and apologies for not noting this in the original bug: this still seems to be broken in draft (ie https://demo.pubpub.org/pub/2bqfqpud/draft). There's no way to interact with anything when you're drafting the piece. That has implications for folks who don't ever want to release pubs. Is there a way to fix that as well?
