### ISSUE TITLE
LaTeX not importing

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1136]
Suspect related to block changes, but unsure. Have tested with a number of different tex files, including the one linked.

**What went wrong, step-by-step?**
1. Try to import [example tex](https://pandoc.org/demo/example4.tex) from Pandoc
2. Import initially succeeds
3. When clicking import, metadata transfers, but content does not, and importer just hangs.
4. Console throws error: `Uncaught (in promise) RangeError: Empty text nodes are not allowed` or, in some cases, `Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0`

**What did you expect to happen?**
LaTeX should import properly

**What URL can we use to see the issue?**

**What browser/operating system were you using?**

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by 3mcd** [comment]
Fixed by ff76da8.
