### ISSUE TITLE
Previously published volume URLs (now collections) aren't resolving

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1137]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Visited https://projections.pubpub.org/
2. Clicked 'Volumes' drop-down menu and selected Vol. 13.
3. Page not found
4. The same occurred for volumes 1-12
...

**What did you expect to happen?**
To view the volume content 
**What URL can we use to see the issue?**
https://projections.pubpub.org/talks-collection

**What browser/operating system were you using?**
Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
![image](https://user-images.githubusercontent.com/72410195/98869978-2dcb5180-2438-11eb-970a-79ceea7d1fde.png)
![image](https://user-images.githubusercontent.com/72410195/98870091-6408d100-2438-11eb-84cb-ba75c05497f9.png)

**Who reported this? (If not you)**
Aria Ritz Finkelstein, M.Arch., MS.UD.
ariaritz@mit.edu / www.ariaritzfinkelstein.com

**Comment by 3mcd** [comment]
Resolved by #1140.
