### ISSUE TITLE
Allow compact whitespace before/after bullets in bulleted lists

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1138]
**What's your request?**

Support a more vertically compact linebreak before/after bulleted lists, for cases where they should be nested tightly with other text.

**What would this feature help you accomplish, and why is that important to you?**

In Google Docs, the default style when creating a bulleted list in a new paragraph is to have a full paragraph break rather than a line break between the preceding line and the first bullet.  But you can also fairly intuitively delete that paragraph break and leave just a line break.

In a pub, I often want to have a short bulleted list -- or a series of them throughout a running essay -- w/o breaking the vertical flow of an article, and would like this same visual experience.  

(Also, if I'm importing a compact essay from elsewhere, and it stretches out in the pub, that's repeated extra time to reformat.)

**Have you considered any alternative solutions or features?**

Faking a bulleted list with newlines within a paragraph, and a different character as the 'bullet', offers some of this effect, but is extra effort and doesn't look as nice.  A

---

**Any attachments or reference images? (Drag them here)**

**Are there any other products or services that do this well?**

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***

**Comment by gabestein** [comment]
Closed as not planned. We are working on more customization/font packs, though, which should help.
