### ISSUE TITLE
Hard to resize table rows that are initially out of viewport

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1150]
**What went wrong, step-by-step?**
1. On a wide table that has cells that are out of viewport, scroll to see those cells.
1. Attempt to select the column border to drag
1. Table will snap back to original state with columns out of viewport

...

**What did you expect to happen?**
I should be able to adjust column widths for out-of-viewport cells without it snapping back.

**What URL can we use to see the issue?**
https://copim.pubpub.org/pub/copim-outreach-overview/

**What browser/operating system were you using?**
OS X / Chrome 
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Toby / COPIM

**Comment by idreyn** [comment]
Possibly the same issue as #1148

**Comment by idreyn** [comment]
Appears to be fixed in e740051d8f779cc8c9fe3d4b4203ba52e06b9bbb (but not the same issue as #1148, sadly)
