### ISSUE TITLE
Ability to add custom URL to community footer image 

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1166]
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What's your enhancement request?**
To have the option to change the default community URL on footer images. 

**What would this enhancement help you accomplish?**
In general, this would allow communities to be standalone but link to a relative (i.e., think org plan communities). 
More specifically, I have a newly formed community (Intellectual Property) and am trying to utilize the MITP logo for the footer and link to the the MITP Open page. 

---

**Any attachments or reference images? (Drag them here)**
![image](https://user-images.githubusercontent.com/72410195/100103296-4e2ce000-2e2a-11eb-9e33-350e0c2949ab.png)

**What's the URL to your PubPub community?**
https://intellectual-property-strategy.pubpub.org/

**Who requested this? (If not you)***
N/A

**Comment by gabestein** [comment]
Yay we did this! #1313
