### ISSUE TITLE
[Enhancement Request] Ability to Control Color of Home Banner Text

### ISSUE THREAD

**Issue by writingpoli** [pubpub/pubpub#1168]
I'd like to be able to control the font color for the main banner on our home page. 

Rather than defaulting to black or white text, I'd at least like to be able to use our current theme colors the way the menu text does. 

**What would this enhancement help you accomplish?**

Design consistency.

---

**Any attachments or reference images? (Drag them here)**

https://i.imgur.com/JTm6XZ8.png

**What's the URL to your PubPub community?**

sareview.org

**Comment by gabestein** [comment]
Thanks William. I agree, we should at least add light/dark accent to the options alongside black and white. We'll take this up in our prioritization next week.

**Comment by writingpoli** [comment]
Awesome! Thank you!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by agnescameron** [comment]
++ having the same options as for the top of pubs would be great!

**Comment by metasj** [comment]
+1 :)  (encountered again 2 wks ago)

**Comment by writingpoli** [comment]
Yeah, I found myself wishing for it again the other day, too. :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gabestein** [comment]
Woof, sorry. At this point, we're most likely to address this as part of https://github.com/pubpub/roadmap-repo/issues/7

For now, custom CSS can help here.
