### ISSUE TITLE
Links to pub nodes work only sporadically on initial page load

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1170]
**What went wrong, step-by-step?**
1. Visit a link to a pub node, ie https://readingthecomments.mitpress.mit.edu/pub/ujeil296/release/2#r9630153434
2. Browser will typically not jump to the node – sometimes it does if you refresh and it's already loaded the page, indicating it may be some sort of browser order issue.

**What did you expect to happen?**
Browser jumps to the node.

**What URL can we use to see the issue?**
https://readingthecomments.mitpress.mit.edu/pub/ujeil296/release/2#r9630153434

**What browser/operating system were you using?**
Any
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by 3mcd** [comment]
Fixed by #1186
