### ISSUE TITLE
Pub node links being covered by Pub scroll header on jump

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1171]
**What went wrong, step-by-step?**
1. Visit https://projections.pubpub.org/pub/3fa17lcj/release/1#overview-of-the-papers
2. Notice that the section header gets covered by the pub scroll header

**What did you expect to happen?**
The page should jump so that the section header is visible below the pub scroll header

**What URL can we use to see the issue?**
https://projections.pubpub.org/pub/3fa17lcj/release/1#overview-of-the-papers

**What browser/operating system were you using?**
Chrome / OS X
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Alana Brooks

**Comment by idreyn** [comment]
This is the default browser behavior — we'll need to add a custom bit of router-like code to respond to changes in the URL hash by scrolling to the "right" part of the page.

**Comment by gabestein** [comment]
Yeah, that's a bit of a bummer. I wonder if there's a more CSS-y fix...I can do a bit of poking around.

**Comment by 3mcd** [comment]
This is partially addressed by #1186, although we still have this issue when clicking on reference links. I'll address this in a follow-up PR.
