### ISSUE TITLE
figure > img elements in exports should have display: flex

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#1172]
Our CSS for HTML/PDF exports gives `figure` elements a max-height of 800px. We want images (and videos, etc, I guess) inside of those figures to have `display: flex` so they don't vertically overflow that, but they currently have `display: block` because of a more specific CSS selector. This can cause Paged to freak out when very tall images are added to a Pub.

**Comment by caraya** [comment]
Wouldn't this be fixed by setting the image height to auto instead of a fixed value?

**Comment by gabestein** [comment]
Ah, so this is jut a bit off. It's actually just `figure` that needs `display: flex`, and it's being overwritten by a more specific directive `.editor figure`. Solution is to just prepend that section of the print media styles with `.editor.` Incoming...
