### ISSUE TITLE
Reference popover transparency

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#1178]
**What went wrong, step-by-step?**
1. The reference popover in the formatting bar seems to have a transparent frame that’s just slightly larger than it’s white-backgrounded content. So, you can see text through the popover at times.

**What did you expect to happen?**
The popover should be completely opaque with a white background

**What URL can we use to see the issue?**
Any pub

**What browser/operating system were you using?**
Firefox

---

**Have any screenshots? (Attach them by dragging the image here)**
![Screen Shot 2020-12-03 at 11 57 32 AM](https://user-images.githubusercontent.com/1000455/101181984-721bcd00-3645-11eb-8e58-48d696347ce9.png)

**Comment by 3mcd** [comment]
Fixed by 3baaab6
