### ISSUE TITLE
Connection thumbnail shows even when there is no associated image

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1180]
**What went wrong, step-by-step?**
1. Add this doi as a pub connection: https://doi.org/10.1109/5.771073
2. Connection loads with blank thumbnail, even though no og or other thumbnail tag for it exists.

**What did you expect to happen?**
Connection will not load with a thumbnail.

**What URL can we use to see the issue?**
https://test.duqduq.org/pub/fiu8gyxr/release/1

**What browser/operating system were you using?**
Chrome / OS X
---

**Comment by 3mcd** [comment]
Fixed by 70cdba7
