### ISSUE TITLE
Preview Image for Collections Layout

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1188]
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What's your enhancement request?**
Add 'preview image' to collection layout. 

**What would this enhancement help you accomplish?**
Assuming this will allow images to be displayed for collections when added to the Collections & Pages Block. 

---

**Any attachments or reference images? (Drag them here)**

_Page editor with 'Preview Image' feature_
![image](https://user-images.githubusercontent.com/72410195/101819391-cf52cb00-3aea-11eb-95b2-bc77dbffc531.png)

**Collections & Page Block showing two collections _without image representation_**
![image](https://user-images.githubusercontent.com/72410195/101819197-80a53100-3aea-11eb-9adf-5b93c4e5ab9c.png)

**Collections & Page Block showing _collections_ followed by _pages_ for comparison** 
![image](https://user-images.githubusercontent.com/72410195/101819910-7899c100-3aeb-11eb-82f8-fbbaf544f95e.png)

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***

**Comment by Dawit-Tegbaru** [comment]
Just received a similar request: 
On Fri, Dec 11, 2020 at 7:01 AM Rui Cruz <cruz.rfs@gmail.com> wrote:
Dear Catherine and DawitHope to find you well with this email.I am writing to you on behalf of PhD Career Stories team. Since our last meeting on October 27th, we have been testing different aspects of the PubPub platform, from content creation to social media sharing. I can say that in general our impressions of the platform are very positive! Congratulations on the platform!
I am writing to you today because we are facing a couple technical questions and we hope that you could help us out on clarifying them.I will describe them below. For reference you can access our PubPub test website: [](https://phdcareerstories.pubpub.org/)
Issue #1:
We uploaded some podcasts into the platform. Each individual podcast is in a Pub. Different Podcasts (Pubs) were grouped in different Collections. This corresponds to the Tags/Categories that we are using to categorize the different podcasts.We have these Categories on a dropdown menu at the frontpage. It works great.We also have them at the bottom of the frontpage. For that, **we added them in a “Collections & Pages Block Here lies the problem. Right now the categories at the bottom of the page are in rectangles of different colors. We would like to have more flexibility in the way we exhibit our categories (For instance, we would like them to be in squares of the same color).Is there a way to achieve this?** We were not able to do it through our trials with the different section blocks. My guess is that maybe with an HTML block we could solve this?

**Comment by idreyn** [comment]
Implemented in cd0989656b3b766eddd801ac4a3e123d70f6b09b
