### ISSUE TITLE
No or incorrect "citation_journal_title" meta property

### ISSUE THREAD

**Issue by ThomasJorna** [pubpub/pubpub#1192]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Published multiple articles in the last weeks, had trouble being picked up by google scholar.
2. Looked at header metadata, either there was no citation_journal_title in case of no main collection set, or the citation_journal_title was set as the name of the collection.
...

**What did you expect to happen?**
I expected the citation_journal_title property to be populated with the name of our journal, "Journal of Trial and Error". Because of this Scholar cannot pick up the title of our journal and possibly has a tougher time picking up the articles at all, as we noticed that either no articles were picked up or it took much longer than usual.

My guess as to why it does happen for the HDSR and not us (except for reputation, clicks, citations etc.) is that we do not use the built in CrossRef deposit function, which might supply that information to PubPub otherwise. 

**What URL can we use to see the issue?**
Correct usage: https://hdsr.mitpress.mit.edu/pub/twyc748y/release/1

Absent: https://archive.jtrialerror.com/pub/failfast/release/3
The reason it is absent here is because I set the order of the collections incorrectly, which I will leave for now to illustrate the point.

Incorrect: https://archive.jtrialerror.com/pub/alcoholcues/release/6
All other articles in the issue have this too.

**What browser/operating system were you using?**

---

**Have any screenshots? (Attach them by dragging the image here)**
Correct citation journal title at HDSR: https://hdsr.mitpress.mit.edu/pub/twyc748y/release/1
![image](https://user-images.githubusercontent.com/21983833/102081588-c591d600-3e10-11eb-9829-e5faf240b23f.png)

Missing:
![image](https://user-images.githubusercontent.com/21983833/102081240-38e71800-3e10-11eb-84f0-223fd9de1b58.png)

Incorrect:

![image](https://user-images.githubusercontent.com/21983833/102081272-46040700-3e10-11eb-917f-074e9243aee4.png)

![image](https://user-images.githubusercontent.com/21983833/102081310-53b98c80-3e10-11eb-86be-0af0726db829.png)

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Thanks for your patience over the holidays — this should now be fixed as of 819b3619.

**Comment by ThomasJorna** [comment]
It seems to work now, thank you so much!
