### ISSUE TITLE
Caption crosstalk across images in a page block

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1196]
As an editor editing a page, I'd like to be able to edit text in captions of multiple images in the same block.

Just now, on [iii.pubpub.org](https//iii.pubpub.org) : I had a image Img-1 with a caption C1, in a block. 
* I edited the page, and added another image (Img-2) below the first 
* I typed a caption (C2) into the caption field for Img-2.
* I clicked into the C1, wanting to copy some of that older caption text.  
* It took a moment for that to work -- my cursor didn't appear there right away.
* Suddenly I found the cursor in caption of Img-1, but the text had been replaced with the text I'd just added as C2. The caption of Img-2 was now blank.

**Comment by idreyn** [comment]
Thanks, I also saw this the other day but couldn't make it happen a second time.

**Comment by idreyn** [comment]
I think this should be fixed as of a91172adb029dfe7c6a4ebaff6fffc7ecd049c25 or so but please re-open if you see it again!
