### ISSUE TITLE
Impact Tab is not able to show "Top" pages or Pubs

### ISSUE THREAD

**Issue by ThomasJorna** [pubpub/pubpub#1197]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Wanted to look at the impact tab
2. For "Top Pages", "Top Pubs" and "Most Downloaded" an error is displayed
3. Downloading the .csv yields a file displaying the error message {"status":"failed", "error":"An error occurred while running the query."} 

**What did you expect to happen?**
To be shown that dat.

Seems to come from a 404 error from keen.io, as this does not appear when looking at individual pub statistics, which work fine.
![image](https://user-images.githubusercontent.com/21983833/102235921-28f43480-3ef3-11eb-8489-0bd1110c7e9b.png)
![image](https://user-images.githubusercontent.com/21983833/102235979-390c1400-3ef3-11eb-862d-848dd6ab2e2f.png)

**What URL can we use to see the issue?**
any dash i'd think, otherwise https://archive.jtrialerror.com/dash/impact

**What browser/operating system were you using?**
Firefox/Chrome/Brave, Linux
---

**Have any screenshots? (Attach them by dragging the image here)**
Error:
![image](https://user-images.githubusercontent.com/21983833/102236114-635dd180-3ef3-11eb-89c5-08ec085f5064.png)

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Thanks Thomas! Should be fixed now.
