### ISSUE TITLE
Non-header IDs are not stable

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1202]
**What went wrong, step-by-step?**
1. Copy the link to the first paragraph here: https://notes.knowledgefutures.org/pub/badge-platform-experiment/release/20
2. Visit the link in a new tab.
3. Notice the viewport does not jump to the first paragraph.
4. Open document source.
5. Search for the copied ID fragment.
6. Notice it does not exist on the page, and the ID for the first paragraph has changed.

**What did you expect to happen?**
The ID should be stable, forever, so you can link to a paragraph.

**Comment by idreyn** [comment]
This was addressed in 316b6e227a47fbd9ab5a66e526ae055153efd598 by removing the block-level link buttons for documents that have not been re-released since block IDs were invented and thus have unstable IDs.
