### ISSUE TITLE
(Author) citation style is missing closing parenthesis.

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1220]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Add a structured citation to a pub.
2. In Pub Settings, choose the (Author) inline style.
3. It will appear with the closing parenthesis, per the screenshot.
...

**What did you expect to happen?**
Closing parenthesis should be present.

**What URL can we use to see the issue?**
https://demo.duqduq.org/pub/diasuuy0/draft

**What browser/operating system were you using?**
Mac / Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
<img width="308" alt="Screen Shot 2021-01-04 at 18 18 28" src="https://user-images.githubusercontent.com/639110/103589455-6bd57680-4eb9-11eb-9dbf-5f91bf4a2b41.png">

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Closed in bdaa083c178668fa619aa9bfbdc748df81007eed
