### ISSUE TITLE
Layout queries should be able to load Pubs from private Collections

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1222]
Seems like a regression – for some reason, page queries are not showing properly for logged out users. E.G., this page is blank when it should have a pub displayed:

https://tmb.apaopen.org/webinars

**Comment by idreyn** [comment]
This turned out to be an issue where the Collection the block was querying was private. This should be possible since it doesn't really leak any information to the reader; I've updated the title of the issue to reflect this.

**Comment by idreyn** [comment]
Fixed in, let's say, #1299
