### ISSUE TITLE
TOC not working

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1226]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. When you click on the header in the toc, nothing happens
2. I know I've reported this and you've worked on this problem before! Not sure why it's sticking around
...

**What did you expect to happen?**

**What URL can we use to see the issue?**
https://commonplace.knowledgefutures.org/pub/trust-through-trickery/release/1

**What browser/operating system were you using?**
chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
http://g.recordit.co/RG2ZsV0zxE.gif

**Who reported this? (If not you)**

**Comment by pcuellar** [comment]
Nudging this request. Just learned our TOC's are not working as we are preparing to launch a revamping of our publication.

**Comment by gabestein** [comment]
Hello — we took a look at this this morning and were unable to replicate. What's your community, browser, and OS? We'll take another look.

**Comment by pcuellar** [comment]
Our community is https://techotherwise.pubpub.org/, I am on Brave, MacOS 10.15.7. The way I am experiencing the issue is links don't work from the TOC at the top, but if you scroll down and use the pinned TOC, those links do work.

**Comment by gabestein** [comment]
Was fixed somewhere along the line. Not completely sure where.
