### ISSUE TITLE
Old pubs (from 2019) appear in searches + collections but won't open

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1228]
Example (which I've seen on other communities, again here): 

On the Structuring Collective Knowledge site, some pubs that never had a public release now won't open, when following a previously-shared URL or when clicking through from a user's profile or a collection dashboard.

[Dashboard overview](https://knowledgestructure.pubpub.org/dash/overview):
<img width="986" alt="Screen Shot 2021-01-08 at 17 56 52" src="https://user-images.githubusercontent.com/1615548/104073329-6474dc80-51db-11eb-9c85-2d3816ae1180.png">

The four pubs shown here in this collection (Course Notes and 3 new pubs) don't open: clicking on their titles yields a simple "Page Not Found" error.
<img width="337" alt="Screen Shot 2021-01-08 at 18 03 31" src="https://user-images.githubusercontent.com/1615548/104073455-b584d080-51db-11eb-8d55-40746e365682.png">

In contrast, a fifth pub created around the same time and not published, opens without complaint.
<img width="332" alt="Screen Shot 2021-01-08 at 18 04 09" src="https://user-images.githubusercontent.com/1615548/104073498-d0efdb80-51db-11eb-9d7d-f37d76c75814.png">

This breaks some old links, and makes it hard to clean up collections and histories.

**Comment by idreyn** [comment]
None of these Pub have any Branches, which makes me think they were corrupted in the mid-2019 migration. However, they also don't have any draft content so you're not missing much :)

I can remove them if you like — otherwise, they will probably become re-accessible in the near future as we are set to remove Branches as a concept anyway.

**Comment by metasj** [comment]
That sounds right -- if it's no trouble, do remove them to avoid [my] future confusion.  But I don't suppose anyone else will notice!

**Comment by idreyn** [comment]
Done!
