### ISSUE TITLE
C/P images and Captions

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1229]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. NIME conference is using PubPub for their conference submissions and created templates to guide their participants. 
2. Upon copying and pasting the temaples into a new pub, submitters have found that image captions do not carry over.
...

**What did you expect to happen?**
Caption would appear below c/p image

**What URL can we use to see the issue?**
https://nime.pubpub.org/submissions
and on any PubPub draft

**What browser/operating system were you using?**
I don't know what the NIME submitter was using but I also experienced this problem and I'm on Chrome.
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Oh, I definitely goofed this up when we added the alt text field. Will take a look right now.

**Comment by idreyn** [comment]
Fixed as of 3ada3f41ed1a97d96e8683c4789e5dfa91a1fabc

**Comment by coahearn** [comment]
Thanks!
