### ISSUE TITLE
Multiple discussion anchors on same line always repeat name of first discussion

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1230]
**What went wrong, step-by-step?**
1. Add a discussion
2. Add another to the same line from a different user
3. Name of first person repeats twice

**What did you expect to happen?**
See the name of the second person's discussion

**What URL can we use to see the issue?**
https://qubqub-br-new-discussions-plug.herokuapp.com/pub/8td7qygp/draft

**What browser/operating system were you using?**

---

**Have any screenshots? (Attach them by dragging the image here)**
<img width="312" alt="Screen Shot 2021-01-12 at 10 35 15" src="https://user-images.githubusercontent.com/639110/104335932-dc842080-54c1-11eb-9b05-ccf7af9e6e7e.png">

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Fixed in 0ec2d886d5a85949a9bd20b64530fac496b07137
