### ISSUE TITLE
Add a simple JS feedback widget to every page.  

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#124]
I don't see a good free-software option.  Asking people to scroll to page bottom, log in to github, and create a ticket (without autofilling info on what browser they're using / what page they were visiting / what their pubpub user is) takes too long, will lost most feedback.

Free-beer option: Doorbell.io  
   https://doorbell.io/register?plan=free

Awesome, automatic screenshot + visual annotation + text annotation, but $20/mo:  
   https://usersnap.com/pricing

Medium term: clone usersnap in free software, run as side business ;)

**Comment by isTravis** [comment]
Yes. Absolutely. Let's try playing with UserSnap for a bit. Added in 3b85b14468e1a0bf7d3c85ed96fd6303f259ce12. 

Should be live now, let's see how useful it is!
