### ISSUE TITLE
Line breaks in pub descriptions?

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#1242]
It would be great to be able to have line breaks in pub descriptions! This would allow us to use the field for (e.g.) epigraphs to 
book chapters.

Here's the example I was talking over with Catherine in the chat during office hours.
https://mitp-arch.pubpub.org/pub/m4z3y70q

I think it would be cool to have the epigraph carry over into the TOC with the ll breaks intact, so that it would still be legible (and look right) here.
https://mitp-arch.pubpub.org/the-architecture-machine

There must be reasons not to want this?

**Comment by gabestein** [comment]
Indeed — these are meant to be previews that can be displayed in multiple places where line breaks may either not make sense (like an Issue Page) or not be supported (like social media sites). As much as we can, I think it makes sense to restrict rich text to the pub body.
