### ISSUE TITLE
Allow creating a new collection from most interfaces that ask you to choose one

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1243]
When editing a pub, I often want to put pubs into a new collection (cloning a page section, for instance, to a new iteration).  Having to leave the editing screen that offers a collection dropdown to hunt for where to create one is distracting, and can make me lose my place in the original flow.   Switching to a new tab to create the collection also doesn't update the settings page offering the dropdown, so I have to remember to a) create a new collection, b) save the settings so far without that collection, c) refresh.  

An option for "+ add collection" in the dropdown, similar to "add folder" options in file system menus, would be rewardingly handy.

**Comment by gabestein** [comment]
Closed by #1627
