### ISSUE TITLE
Feature: Wordpress import

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#125]
I have a WP blog that I want to import into PubPub.  [Lots of science blogs are where first-pass publishing of results and charts happens.]

a) Is this a recommended use of P²?  If so, add a manual page about it.  
b) Add an import tool (to at least capture original posts & metadata, if not comments). 
c) Make this work incrementally & on the client side, in case there's a huge import...

**Comment by writingpoli** [comment]
Was this ever completed? Linked request is closed and unclear.

**Comment by gabestein** [comment]
We have the capability to do this now on the backend, though we don't yet have a UI for it. So, closing this out – we will develop a UI at a later date.
