### ISSUE TITLE
Federate PubPub with ActivityPub

### ISSUE THREAD

**Issue by aschrijver** [pubpub/pubpub#1251]
PubPub has a Community concept and Collaboration / Social features. The discussion I started is about considering:

> **What opportunities can Federation bring to your business domain, when incorporated from an early start?**

Sooo many applications are based on a Community concept. Could this be federated? Between PubPub instances? Universally? Why would a community be bound to a single server or cloud-based application?

The discussion may inspire a brainstorm on what is possible when going this route.

- See discussion: [Federating PubPub. Community Has No Boundary](https://github.com/pubpub/pubpub/discussions/1249)

(_**Note**: This is a heads-up issue only to draw attention to #1249 I created yesterday, and to get 'ActivityPub' as keyword in issue search. It might be closed until there is a concrete enhancement use case._)

**Comment by gabestein** [comment]
Okay, thanks. Noted and we will follow up on the discussion thread.

**Comment by gobengo** [comment]
@gabestein let's do this

**Comment by gobengo** [comment]
In light of recent events, has this risen on your roadmap? :) @gabestein
