### ISSUE TITLE
Can't change collection title

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1255]
### What went wrong, step-by-step?
1. Tried to change collection name via the settings page
2. On clicking save, got success message and no console or network errors.
3. On refresh, collection name remains the same.

### What did you expect to happen?
Name changed.

### What URL can we use to see the issue?
https://demo.pubpub.org/dash/collection/8jyy2z6g/settings

### What browser/operating system were you using?

===

**Comment by idreyn** [comment]
This is working fine for me — are you still able to reproduce?

**Comment by gabestein** [comment]
Yup. I just realized it's sending 3 requests on my browser. One has the new title. Then the other two have the old title. So I think it might be saving and then overwriting it? Very strange...

**Comment by idreyn** [comment]
I think we addressed this on a call but I forget what the outcome was. Is this one of those things where it's ambiguous whether you need to click the Save button or not — not a bug per se but just bad UX?

**Comment by gabestein** [comment]
It's just less than ideal UX. I think we can close in favor of knowing we're gonna have to re-factor the settings pages across the board at some point.
