### ISSUE TITLE
Improve feedback workflow: prominent link, new tab, 'new issue' page

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#127]
Right now clicking on feedback replaces the current page, and takes you to the Issues page on github.   To make it faster:
- Make the link more prominent (a different color?)
- Open in a new tab or popup
- Link directly to https://github.com/pubpub/pubpub/issues/new

(last issue on feedback :)

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

We've mostly replaced this feedback mechanism with email and Discourse for now. But this reminds me to discuss adding a link to Discourse to PubPub!
