### ISSUE TITLE
Pub deposits with issue primary collections with blank date published should default issue publication date to collection creation date

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1273]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Tried to deposit article in a primary collection with issue type
2. Deposit used today's date for the issue publication date, even though the issue was published months ago

### What did you expect to happen?
Default issue publication date when not set in collection metadata should be the creation date of the collection

### What browser/operating system were you using?

===

**Comment by idreyn** [comment]
Fixed in 90814cba18f115d1186a19ba6872709c914a3fb2
