### ISSUE TITLE
MS Word on Mac pastes into PubPub as an image!

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1278]
### What went wrong, step-by-step?
1. Copy any text from a document in MS Word on Mac.
2. Paste will appear as an image!
3. If you paste and match formatting, or paste from Pages with the docx open, it pastes correctly.

### What did you expect to happen?
Paste appears as text.

### What URL can we use to see the issue?
n/a

### What browser/operating system were you using?
n/a

===

### Who reported this? (If not you)
Parmita / RRC19

**Comment by gabestein** [comment]
Seems to be a weird known thing: https://github.com/WordPress/gutenberg/issues/4854

**Comment by gabestein** [comment]
https://github.com/WordPress/gutenberg/pull/4882/files

**Comment by idreyn** [comment]
Fixed (at least for my copy of Office) in 2f933277a15a263a1ab4bbd36b96d3a106544aec
