### ISSUE TITLE
Login usability: make it a default option; 

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#128]
When clicking on 'New Pub' or other actions, a logged out user is currently taken to http://v2.pubpub.org/signup  with only a small link at the bottom of the page (requiring a scroll on many devices) to signing in for existing users.  

_Options_:
- Store a cookie to indicate if they are likely to have an account already, and default to the signin page
- Offer a "stay logged in for 30 days" option (cookie again)

**Comment by isTravis** [comment]
Stay logged in for 30 days is the default expiration on logged in cookies now. Login button also more prominent at the top of the page, so hopefully the small scroll-necessary login button is not longer an issue.
