### ISSUE TITLE
Links in footnotes running wild!

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1286]
For an example see here: https://commonplace.knowledgefutures.org/pub/6vwhguqu/release/4

Links in footnotes are extending beyond their little footnote box. Rogues!

<img width="895" alt="Screen Shot 2021-02-17 at 11 27 56 AM" src="https://user-images.githubusercontent.com/32333767/108234923-4d4ad800-7113-11eb-91da-8806e4090d06.png">

**Comment by metasj** [comment]
It does make them feel alive... same as #1227 ?

**Comment by idreyn** [comment]
Fixed in f1600a2f3434b1f07bc90d606be6613cfa998740
