### ISSUE TITLE
Annotation of superscript text

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1301]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. posted an annotation on text that's formatted as superscript in a pub draft
2. annotation box appears very far over in the right margin
...

### What did you expect to happen?
appear as normal

### What URL can we use to see the issue?
https://notes.knowledgefutures.org/pub/ettejwvb/draft

### What browser/operating system were you using?
Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="1296" alt="Screen Shot 2021-02-24 at 11 35 12 AM" src="https://user-images.githubusercontent.com/32333767/109033196-6401a980-7694-11eb-9c6c-4bcbc6a6fe1b.png">

### Who reported this? (If not you)
CA

**Comment by idreyn** [comment]
Fixed (though pending deploy) in 9810fcb805cb7f2f5e6ef8101367ac8d3829262a
