### ISSUE TITLE
Downloading a Pub - Footnotes go to itemized list 

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1312]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. When downloading a Pub into Word,
2. Any footnotes go into an itemized list at the end of the document rather than being linked in-line
...

### What did you expect to happen?
I would expect the footnotes to be linked, either as references at the end of the doc, or as actual footnotes in the bottom margin

### What URL can we use to see the issue?
https://commonplace.knowledgefutures.org/pub/trust-through-trickery/release/1

### What browser/operating system were you using?
Chrome/Duckduckgo extension on Mac/Catalina

===

**Comment by gabestein** [comment]
Was fixed somewhere along the line, and I just regenerated the docx.
