### ISSUE TITLE
Unloaded Images

### ISSUE THREAD

**Issue by junemanabraham** [pubpub/pubpub#1330]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. The images at https://commonplace.knowledgefutures.org/pub/3ohbx7io/release/2   as well as at all pages of https://commonplace.knowledgefutures.org/  do not load properly. We (Dasapta and I) access it in Indonesia (with Indonesian IP Address)
2. However, if I activate my VPN with USA IP Address, the images load just perfectly.
3. Could you check if commonplace.knowledgefutures.org is "friendly" with mobile IP address of Indonesian?
...

### What did you expect to happen?
Images load properly.

### What URL can we use to see the issue?
Mentioned above.

### What browser/operating system were you using?
Chrome, Firefox, on Android OS.

===

### Have any screenshots? (Attach them by dragging the image here)
I have sent it to Sarah Kearns.

**Comment by idreyn** [comment]
Hello — we've adjusted our CDN settings to make it easier to access content from `assets.pubpub.org` in Indonesia. Please let me know if you continue to have problems loading images after this!
