### ISSUE TITLE
Unneeded navbar fading at certain widths

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1334]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Browse hdsr with a window > our ~1256px breakpoint
2. Last item in navbar is "faded" despite not needing to be.

### What did you expect to happen?
No fading on last item.

### What URL can we use to see the issue?
https://hdsr.mitpress.mit.edu/

### What browser/operating system were you using?
Chrome / Mac

===

### Have any screenshots? (Attach them by dragging the image here)

<img width="1194" alt="Screen Shot 2021-03-31 at 11 53 26" src="https://user-images.githubusercontent.com/639110/113173741-b4ca6c00-9217-11eb-8c15-2f2771abf8fb.png">

**Comment by coahearn** [comment]
Could also be why the Commonplace nav bar looks like this right now
![Uploading Screen Shot 2021-04-05 at 9.13.13 AM.png…]()

**Comment by gabestein** [comment]
Ideas:
- JS to determine overflow, + small shadow and/or arrow
- More dropdown
- Mobile-specific solution
