### ISSUE TITLE
Wonky drag and drop for pinned pubs

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1337]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. selection of a pub puts it and the bottom of the pinned pubs list (hard if the list is long and you can't actually see where it was added until you scroll down. Recommend adding to top)
2. dragging it up to the top position is hard to control. the screen scrolls up past the block quickly, so I end up moving it incrementally.
...

### What URL can we use to see the issue?
likely any PubPub community but I was in Commonplace

### What browser/operating system were you using?
Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
See video: https://recordit.co/C5xzEPEEUP

### Who reported this? (If not you)
CA

**Comment by idreyn** [comment]
Resolved by c23ec9d0461dbc63672ec6c80ddc5dd8acc95622 (fix will go out later today I think)
