### ISSUE TITLE
Some pubs not properly chunked in algolia

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1339]
### What went wrong, step-by-step?
1. Search for text in [this article](https://hdsr.mitpress.mit.edu/pub/kxks56er/release/4) on HDSR (e.g. "football")
2. Articles does not appear in search

It appears we're having issues with chunking in algolia.

### What did you expect to happen?
Article appears in search.

### What URL can we use to see the issue?
https://hdsr.mitpress.mit.edu/search?q=football

### What browser/operating system were you using?

===

**Comment by isTravis** [comment]
# What
fine
##  #Okay
Fine
### Hello
**_[This is wild](url)_**
