### ISSUE TITLE
Table formatting wonkiness 

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1354]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. The table does not want to change
2. I fight with the table
3. When I highlight a column to merge cells within it, the page scrolls and the options menu is hard to navigate
...

### What URL can we use to see the issue?
https://recordit.co/iKqyqDf4yk

### What browser/operating system were you using?
Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
https://recordit.co/iKqyqDf4yk

**Comment by gabestein** [comment]
To replicate:

- In Chrome at least (should check Safari, too)...
- Open table menu where menu is off bottom of viewport
- When mousing over open menu, page scrolls down without user input
