### ISSUE TITLE
Reviews tab no longer shows number of reviews

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1359]
Must be related to the recent dash pushes.

### What went wrong, step-by-step?
1. Requested publication.
2. Review shows up on the review tab.
3. No number shows up in the "reviews" tab link indicating an open review.

### What did you expect to happen?
A number shows up in the "reviews" tab link.

### What URL can we use to see the issue?
https://demo.pubpub.org/dash/reviews

### What browser/operating system were you using?
Chrome Latest / Mac Latest

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="1134" alt="Screen Shot 2021-04-20 at 13 46 32" src="https://user-images.githubusercontent.com/639110/115441413-d4353300-a1de-11eb-8731-356488f61df5.png">

### Who reported this? (If not you)
Scott / crimEmpire

**Comment by idreyn** [comment]
We had to remove this to ship the overview performance improvements...it'll be fixed by #1360.
