### ISSUE TITLE
Table number customization

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1383]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
Being able to change the Table number - I don't like that it autogenerates the table number. Some tables are imported as images and sometimes tables are imported in more like the Excel-esque style that is embedded. 

### What would this enhancement help you accomplish?
This would let people customize their table numbers. 

---

### Any attachments or reference images? (Drag them here)
<img width="694" alt="Screen Shot 2021-04-29 at 4 23 03 PM" src="https://user-images.githubusercontent.com/20121061/116613885-3856a600-a907-11eb-964e-559ae03561c6.png">

### What's the URL to your PubPub community?
https://academicentrepreneurship.pubpub.org/pub/tzu9lgys/draft
Note that the second table is also called "Table 1"

**Comment by gabestein** [comment]
Thanks for writing in. I agree we should ultimately allow customization of the generated table labels. For now, however, you can turn off the auto-generated table numbering and use your own text in the Pub Settings:

<img width="392" alt="Screen Shot 2021-04-30 at 10 09 39" src="https://user-images.githubusercontent.com/639110/116706979-2ffc7a80-a99c-11eb-82f2-633e4cbc945a.png">
