### ISSUE TITLE
Quick Actions appearing even when logged out.

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#1392]
### What went wrong, step-by-step?
The new Dashboard quick-actions are great! However, they appear for all users - even when logged out. 

### What did you expect to happen?
I would expect the Quick actions to only be visible if you have permissions to do the things the quick actions describe (e.g. the 'Edit Home Page' button takes you to a 404 when not logged in.

### What URL can we use to see the issue?
[notes.knowledgefutures.org/dash](notes.knowledgefutures.org/dash)

### What browser/operating system were you using?
Firefox, OSX

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="1433" alt="Screen Shot 2021-05-04 at 8 02 52 AM" src="https://user-images.githubusercontent.com/1000455/117020405-6865c680-acc4-11eb-8123-ae563bfab733.png">

**Comment by idreyn** [comment]
Fixed in ddd5cc9
