### ISSUE TITLE
PDF download broken again.... will not download entire document <https://doi.org/10.21428/8bbb7f85.35a0e14b>

### ISSUE THREAD

**Issue by BruceCaron** [pubpub/pubpub#1400]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1.   NOT the formatted PDF... the auto-generated one.
2.  When I download, only 147 pages download, not the whole document.
...

### What did you expect to happen?
The whole document PDF to download.

### What URL can we use to see the issue?
https://doi.org/10.21428/8bbb7f85.35a0e14b

### What browser/operating system were you using?
firefox also Chrome

===

**Comment by BruceCaron** [comment]
This is still broken.  I've recreated this on other computers.

**Comment by gabestein** [comment]
Ah, sorry Bruce, I missed the edit of your original post. That's quite helpful! I was able to find the issue (it's a long story, but related to #1172). We're working on a fix (#1414) which should be live pretty soon.

**Comment by BruceCaron** [comment]
Hi Gabe,

This is still broken....  Just a ping.  What's the timing on the fix?

**Comment by gabestein** [comment]
Sorry Bruce, we're still waiting for it to be pushed into production. I'll check in on it tomorrow morning during our eng meeting.

**Comment by gabestein** [comment]
Actually, never mind that. My apologies! It was deployed on Friday, and I just forgot to clear the download cache for your Pub. I just regenerated the PDF, and it now appears to work all the way through.
