### ISSUE TITLE
MS Word download does not download images.

### ISSUE THREAD

**Issue by BruceCaron** [pubpub/pubpub#1406]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. I did the autogenerated MS Word download...
2. Word did not show any images, just spaces between paragraphs (see screenshot).
...

### What did you expect to happen?
images with the text.

### What URL can we use to see the issue?
https://openscientist.pubpub.org/pub/play/release/2

### What browser/operating system were you using?
Chrome and Firefox

===

### Have any screenshots? (Attach them by dragging the image here)
yes
<img width="1164" alt="PubPub_original" src="https://user-images.githubusercontent.com/3869816/117857816-0a942a00-b242-11eb-854c-1a0924ba9d87.png">
<img width="1164" alt="MSWord_output" src="https://user-images.githubusercontent.com/3869816/117857846-1253ce80-b242-11eb-8b6c-746d7cca23b1.png">

**Comment by gabestein** [comment]
Hi Bruce — I'm not able to reproduce this issue. Images load when I open them in the download word version.

Which operating system / version of Word are you using?

**Comment by gabestein** [comment]
Sounds good. I was unable to replicate with Pages or Word on my end. Feel free to re-open if you keep encountering this.
