### ISSUE TITLE
Unable to subscribe to PubPub mailing list in Firefox

### ISSUE THREAD

**Issue by cyrialize** [pubpub/pubpub#1411]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. I signed up for a new account for PubPub
2. I clicked the checkbox to receive news and updates (e.g. signed up for the mailing list)
3. I received this email:
![pub-pub-confirm-subscription](https://user-images.githubusercontent.com/10124248/118281091-d8c9d000-b49a-11eb-9407-717c335e6313.JPG)
4. I clicked on the link "Yes, subscribe me to this list."
5. I was brought to the subscription page, I confirmed that I was human going through the reCaptcha
6. I was then brought to this page:
![pub-pub-subscription-issue](https://user-images.githubusercontent.com/10124248/118281292-0c0c5f00-b49b-11eb-9c0d-8dfbfa3913b1.JPG)
7. I tried multiple times by turning off my ad blocker (uBlock Origin) as well as turning off Firefox's Enhanced Tracking Protection. Once I turned off the tracking protection, my screenshot looked like this:
![updated-pub-pub-subscription-issue](https://user-images.githubusercontent.com/10124248/118282454-47f3f400-b49c-11eb-9a45-44874f015def.JPG)
8. When I switched over to Chrome, I was able to subscribe successfully:
![subscription-confirmed](https://user-images.githubusercontent.com/10124248/118282980-d9fbfc80-b49c-11eb-9e0d-21c18727f996.JPG)

### What did you expect to happen?
I expected to see a success page, letting me know that I signed up for the mailing list.

### What URL can we use to see the issue?
This is the URL from the "Yes, subscribe me to this list." page: 
https://us5.mailchimp.com/mctx/clicks?url=https%3A%2F%2Fpubpub.us5.list-manage.com%2Fsubscribe%2Fconfirm%3Fu%3D9b9b78707f3dd62d0d47ec03d%26id%3Dbe26e45660%26e%3D987d20112d&h=af3def96cc849d86a6eff1c3a0abf78ac421d60a91d107dae0c671fc5c199930&v=1&xid=24982f5a88&uid=127559626&pool=contact_facing&subject=PubPub%3A+Please+Confirm+Subscription

This is the URL from the confirmation subscription page:
https://pubpub.us5.list-manage.com/subscribe/confirm

### What browser/operating system were you using?
I am using Mozilla Firefox 88.0.1. 

I am using Windows 10 Pro version 20H2, OS build 19042.985

### Additional Notes

- I attempted to go through subscription multiple times, I achieved the same result. 
- I opened the console while attempting this, and saw that I got a HTTP 406 error:
![http-406](https://user-images.githubusercontent.com/10124248/118282120-ef245b80-b49b-11eb-9cb8-23df2ec83781.JPG)
- I believe this mainly has to do with how Firefox operates in terms of blocking. I turned content blocking off, but I still received these errors in the console:
![additional-error-messages](https://user-images.githubusercontent.com/10124248/118283228-20515b80-b49d-11eb-82be-94eb4eb475fc.JPG)

===

### Have any screenshots? (Attach them by dragging the image here)
See screenshots above.

### Who reported this? (If not you)
I reported this.

**Comment by gabestein** [comment]
Thanks for sending this in. Unless I'm confusing things, it looks like this all occurred Mailchimp's side, which means that, unfortunately, we don't have much control over it. You could try reporting it to Mailchimp directly [via their help](https://mailchimp.com/contact/).

Just in case, though, I did take a look and was unable to replicate in Firefox. I got the captcha and was able to fill it out and get to the success screen without error. So, my guess, given the error messages you got, is it was a transient issue with Mailchimp that has now been fixed.

**Comment by cyrialize** [comment]
Sounds good! Thank you so much for the quick response.
