### ISSUE TITLE
Collection order drag + drop

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1415]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Pub order in collection won't change as I drag + drop into place
2. Pubs will not move to the position I drop them in and also seem to change the order of other pubs
3. Could it have to do with it being a secondary collection? Did not have this issue in the primary book collection
...

### What URL can we use to see the issue?
was here: https://academicentrepreneurship.pubpub.org/dash/collection/zcwtvd4e/overview

### What browser/operating system were you using?
Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
https://recordit.co/mwpR0KoTHK

**Comment by idreyn** [comment]
Found the issue with this — there were several duplicate `CollectionPub` records linking a Pub with this Collection, and one Pub in here that belongs to another Community. Very unsure how this happened, but I cleaned that up and drag/drop should be working here now.
