### ISSUE TITLE
No spaces on Pub to Request Publication or Publish

### ISSUE THREAD

**Issue by scottjacques** [pubpub/pubpub#1425]
When I make a Pub that’s just a Connection, I have to hit the spacebar to Publish. Nor can someone "Request Publication." New people won’t realize that, which will lead to unsubmitted works. It is also a small pain for me. Can you remove the requirement, i.e. allow (request of) publication with zero characters?

For CrimRxiv.com

**Comment by gabestein** [comment]
Closing as stale. Will be receiving attention in https://github.com/pubpub/roadmap-repo/issues/14
