### ISSUE TITLE
Redirect from Community-level to PubPub-level /user/:slug route for users unaffiliated with a Community

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1429]
### What's your enhancement request?
Right now, any user on PubPub is rendered with the community layout if you visit community.pubpub.org/user/slug.

This allows the community to be the target of SEO spam, whereby someone could create a spam user account with links back to a spam site, and then link to that user profile on an authoritative community.

It could also be used for social manipulation where someone could claim membership in a community and use the link as proof.

Instead, we should return a 404 unless the user has published in that Community (e.g. their account is added as a contributor on 1 or more Pubs or Collections) or is an explicitly added Member of the community at any scope.

### What would this enhancement help you accomplish?
Eliminate SEO spam.

---

**Comment by idreyn** [comment]
Some context on this task

We need to modify the `/user/:slug` route which renders a User page in one of two different contexts:

- In a Community, as here: https://notes.knowledgefutures.org/user/ian-reynolds
- On the "base PubPub" site as here: https://www.pubpub.org/user/ian-reynolds

This route is defined in `server/routes/user.tsx`. For a given Community, we want to redirect from this first version of the page to the second "base PubPub" version if the User has no affiliation to the Community. Roughly what we need to add to this route is:

```ts
if (!initialData.locationData.isBasePubPub) {
    const isUserAffiliated = await getIsUserAffiliatedWithCommunity({
        userId: userData.id,
        communityId: initialData.communityData.id,
    });
    if (!isUserAffiliated) {
        // Redirect to www.pubpub.org/user/${userData.slug}
    }
}
```

Where the core of this task is to write the as-yet nonexistent `getIsUserAffiliatedWithCommunity` function. There are a few ways a user can be affiliated with a Community:

- They can be a `Member` of a `Community`, or of a `Collection` or a `Pub` inside that Community
- They can have a `PubAttribution` or `CollectionAttribution` inside that Community

(Monospacing all of these in a sort of pedantic way to emphasize that there are database models by these names)

`getIsUserAffiliatedWithCommunity` should thus query for `Member`, `PubAttribution`, or `CollectionAttribution` models that are related to both the User and Community in question and report whether it finds any.
