### ISSUE TITLE
Feature request: Possibility to choose different languages

### ISSUE THREAD

**Issue by danicotillas** [pubpub/pubpub#143]
It would be great, as the platform is already translated that in Settings you are able to choose other language as spanish.
Thanks

**Comment by isTravis** [comment]
Unfortunately, this is not something we can prioritize on our current roadmap. We are more than supportive of PubPub forks that are translated until we have the bandwidth and architecture to support translations.

**Comment by jacksongoode** [comment]
@isTravis It would be great to have this reopened as a possibility for folks to publish two versions of the paper in different languages. Thanks!

**Comment by gabestein** [comment]
Hello! You can do this with the Connections feature by publishing two Pubs, one in each language, and linking them together with an isTranslationOf connection.

**Comment by jacksongoode** [comment]
@gabestein That's fantastic to hear - do you have an example of a paper that does this?

**Comment by gabestein** [comment]
Sure thing. Here's an example: https://hms.mediastudies.press/pub/simonson-exclusiones/release/2
