### ISSUE TITLE
Include publisher field and custom publication name in metadata (at community level, probably?)

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1434]
### What's your enhancement request?
Be able to specify the publisher and custom publication name at the community level.

### What would this enhancement help you accomplish?
- Generate publisher metadata tags for citations, Google Scholar, crossref, and others.
- Specify a different name for citations

### Features

1. New community settings text field under "details": "Cite as." If filled out, this field replaces the community name as the text in journal and conference (but not book chapter) collections:
-  The name of the `container-title` in all citationjs callsites (cite as dropdown, pub settings, pub dashboard overview)
- The name of the `citation_journal_title` in HTML meta tags on Pub and collection pages
- The name of the publication in exports (cover page and headers)
- The name of the `<journal_metadata><full_title>` in crossref deposits

2. New community settings text field under "details": "Publisher." If filled out, this field is used in all types of collections for:
- The name of the `publisher` in all citationjs callsites (cite as dropdown, pub settings, pub dashboard overview)
- A new `citation_publisher` HTML meta tag on Pub and collection pages
- A new publisher name in export cover pages
- The name of the `<publisher><publisher_name>` in crossref deposits

**Comment by howebenhowe** [comment]
[publisher crossref reference](https://data.crossref.org/reports/help/schema_doc/4.4.2/schema_4_4_2.html#publisher)
