### ISSUE TITLE
Community details not updating

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1468]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Update community description in Settings, hit save, but it doesn't update/save
2.
...

### What URL can we use to see the issue?
https://communitypublishing.pubpub.org/

### What browser/operating system were you using?
Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
https://recordit.co/rUhPqMsbkG

**Comment by gabestein** [comment]
This is a variant of https://github.com/pubpub/pubpub/discussions/1413. It's very bad UX, and we'll fix soon. The solution, shockingly, is to not click save.
