### ISSUE TITLE
Filter out bounces/vacation mail so they don't generate fresh tickets

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1475]
The pubpub feed + fresh ticket system are handy ways to keep track of new changes.   However every time a newsletter goes out we get a raft of bounces and vacation mail that each generate a new ticket; making it harder to use.

>  "Automatic reply: [EXTERNAL] <email subject>"
> "Automatische Antwort: <email subject>"

It would be ideal to filter these out before they generate tickets.

[not sure where to file, so putting it here]

**Comment by idreyn** [comment]
This is likely an issue with the Freshdesk Slack plugin — going to close this as it's unrelated to the PubPub product/codebase.

**Comment by gabestein** [comment]
Indeed. We already filter them out of Freshdesk itself, auto-deleting them from all queues once they come in. But afaik, there's no way to stop them from sending to the Slack feed. I recommend muting notifications for that channel.
