### ISSUE TITLE
Explore page refresh

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1478]

**Comment by coahearn** [comment]
Communities to include (also in email):

Community resources: AfricArXiv | Digital Scholarship at the British Library | Open a GLAM Lab | COPIM | CrimRxiv | CriminologyOpen | Bulletin of the AAS
Museums: Iowa State University Museums | Williams College Museum of Art
Case Studies: SERC Case Studies in Ethical Computing
Book collections: MIT Press COVID-19 Library | MIT Press Open Architecture Series
Books: Phone and Spear | Sustainability Science | Frankenstein | Databases, Revenues, & Repertory: The French Stage Online, 1680-1793 | Academic Entrepreneurship for Medical and Health Scientists
Journals: Harvard Data Science Review | Sonic Scope | Technology, Mind, and Behavior | San Antonio Review | Contours Collaborations | San Antonio Review | Cursor | Data & Analytics for Good | Bee XML
Conferences: Spreading Facts | Pandemics and Games Essay Jam | Met x Microsoft x MIT Hack  
Student publications: ASSOCIATION (Cornell) | Journal of Graduate Food Studies (NYU)
Learning series: Fermentology
Reports: MIT Open Access Task Force 
Review: Data Feminism | Rapid Reviews: COVID-19 | Reviews in DH | Consejo Nuevo León
Press: Media Studies Press | Goldsmiths Press | MIT Press
