### ISSUE TITLE
Editing a Pub's Connections

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1501]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
It would be great to be able to update or edit Connections to Pubs once they are made.

### What would this enhancement help you accomplish?
It would help me not have to re-make connections - -which consists of remove existing ones and basically start all over -- and just make small changes. 

---

### What's the URL to your PubPub community?
https://commonplace.knowledgefutures.org/dash/pub/syftfd3l/connections
(for now, I'll probably have changed the connections by then)

**Comment by gabestein** [comment]
Research what happens when you re-deposit a thing with different connection/relationships.

Connection direction, type, and URL can only be edited prior to crossref deposit. Everything else can always be edited.
