### ISSUE TITLE
Images vanish

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#1505]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Author noted two of the illustrations in a media-heavy pub had disappeared
2. Files are still present when editing the draft (can be downloaded), but these do not display in the published version. The captions are still there.
...

### What did you expect to happen?
Images to continue to display in the published pub

### What URL can we use to see the issue?
https://phone-and-spear.pubpub.org/pub/mn9foui0

Images in q are captioned: Everything is here, 2017 (I found that this one returned after selecting "always allow full resolution")
Djungaya and guku, 2017

### What browser/operating system were you using?
Google Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
n/a

### Who reported this? (If not you)
Jennifer Deger, Catherine A.(who may have more to add?), & self

**Comment by gabestein** [comment]
Huh, we're getting 413, payload too large, which means the resizer is upsizing it? Very odd. May need a quick look from @isTravis...

**Comment by coahearn** [comment]
yah, I saw the same thing: https://recordit.co/I980YpvoKu

**Comment by isTravis** [comment]
Do either of you have an original image file I could test with? My hunch is that it's not being up-sized, but that the resized version is being served from (or by) something that has a different size limit than raw s3 (e.g. AWS Lambda or Cloudfront where the resized images are served from may have a different limit than simple storage).

**Comment by isTravis** [comment]
Yup - it's an AWS Lambda limitation. Lambda has a 6MB limit on files it can process, and in preparing the images for processing (i.e. converting it to base64) - the size is increased. This [issue on the resizing repo](https://github.com/awslabs/serverless-image-handler/issues/282) is exactly what we're bumping into. 

Until Lambda increases their max size (I wouldn't hold my breathe), our two options on the content production side are:
1. Use the 'Always use full resolution' option, or
2. Re-upload the image at a reduced size (seems like our effective limit is 4.45MB)

On the dev side, we could add some intelligence to:
1. Auto-use full-resolution if we get a 413 from `v3-resize.pubpub.org`,
2. Auto-use full resolution if we see the file is larger than 4.45MB,
3. Limit uploads to a certain size.

**Comment by coahearn** [comment]
that is _super_ helpful to know. I remember the images for this book being crazy high quality, too.

**Comment by avanouse** [comment]
Thank you, Travis and Gabe and Catherine! Looks like I just need to work on hitting the sweet spot for resolution on these large images. 

Gratefully, 
Allison
