### ISSUE TITLE
Chinese characters (and other CJK?) not appearing in PDF exports

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#1509]
Via @Dawit-Tegbaru. Probably down to the font we're using — we may want to list additional fallbacks. Or it could be an issue requiring a Paged.js upgrade (see #1356)

**Comment by gabestein** [comment]
As discussed this AM, we believe the route is simply to add Han to our Adobe bundle (@djagdish). We may potentially need to include it in our `printStyles.css` body font-family as well, but we're not sure if that's even needed.

**Comment by idreyn** [comment]
Okay so here's my latest on this. I checked in on this line in `printDocument.scss`:

```scss
@import url('https://use.typekit.net/kmi0tdo.css');
```

This URL tuns out to be specific to our `pubpub-v6-prod` "Web Project" on Adobe Fonts which is visible [here](https://fonts.adobe.com/my_fonts?manage_fonts_filter=all&max_styles=26&min_styles=1#web_projects-section). In theory this means we should be able to add more fonts to this project and they'll automatically get added to this bundle, without making any changes to our source code.

However, the Adobe CJK webfonts come with a complication. Because their character sets are so big, Adobe uses something called [dynamic subsetting](https://helpx.adobe.com/fonts/using/dynamic-subsetting.html) to load only the glyphs required to display the actual content of a page. This requires embedding a snippet of JavaScript to read page content and request more glyphs from Adobe as appropriate.

It seems like we cannot retrofit the `pubpub-v6-prod` project to use dynamic subsetting. We would have to create another project and add [Source Han Serif](https://fonts.adobe.com/fonts/source-han-serif-simplified-chinese) in the right flavors, along with our other fonts. 

## Option 1: New web project with dynamic subsetting

This may or may not work. There are two questions to answer:

1. Does our export pipeline support dynamic subsetting? To find out, we can add the JavaScript snippet from the `cjk-testing` Web Project I created to this file: https://github.com/pubpub/pubpub/blob/454965c90718180dcbb976e1a423a4f396f822b0/workers/tasks/export/html.tsx#L299 using the same `dangerouslySetInnerHtml` technique. This script _should_ get run by the headless Chrome instance that Paged.js uses to produce our PDF exports, but it's an open question whether it will load the fonts to completion before rendering the PDF. Some of the [font display](https://helpx.adobe.com/fonts/using/font-display-settings.html) options may help us here.
2. Assuming this works, do we want to use this new bundle with CJK fonts on `pubpub.org` as well, or only in exports? I'm a little inclined toward the latter. The overwhelming majority of consumer devices have good CJK fonts on them — we are in this position only because the export pipeline runs on a barebones web server. Dictating our own may not add that much value while also tying us further into Adobe's font ecosystem.

## Option 2: Manual font bundling

If the answer to (1) turns out to be "no" then our next option is host fonts directly on Heroku which, according to [this blog post from 2015](https://www.mschweighauser.com/custom-fonts-in-heroku-apps/) is very simple. In that case we have a couple of questions to answer:

1. Can we legally include an Adobe font like Source Han Serif in our repo, assuming we have a license? If not, I'm pretty sure we can find a good open-source CJK font — I'm not particularly wedded to this one.
2. Can we fit a bunch of CJK fonts in our Heroku slug size budget? (Currently at  465.8 MiB of 500 MiB)

----

One final note relevant to either option: we also need to determine whether sans-serif equivalents for these fonts are necessary to render our headers.
