### ISSUE TITLE
Image upload 

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1510]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. HDSR wrote in about a board member's image missing in their bio pub
2. When uploaded, image is not visible, though the media option come up as though it's there
3. Image does appear when you click on "always show full resolution"
...

### What did you expect to happen?
Image appears regardless

### What browser/operating system were you using?

===

### Have any screenshots? (Attach them by dragging the image here)
See video: https://recordit.co/IM17CLtb1n

### Who reported this? (If not you)
Paige (HDSR), Catherine

**Comment by gabestein** [comment]
Appears to be fixed.
