### ISSUE TITLE
"Cite as" URL has undefined.pubpub.org in URL from Dashboard

### ISSUE THREAD

**Issue by cfcohen** [pubpub/pubpub#1512]
### What went wrong, step-by-step?
1. Goto the dashboard page for a publication.
2. Note the the "Cite As" field contains undefined.pubpub.org, while the public publication page has the correct hostname.
...

### What did you expect to happen?

I expected the URL to match the public page.

### What URL can we use to see the issue?

https://medieval.pubpub.org/dash/pub/6cent-chap20/overview

### What browser/operating system were you using?

Firefox 90.0 (64-bit) on Ubuntu Linux.

===

### Have any screenshots? (Attach them by dragging the image here)

No.

### Who reported this? (If not you)

Me.

**Comment by gabestein** [comment]
I think we fixed this in #1502! Feel free to re-open if you see it again.
