### ISSUE TITLE
Markdown footnotes

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#154]
Standard markdown footnotes like "[^1]" are not being rendered at all. Footnote rendering only seems to happen with respect to references that have been previously inserted via the new editor. In academic texts, not all footnotes are references, though: It is important to be able to insert text in footnotes as well. 

In standard markdown and in scholarly markdown, it should be possible to render standard footnotes (including text and references).

**Comment by gsarma** [comment]
This still seems to be a problem- would be great to have this functionality back, particularly for academic articles.

**Comment by ThariqS** [comment]
Got it! We deprioritized footnotes in order to get a basic functionality of the WSIWYG editor fully out there, but will start adding these back.

**Comment by trenkert** [comment]
This is really essential. Without the possibility to have footnotes with custom text, most researchers from the humanities won't be able to use pubpub for their work.

**Comment by ThariqS** [comment]
Okay, thank you. It's good to have feedback like that. One problem we've run into is where to render the footnotes. Usually footnotes are rendered at the end of a page I believe, but we don't have pages in PubPub. Would you rather have them rendered at the end of a document, on the side, or have the text be revealed by clicking/hovering on it.

**Comment by trenkert** [comment]
Any solution is fine, I guess. I would suggest a short preview (2 lines) for hovering, and a popup of the full note on the side when clicking (to avoid unnecessary scrolling down and up again). For pdf exports, I'd suggest endnotes at the end of the document.

**Comment by gsarma** [comment]
I like the idea of endnotes in the actual PubPub display, but I think @trenkert's suggestion is a good compromise.  Endnotes are needed for PDF exports.  

An alternative would be to have endnotes and to be able to click on the endnote number to return to the original position in the manuscript.

**Comment by trenkert** [comment]
@gsarma 's solution with endnotes that link back would work, too.

**Comment by ThariqS** [comment]
This is implemented now! Would love to get your feedback: http://g.recordit.co/Yd0zTvll6A.gif
