### ISSUE TITLE
citation styles

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#155]
is it possible to set a, or to choose between different citation styles as a global option for a specific pub or a whole journal? 

For us, being able to choose between AMA, APA, and Chicago (for instance) would be a necessity.

**Comment by ThariqS** [comment]
All the architecture is here for this (we're using CSL: https://github.com/citation-style-language/styles) just need to add in the different styles and give an option to switch.

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

Potentially thank to you, @trenkert, as you know, we now support APA, Harvard, Vancouver, and Bibtex for easy switching.
