### ISSUE TITLE
Reviews leave authors in limbo - clarify what is happening for requesters and reviewers

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1553]
(A bug report related to FR #1094)

### What went wrong, step-by-step?
1. I invited the head of a potential new community to contribute a pub to an existing community.
2. He joined the community, drafted a pub, and submitted it for review.  I did not see this or get notification of the submission for review.
3. The next week when we met he mentioned he'd submitted it for review.  I did not yet realize that he could not publish it himself when he did not want review.
4.  I checked the activity feed, and reviewed and published it.  He did not get a notification, though he was using the site at the time. I had to inform him it had been published.
5. A week later he made updates after collaborating with other community members, and submitted those for review.  I did not get any notification of this.
6. He mentioned he had submitted another request for review, and asked how reviews were processed (not being entirely clear after reading pub docs)
7. I added him as a community member.
8. I looked at the request queue and saw two sequential review requests.  I tried unsuccessfully to approve request 3 (the most recent).  
9. I successfully approved request 2.  Then I immediately tried to approve request 3; the page hung.  After a hard refresh, it showed it had been approved. 
10. The community member was still not able to directly update his own post.  I went back to the members list and changed his permissions to _manage_, the lowest level that lets him do so, even though I didn't yet mean for him to be able to manage community or collection settings [because we were only discussing single-article-review workflow].

### What did you expect to happen?

I expected 
- the author, after submitting a request for review, to find a status page w/ details of how review works, who can review, how to track its progress (and other options for updating a pub)
- the author, and myself, to have a simpler feed of review requests/updates. 
- some sort of notification to appear indicating there was a review pending; while I was logged in, or at least highlighted on the activity feed; 
- some sort of notification for him to appear once there was an update in review status. 

### What URL can we use to see the issue?
https://knowledgestructure.pubpub.org/dash/activity

**Comment by idreyn** [comment]
Hi SJ — I am recategorizing this as a "feature request". It looks like there are four potentially separable issues here:

- The platform doesn't have built-in notifications. We are working on notifications for certain activity on PubPub and we will probably release a first version of this later in the year. We are soliciting feedback on what kinds of activity people would like to get notifications about, so we'll keep this in mind (and I encourage you to come to Dev Office Hours on a Tuesday to say more about your use case if you like).
- The privileges associated with different permissions levels and the workflow for Reviews are unclear.
- There is potentially a bug where a user with Edit permissions is unable to edit their own Pub draft; I cannot reproduce this, but if you are able to I encourage you to file a ticket specifically with this issue.
- There is potentially a bug with hanging requests on Reviews. I cannot reproduce this either, but the same applies.

This is valued feedback on PubPub, but it's wide-ranging enough that we cannot address it in the scope of a "bug" issue. In the future, please use the "Enhancement" issue template for issues requesting new features — or if the feature is too broad to be completely specified in the body of the issue, I encourage you to make a post in the [discussion forum](https://github.com/pubpub/pubpub/discussions). When reporting bugs, please provide information such as a screenshot, your browser and OS, and a minimal reproduction, keeping each in a separate issue.

I don't mean to strike the tone of "harried maintainer" here — I'm glad you're sharing your thoughts, and I mostly don't want to let them get lost. But these detailed and highly contextual GitHub Issues have a way of sliding down our priority queue in the face of more actionable items, which is a loss for everyone.

**Comment by jeffpooley** [comment]
So great to hear about the notification plans @idreyn !

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/10
