### ISSUE TITLE
Custom CSS does not apply to Pubs

### ISSUE THREAD

**Issue by ThomasFKJorna** [pubpub/pubpub#1560]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Use new shiny CSS feature to make all text a nice ugly shade of red, by adding to custom CSS
``` css
body { 
   color: red;
}
```
2. Open random Page, see glorious red text
3. Open random Pub, see boring black text

Actually what I tried to do was to shorten the DOI (client for some reason picked really long DOIs, causing the collection button not to display), but this does the same.

When loading a page, an inline stylesheet is loaded (usually called # 2), but when loading a pub this doesn't happen.

### What did you expect to happen?
I expected the CSS to also be loaded in Pubs. This is probably intended behavior, but since it's intended behavior I don't like I made it a bug-report :smile: . 

On a more serious note, I didn't see anything in the descriptions of the new feature which indicated that it was limited to pages only. Furthermore, I find it a bit strange to only limit this to pages: someone using custom CSS would probably make quite some changes to the default style, which would make the default Pub style look somewhat out of place. 
If it is in place as a "safety" feature I also find that somewhat strange, as the Custom CSS already has a ton of warnings saying "This could break your community" etc. Please let me break my community.

### What URL can we use to see the issue?
For the lengthy ass DOI, see https://openpresstiu.pubpub.org/pub/powerpolitical/release/5

### What browser/operating system were you using?
Firefox (latest), Arch Linux, but I don't think that really matters

===

### Have any screenshots? (Attach them by dragging the image here)
:D 
![image](https://user-images.githubusercontent.com/21983833/133117697-159f89ad-46ce-4fb3-9f01-eca6f84ec65d.png)

:( 
![image](https://user-images.githubusercontent.com/21983833/133117468-365f2eaa-d578-4827-aabd-1ffb595f6a8b.png)

**Comment by gabestein** [comment]
Hi Thomas — thanks for pointing this out. I am inclined to agree, and we'll add styling to Pubs as well in the coming days.
