### ISSUE TITLE
Cert upgrade causing open graph scrapers to fail

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1564]
It looks like our recent certificate upgrade is causing some issues with open graph scrapers, specifically Twitter and Facebook. See: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Freviewsindh.pubpub.org%2Fpub%2Fed-note-september-2021%2Frelease%2F3

It looks like the issue is related to our cert chain not being correct for subdomains/wildcards. See: https://victorlava.com/how-to-fix-curl-60-ssl_cacert-cant-validate-ssl-certificate/

And:

https://whatsmychaincert.com/?reviewsindh.pubpub.org

I'm not sure what the fix is, or where it lives (cloudflare vs. heroku, etc.), but clearly something with the way we route to subdomains.

**Comment by isTravis** [comment]
Cert bundles/chains have tripped me up so many times. I haven't been able to find a clear explanation of who expects which bundles/chains and why. It surprises me that the cert worked at all, yet was described as misconfigured and failed the FB crawler. 

Anywho - I think I've updated it to be the proper chain. This link validates now: https://whatsmychaincert.com/?reviewsindh.pubpub.org

I don't have an active FB account to user the debugger with. Would you mind testing the FB debug tool again and Closing if we're all set? If you won't be able to get to that today, let me know and I can spin up a quick test-dev account.

**Comment by gabestein** [comment]
Thanks, it worked! I'm pretty convinced certs are basically not knowable, so, no worries.
