### ISSUE TITLE
Support for COiNS metadata

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#157]
Support for COiNS metadata

**Comment by gabestein** [comment]
Hello! I'm going through our much-neglected GH issues to clean them up a bit. I can't find much info on COiNS outside of a wiki reference and a few pages referencing it. In particular, http://ocoins.info/ seems to have been taken down. Is COiNS still widely supported/used by your communities?

**Comment by gabestein** [comment]
A year later ... the COiNS spec site appears to be dead (https://ocoins.info), good info about it is hard to come by, and we now support better metadata for Zotero and Mendeley (#580) via html metadata tags, which seems to be prevailing. So, I'm going to close this issue. Feel free to re-open if COiNS reappears or becomes important to you again in the future.
