### ISSUE TITLE
vimeo embeds don't include fullscreen option

### ISSUE THREAD

**Issue by publicityreform** [pubpub/pubpub#1588]
### What did you expect to happen?

the embedded player should include a fullscreen control

### What URL can we use to see the issue?

https://learning.pubpub.org/pub/circlemovements

### What browser/operating system were you using?

mac os 11.6
chrome 94
safari 15
firefox 92

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="718" alt="Screen Shot 2021-10-04 at 10 43 10 PM" src="https://user-images.githubusercontent.com/25676260/135966978-cdd045f7-a584-4ae1-aa87-9f8e68e98037.png">
(fullscreen controls should appear to the right of the playbar)

**Comment by gabestein** [comment]
Cannot repro. Was likely a video setting.
