### ISSUE TITLE
Add secondary metadata elements to Pandoc templates

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#1592]
Move [fields](https://github.com/pubpub/pubpub/blob/5bee172991aac472584140093a8ea50f239dbebc/workers/tasks/export/html.tsx#L174) previously rendered directly into Pandoc document body:

- `updatedDateString`
- `publishedDateString`
- `communityTitle`
- `primaryCollectionTitle`
- ~`doi`~
- ~`licenseSlug`~
- `publisher`

...into front matter and templates.

**Comment by gabestein** [comment]
Done in #1688
