### ISSUE TITLE
Add sort functionality to tables

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1601]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
Add sort functionality to tables

### What would this enhancement help you accomplish?
Ability to sort by ... Sorting is one of the most common use cases for organizing/viewing data in a table.  

---

### Any attachments or reference images? (Drag them here)
N/A

### What's the URL to your PubPub community?
N/A

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/9
