### ISSUE TITLE
Community Impact timing is off

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1629]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
When I'm looking at a community's analytics for 1 year, it's very different than looking at the community's analytics for 12 months. This is when this year and this month is included in the filter, respectively. 

...

### What did you expect to happen?
I expected 12 months = 1 year

### What URL can we use to see the issue?
https://commonplace.knowledgefutures.org/dash/impact

### What browser/operating system were you using?
MacOS/Google Chrome

===

**Comment by gabestein** [comment]
Taking a look, I'm fairly sure it's working as intended, it's just humanity's relationship to time and language that's wonky. Or, more specifically, the Metabase dashboard's, which I don't have much control over.

- Previous year = the last calendar year. We seem to only have data going back to April 29, 2020, which is when we switched over from our last analytics provider. We should have data prior to that, so it's a bit concerning that we don't, and I'll look into it — but it's unrelated to the dates.
- Previous 12 months = the last 12 months. So, September 2020 - September 2021.
