### ISSUE TITLE
Aligning Edit and View views: Edit, View, Comments, Versions

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#163]
Related to our discussion today:

An active group of editors will want to do all of the following:
- See how a pub looks to readers
- Edit the pub together
- Save snapshots while editing
- Go back to a previous snapshot 

While reading, if you have edit permissions, you want to see the 'Edit' option.  
Everyone wants to see the 'Versions' or 'version history' option, even if it's small.
While looking at a past revision, you want to be able to edit that revision (maybe note that in the edit summary: edited from rev. N)

While editing, you want to see comments (and to be able to add comments directly, w/o going back to read mode)

**Comment by isTravis** [comment]
Closing as architecture and layout has been changed. Edit functionality (tied in with forking) coming to address the majority of points above.
