### ISSUE TITLE
Twitter profile link should check content before prefixing it with http://twitter.com

### ISSUE THREAD

**Issue by octref** [pubpub/pubpub#1638]
### What went wrong, step-by-step?

1. Open https://cursor.pubpub.org/user/thomas-renkert/authored
2. Click the twitter link
3. It opens https://twitter.com/https://twitter.com/Thomas_Renkert
...

### What did you expect to happen?

It opens https://twitter.com/Thomas_Renkert

### What URL can we use to see the issue?

https://cursor.pubpub.org/user/thomas-renkert/authored

### What browser/operating system were you using?

macOS / Chrome

===

### Have any screenshots? (Attach them by dragging the image here)

![image](https://user-images.githubusercontent.com/4033249/138526734-6367f955-e7f6-457c-994d-ae1661907143.png)

**Comment by idreyn** [comment]
I think we want to encourage people to just insert their Twitter username here — there's some feedback text next to the input for this that shows the username appearing within the URL (though your PubPub account may well predate that!)

If you want to strip the URL out of your username on your profile you can do so from [here](https://cursor.pubpub.org/user/thomas-renkert/edit).
