### ISSUE TITLE
Make white or black blocks a default for pub theme settings

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#1649]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
Currently, "dark" text is in the default theme for pubs. I think this should be changed to white blocks.

### What would this enhancement help you accomplish?
Text without blocks can become really illegible if you add a background image without realizing how dark or how pale it is against the type. You can do this by mistake, because the default is blockless—and this even makes it hard to navigate back to pub settings, in the event you're just trying to use that link in the pub header. 

I can imagine myself getting very, very frustrated by this.
---

### Any attachments or reference images? (Drag them here)
<img width="1210" alt="Screen Shot 2021-11-02 at 5 31 46 PM" src="https://user-images.githubusercontent.com/60357197/139954722-d9487db9-c47d-4f02-ac8e-1709efe002fb.png">

### What's the URL to your PubPub community?
This would be true anywhere

**Comment by idreyn** [comment]
I agree that this is frustrating and personally I think the default style is a little drab. I'm not sure about white/black blocks, either, though. They're kind of too far on the other end of the spectrum — maybe a little too punchy?

My vote would be to default to light text with Community accent background. It looks great when an image is added. This style was central to our 2020 redesign of the header, and we backed away from it at the last minute because we worried it was too opinionated. Maybe worth rethinking @gabestein?

**Comment by avanouse** [comment]
Revisiting this today, I'm beginning to think it's OK that this happens. It
should encourage users to be careful and reflective about their design
decisions!

**Comment by gabestein** [comment]
I'm inclined to agree with your sane default, @idreyn. But I also think we're planning to make defaults more customizable, generally, as a next iteration on submissions, so I think it could probably wait for that.

**Comment by idreyn** [comment]
Thanks for the responses. Sounds like we're okay without any changes for now, so I'll go ahead and close this.
