### ISSUE TITLE
Search page results shows incorrect timestamps

### ISSUE THREAD

**Issue by djagdish** [pubpub/pubpub#1656]
### What went wrong, step-by-step?
1. Entered keywords to find pubs using the _Search_ page in a community.
2. Some of the pubs shown in the results of the Search show incorrect timestamps. More precisely, some of them show the _current date_, instead of the actual _draft-last-edited-on_ date.
3. The erroneous timestamps were seen usually with Draft pubs only. Not sure if it extends to Released pubs also at this point.

### What did you expect to happen?
1. Timestamps shown for the results should be accurate, as they are usually used as a quick mental filter by users to focus on the relevant results.

### What URL can we use to see the issue?
append `/search` to the root url of the community, and enter some keywords to search for pubs.

### What browser/operating system were you using?
Mac OS Big Sur 11.3.1, Chrome 

===

### Have any screenshots? (Attach them by dragging the image here)

Screenshot here shows today's date (Nov 9, 2021) as timestamp of some pubs, even though those pubs were last edited months/years ago.

![image](https://user-images.githubusercontent.com/316939/140974471-dc551e6f-83f1-4903-b32b-ee4fafb732e1.png)

**Comment by idreyn** [comment]
Oddly we no longer have the data we need in Algolia so I'm just removing this entirely for now and deferring a real fix to #1670.
