### ISSUE TITLE
EPUB import error

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1657]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Importing epub files resulted in a transform error
2. Uploaded an EPUB file that imported several weeks ago without issue. Nevertheless, the same error message appeared. 

===

### Have any screenshots? (Attach them by dragging the image here)
![image](https://user-images.githubusercontent.com/72410195/140992431-c369b6bb-473b-4d3f-9516-ad577c846e91.png)

**Comment by idreyn** [comment]
Resolved by ea48cef
