### ISSUE TITLE
Importer munging multiple author names together

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#1659]
Probably a Pandoc upgrade thing

**Comment by idreyn** [comment]
On closer inspection this looks like a one-off problem with a single document so I'm going to close this.

**Comment by gabestein** [comment]
Sorry, I should have reported this a million years ago. If it's what I think, I've seen it happen a bit with JATS articles before, too, (and before upgrades), but oddly only with APA-formatted ones. I think I tracked it down to an issue with pandoc that I'll need to report.
