### ISSUE TITLE
Enable member-based Crossref DOI deposition

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1674]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?

- Make Crossref connection from community https://jbt.pubpub.org/ (credentials available)
- Apply existing DOI prefix (10.7171) to newly generated DOIs. 
- Add an option to generate suffix. 

### What would this enhancement help you accomplish?

Mint and deposit DOIs on behalf of the journal using existing crossref membership. 
---

### Any attachments or reference images? (Drag them here)
HDSR example 
![image](https://user-images.githubusercontent.com/72410195/142476147-085db3df-9122-4de1-8a68-1b2b22efa527.png)

### What's the URL to your PubPub community?
https://jbt.pubpub.org/

**Comment by gabestein** [comment]
Resolved by #1680
