### ISSUE TITLE
Missing metadata in JATS XML export

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#1688]
Include the following journal  metadata in JATS exports:
ISSN or other unique Journal ID
Publisher name
Volume
Issue number (if applicable)
Unique identifier or elocation ID (could be the pub slug) 
Publication dates (Issue-based or Article-based) 

### What browser/operating system were you using?

===

### Have any screenshots? (Attach them by dragging the image here)
Current Output: 
![image](https://user-images.githubusercontent.com/72410195/144500092-04edf708-ec2a-42e4-9f38-657db6f95e25.png)

Correct examples 
journal-meta 
![image](https://user-images.githubusercontent.com/72410195/144501021-ecf84d62-f9bd-4ef4-bf63-72a1bb8e2375.png)

article-meta
![image](https://user-images.githubusercontent.com/72410195/144501446-f5ca8e3a-7d40-4357-80c1-a45faadd9fe3.png)

pub-date within article or issue-meta
![image](https://user-images.githubusercontent.com/72410195/144502231-9742f8c1-85e1-423c-8a12-1a4e835e8ef1.png)

**Comment by gabestein** [comment]
I think most of this (save maybe the unique id), is because the collection and pub aren't public yet, so technically the pub doesn't have a pub date or a primary collection yet. When the pub is published, it should have all of this info.

Can you provide an example of the unique id? I haven't seen it as a requirement before; we'd probably use the slug, as you suggest.

**Comment by Dawit-Tegbaru** [comment]
> I think most of this (save maybe the unique id), is because the collection and pub aren't public yet, so technically the pub doesn't have a pub date or a primary collection yet. When the pub is published, it should have all of this info.
> 
> Can you provide an example of the unique id? I haven't seen it as a requirement before; we'd probably use the slug, as you suggest.

I checked a published TMB article prior to submitting the ticket thinking the same but to no avail.

Several publishers use page range in lieu of elocation-id (unique id). Both are acceptable. Here's an example via https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/elocation-id.html
![image](https://user-images.githubusercontent.com/72410195/144515026-0d9fea5c-942c-48f9-9fc0-4b142ecc3a67.png)

**Comment by gabestein** [comment]
Odd...I'll take a look.

**Comment by gabestein** [comment]
Anyhow, let me know your thoughts when you get a chance on the elocation stuff.

Otherwise, I have a PR ready for the other stuff that we can slot in next week.

**Comment by Dawit-Tegbaru** [comment]
I appreciate you looking into this 🙏🏽.  PubMedCentral accepts NLM or JATS XML. I believe in either case the page range or elocation tag is required. THere's more info here including downloadable sample files: https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/style.html. Their style checker (also in that page) highlights the missing metadata.

**Comment by Dawit-Tegbaru** [comment]
I could be mistaken but my understanding was that the <elocation-id> is a unique id generated by the publisher (or publishing agent). Conventions used are up to the publisher. I think the slug or doi suffix would be sufficient (although not every pub will generate a DOI) which is why I suggested the slug. 

Via JATS 1.2: 

> <elocation-id>Electronic Location Identifier
> Bibliographic identifier for a document that does not have traditional printed page numbers.
> **Remarks**
> This element acts in the same way as a page identifier for a document that does not have traditional page numbers; the value could be an article identifier, publisher’s number, etc., for example, “E70”.
> **External Assigned Identifier:** This element holds an externally assigned identifier, assigned to an article by a publisher, an archive, or library to help cite an article that is born digital and will never have page numbers. The contents of this element should not be confused with the id attribute, which holds an internal document identifier that can be used by software to preform a simple link.
