### ISSUE TITLE
Refreshing the page can cause lost work

### ISSUE THREAD

**Issue by DocSunset** [pubpub/pubpub#1753]
### What went wrong, step-by-step?
1. The editor had an issue connecting; a small yellow "Connecting..." message was displayed where there is usually green "Connected"
2. I assumed this was an innocuous bug, and no problem. I worked in an open tab for several days
3. While editing I pressed Ctrl+R with the intention of "redo"-ing a change I had "undo"-ed with Ctrl-Z, causing the page to refresh.
4. My work was lost
...

### What did you expect to happen?

Ideally in a situation like this, the contents of the edit buffer should have been cached locally and taken precedence over the copy stored on the server so that my work would not be lost.

### What browser/operating system were you using?

===

**Comment by DocSunset** [comment]
Apologies if this is not the right place for this issue.

**Comment by gabestein** [comment]
Thanks for filing this, and I'm sorry you had this experience. To avoid this scenario, PubPub should be displaying a warning about lost work if you navigate away from the page without local worked having saved. I assume you did not receive this warning?

If so, could you also let us know the OS and browser you were working on, so we can try to track down why the warning didn't appear?

**Comment by DocSunset** [comment]
Chromium Version 97.0.4692.71 (Official Build) Arch Linux (64-bit).

I did not see any warning, although I have also seen the warning several times since then, so I'm guessing this is going to be hard to track down. In case you never find it, another alternative might be to provide a more alarming indicator when connecting to the server, similar to how you get a bright red label when offline?

Please let me know if I can provide any more information to help.

**Comment by gabestein** [comment]
Thanks! We've been able to track down the issue. We're currently showing the warning message only when the documented has become disconnected after first making a connection to our server. However, if a document never makes the first connection, which happens on rare occasions, it is possible to make changes and leave the page without realizing it. This is obviously bad UX and entirely on us. To rectify it in the  we'll be preventing users from making changes until the initial connection has been established.

**Comment by DocSunset** [comment]
Awesome! That sounds like a very reasonable solution, and I'm glad you found the root of the issue. 👏

**Comment by MaPeras** [comment]
Sorry, but this bug just came up again five minutes ago [here](https://openrewi.pubpub.org/pub/d38znhen/draft?access=81dm9ud3). Had closed my computer and resumed to the tab. Before, everything went just fine. "Connecting" persisted, without a warning. Had to re-open the browser in order to "connect" and all changes were gone.

This also happened to other team members at openrewi.pubpub.org

Firefox 126.0.1 
on Ubuntu 22.04.4 LTS

**Comment by sheishistoric** [comment]
Thanks for finding this thread, @MaPeras. To clarify, you didn't receive a warning when resuming to the tab & all the changes you made _after_ resuming to the tab were gone?

**Comment by MaPeras** [comment]
Yes, there was no warning. The banner just kept saying "connecting". Refresh didnt work. Had to re-start the browser in order to connect again.
