### ISSUE TITLE
Submission banner block design

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1756]
<img width="1205" alt="Screen Shot 2022-01-18 at 11 43 18" src="https://user-images.githubusercontent.com/639110/149980438-e8c7bcee-17da-46b6-9e1c-72db8f697948.png">

https://qubqub-pr-1755.herokuapp.com/a-long-collection-name-that-everyone-regrets-choosing

**Comment by djagdish** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/316939/152817636-399d57d2-e216-4f87-919b-6db51f5e636d.png">

https://www.figma.com/file/ERHvqJqCVBZ7dH2ZQBGlp8/?node-id=673%3A1324
