### ISSUE TITLE
Word Count

### ISSUE THREAD

**Issue by samuelebaker** [pubpub/pubpub#1769]
Hey, small thing: I can't find in the documentation whether or not a draft pub can display a word count, and if it can, how to see it. I like pubpub as a writing environment as well as a platform, but this is a feature found in Ulysses etc that is sort of needed. Sorry if I am being obtuse and just missing how to see this! Thanks in advance for any help anyone can give.

**Comment by gabestein** [comment]
Thanks for the suggestion. We don't currently have word counts, so you're not missing anything. Unfortunately, it's not super trivial because of the way documents are built behind the scenes, but we just discussed it and it's something we're interested in looking into in the next few weeks.

**Comment by gabestein** [comment]
@samuelebaker: this is now live. Thanks again for the suggestion.

![Screen Shot 2022-03-31 at 1 04 27 PM](https://user-images.githubusercontent.com/639110/161123538-7119de45-b628-4361-92a7-b6b28748a69e.png)

**Comment by samuelebaker** [comment]
Thank you all, I love the implementation.

BTW I’ve just had a paper accepted at the 2023 MLA convention in San Francisco, for a panel entitled "What do we want in a research platform of the future?” — my paper will be called "Some Steps Toward Collectivist Platforms for Humanities Research Collaboration” and I will definitely be touting pubpub! I may be in touch about this again if I have any questions about the history and intent of the platform not addressed in your (excellent) documentation. 

Sam

**Comment by gabestein** [comment]
Thanks Sam. That's super cool! We look forward to reading the paper. And we're happy to chat anytime about the history, philosophy, etc.
