### ISSUE TITLE
Credit collection-level editor/creators in the auto-generated pub-level citations

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#1807]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
Let the automatic citation for a pub include collection-level metadata for editorship and/or authorship so that (e.g.) the editor of a collection of essays is always cited in the generated citation for the chapter *as well as* the author of the  pub (which is currently visible in this citation only when you've checked the box for it to appear on the byline).

### What would this enhancement help you accomplish?
(1) more consistently proper attribution for cases where the collection-level creator is also the primary author of the pub (authors get cited for citations chapter-by-chapter: can this  be true on clicking "cite" as well as when viewing the heading of the pub?); (2) editors can be properly credited (as editors) for the contributions they've solicited, selected, and helped through gestation

---

### What's the URL to your PubPub community?
[examples abound! Let's please talk about this!](https://autogeddon.pubpub.org/pub/jzu2d7ru)
compare to ch 2.1 in the same community.

### Who requested this? (If not you)
Me, but related to observations by Kelsey Dufresne

**Comment by gabestein** [comment]
Intended behavior: when byline is checked at collection level, treat those contributors as authors on each pub within collection.

**Comment by gabestein** [comment]
Notes from today's call:

- Map from CREDIT Taxonomy to CSL values, pass those into citation.js to generate pub-level citations/deposits. Gabe/Allison to work on mapping.
- Is it mapping or just mapping + logic? Gabe to research.
