### ISSUE TITLE
Break the `SubmissionTab` into the `DetailsTab` and `ContributorsTab`

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#1851]
Here we'll break the existing `SubmissionTab` into two new top-level tabs, the `DetailsTab` and `ContributorsTab`. Each should be wrapped in a `SpubHeaderTab`.

[_Figma mocks_](https://www.figma.com/file/ERHvqJqCVBZ7dH2ZQBGlp8/SPUB-vision?node-id=941%3A2039)

Note that what I'm calling the `DetailsTab` is the "Submission" tab in the mockups — I'm choosing a different name for clarity.

## The `DetailsTab`

This is very similar to the existing `TitleSubmissionAbstract` tab, with the following changes:
- Removing the `description` field
- Adding the `DownloadChooser` which is currently in the `SpubSettings` tab. We can revert any changes made to this component's styling in previous work, and treat it as normal Blueprint buttons.
- Removing the last piece of copy (`Enter your primary submission content...`)
- a few copy changes to prompt and placeholder text per the Figma mockups

Some misc tips:
- The mockups still show some (?) info indicators on various fields, which we can safely ignore.
- All of the custom field currently inside `spubHeader.scss` should be scoped to the `.scss` file for this component

## The `ContributorsTab`
This one is easy — we'll just take the existing `ContributorsTab` and wrap it in a `SpubHeaderTab`.

**Comment by howebenhowe** [comment]
Per the mocks, I have used the name `SubmissionTab` for what this card refers to as the `DetailsTab`
