### ISSUE TITLE
Math formulas

### ISSUE THREAD

**Issue by horstfortytwo** [pubpub/pubpub#1870]
I am using pubpub to write a book (course/lecture notes) on mathematical logic. I am loving pubpub, but: The text I write contains on average one or two math formulas per sentence and the WYSIWYG editor of pubpub drives me crazy in this respect.

To make this more precise, here is what I have to do to insert a formula (even a simple x):

I move my mouse/cursor to the formula button and click on it. A default formula is inserted into the text.
I click on the standard formula. A pop-up window opens, displaying the default formula.
I click on the pop-up window (to gain focus).
I erase the default formula.
I click on the update button.
This is so laborious that I now do the following as a work around. I type the entire text in [CodiMD](https://hackmd.okfn.de/), which is a mark down editor with math support and regularly remove the entire content from pubpub and import the md file from CodiMD.

Here is what would make my work easier and is probably easy to implement.

A keyboard short-cut that opens a pop-up window for directly editing math, for instance, CTRL-M for an inline formula und CTRL-SHIFT-M for a displayed formula.
The pop-up window is empty, so no default formula.
The focus is directly in the edit area of the pop-up area.
A keyboard short-cut for saving (updating) the formula.
The point here is that this can all be done using the keyboard. No mouse interaction necessary, only a few additional key strokes for entrering a math formula. In fact, this would be as fast and convenient as surrounding math formulas by $ or $$, as is usual in other contexts.
Maybe, this is the wrong place to discuss this issue. I would be very grateful for any advise where to post it instead.

**Comment by gabestein** [comment]
Thanks for the feedback! As I see you also wrote a discussion (#1869), I'm going to close this in favor of chatting there.
