### ISSUE TITLE
Reference manager doesn't adopt title

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#192]
The reference manager doesn't seem to adopt the reference title or any other identifying information when a new reference is created. This can make if difficult to find a particular reference (or other file) because you end up with a bunch of things called "New Reference".

![references](https://cloud.githubusercontent.com/assets/1399027/18716090/21fa4bea-7fe1-11e6-8dbb-14d1ea7f8a16.PNG)

**Comment by ThariqS** [comment]
Thanks Devin, definitely a bug, we'll get on it! In the mean time if you go to 'Edit' -> 'Details' -> 'Save Version' you can change the name. I realize that flow is super clunky, we're working on optimizing that!
