### ISSUE TITLE
Feature Request: Method for segregating comments by journal

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#194]
For journals seeking out reviews for submitted pubs and then working with those reviews, it would be helpful to have the ability to segregate the reviews (comments) by journal and view only those items on the article page.

Further, with this segregation, it would help for the journal editors to have moderation capability to help with abuse of the open commenting system.

**Comment by labarba** [comment]
Allow me to add to the feature request above—both @devinberg and myself are editors for The Journal of Open Engineering, built on PubPub. 

On TJOE, reviews are published using the sidebar on the article itself. See the "Instructions for Reviewers" on the journal [About](http://www.tjoe.org/about) page. Thus, if the article attracted several comments, the solicited review might be buried in the comment clutter. The situation would be worse for articles that attract numerous comments.

We would like to be able to somehow highlight the solicited reviews versus other comments. The feature request is for a solution that creates comment categories and allows prioritizing one over other categories—or maybe "pinning" of comments to achieve a similar result.

It would also be good to allow moderation of comments, but this is a separate feature request.

**Comment by isTravis** [comment]
Working on it as we speak! We're playing with moving the discussions to a more topic-based structure. You can see an early test of this live on the [MIT Future of Libraries Report](http://pubpub.org/pub/future-of-libraries). 

The thinking is that once we have conversations organized a bit more by topic, we can apply labels to those topics. These labels will be editable by the owner of the pub. Journals will also have a special label they can add to 'endorse' a conversation. Filters at the top let these conversations be easily sorted and sifted. See the rough wireframe below for a quick idea of what I'm talking about.

<img width="386" alt="screen shot 2016-11-12 at 10 05 42 am" src="https://cloud.githubusercontent.com/assets/1000455/20238766/8984cce2-a8c0-11e6-93f9-371e4f5b709b.png">

I'm open to the idea of certain topics being 'pinnable' and letting the author of the pub define the default filter state (perhaps you default to showing conversations the author has labeled as 'Journal Reviews').

These topics can also be closed, allowing some form of light moderation.

**Comment by devinberg** [comment]
Is there a timeline for implementation of this?

**Comment by isTravis** [comment]
We're making progress on this on the [v3 branch](https://github.com/pubpub/pubpub/commits/v3), but I think it won't be live until end of December or early January.

**Comment by isTravis** [comment]
Closing this issue as pubs in v4 are solely situated in a single journal.
