### ISSUE TITLE
Map contributor role in Pub citations and collection deposits

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1945]
Right now, all contributors at collection level, and all with "list on byline" checked at Pub level are included in the generated citation for the Pub as authors. Only pub-level contributors are included in HTML metadata and Crossref deposits.

Instead:

1. Only contributors at the collection level with "list on byline" checked should show up in citations, HTML metadata, and Crossref deposits at all levels.
2. We should use the first value entered in the Contributor "role" field (if there is one), at both the collection and Pub level, to specify specific roles in the generated citation, HTML metadata, and crossref deposits. This should happen in Pub-level citations, Pub-level HTML metadata, Pub-level crossref deposits, and Collection-level crossref deposits.

# Functional Specs

## Contributor Widget, Pub and Collection Level
- Add `Editor` to attribution role list. See mapping below.
- Add `Series Editor` to attribution role list. See mapping below.
- Add `Translator` to attribution role list. See mapping below.
- Add `Chair` to attribution role list. See mapping below.

## Collection Level
Use selected Contributor role with mapping below to set: 
- "contributor_role" for crossref deposits (see crossref notes below)

## Pub Level
Use selected Contributor role with mapping below to set: 
- HTML metadata (e.g. "citation_author")
- "contributor_role" for crossref deposits (see crossref notes below)
- Pub citation in cite button on Pub
- Pub citation in Pub overview dash
- Pub citations in "more citation options" modal

At some point, we should develop documentation and ultimately add some ui copy linking to that documentation.

# Mapping:

If not specified below, the role does not have a mapping and should be left to the default: author. This means that if someone chooses, for example, Conceptualization, and lists them on the byline, we will treat them as an author.

| PubPub Role List | CSL-JSON | HTML Meta | Crossref contributor_role |
| --- | --- | --- | --- |
| none selected (default) | author | citation_author | author |
| --- | --- | --- | --- |
| Illustrator | illustrator | n/a | n/a |
| --- | --- | --- | --- |
| Visualization | illustrator | n/a | n/a |
| --- | --- | --- | --- |
| Writing - Review & Editing | editor | citation_editor | editor |
| --- | --- | --- | --- |
| Editor | editor | citation_editor | editor |
| --- | --- | --- | --- |
| Series Editor | collection-editor | citation_editor | editor |
| --- | --- | --- | --- |
| Translator | translator | n/a | translator |
| --- | --- | --- | --- |
| Chair | chair | n/a | chair |

# Research/Notes

## CRediT
https://casrai.org/credit/

## CSL-JSON
Add a new list of name variable objects to the Cite object with the key specified (e.g. `editor: [{ first: 'Zaphod', last: 'Beeblebrox'}]`)

See: https://docs.citationstyles.org/en/stable/specification.html?highlight=illustrator#name-variables

## HTML Meta
Add a new element for each contributor (e.g. <meta name="citation_editor" content="Zaphod Beeblebrox">

Very scattered docs here, but e.g.: http://div.div1.com.au/div-thoughts/div-commentaries/66-div-commentary-metadata

## Crossref
Add the role to the `contributor_role` attribute of the `person_name` element

See: https://www.crossref.org/documentation/content-registration/descriptive-metadata/contributors/

**Comment by kaciccone** [comment]
As a PubPub user, I'm glad to see the pub citation problems getting attention. There are two separate problems that need to be addressed:

    All contributors at the collection level are included in the generated citation as "authors."
    All contributors at the pub level are included in the generated citation as "authors," even if they aren't listed on the byline (contrary to what's stated in the first sentence above).

The more pressing problem from my perspective is the second one—we only want people listed on the byline to be included in the citation as "authors." Thank you for your attention to this issue.

**Comment by gabestein** [comment]
Thanks for pointing this out. I think the second issue is its own bug that appears to have cropped up as we've tried to address this one. So, I created a separate card for it, which we should be able to address fairly quickly: https://github.com/pubpub/pubpub/issues/1957
