### ISSUE TITLE
non-byline contributor should not be listed in pub-level citation

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1957]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Create a pub
2. Add a contributor and uncheck "list on byline"
3. View citation: non-byline contributor appears in citation

### What did you expect to happen?
Non-byline contributor should not appear in citation.

### What URL can we use to see the issue?
https://demo.pubpub.org/dash/pub/cf3rjrm8/overview

===

### Who reported this? (If not you)
https://github.com/kaciccone

**Comment by kaciccone** [comment]
Thanks for your attention to this issue! We have been grappling with how to resolve this problem, including considering removing all contributors except folks on the byline (which we really don't want to do).

**Comment by gabestein** [comment]
closed by #1961
