### ISSUE TITLE
can't comment on released pubs (tooltip not showing on highlight)

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1964]
### What went wrong, step-by-step?
1. Visit any released pub
2. Try to highlight text and leave a discussion
3. Tooltip to leave discussion does not appear

### What did you expect to happen?
Tooltip to leave discussion should appear

### What URL can we use to see the issue?
Any released pub.

### What browser/operating system were you using?
Chrome Latest, Firefox Latest, Safari Latest / Mac OS Latest

===

**Comment by CommitsVortex** [comment]
I'm not sure if this warrants a new bug report, but the overall commenting functionality on released pubs appears to be down -- not only the tool tip feature. Attempting to leave a comment in the comments box at the bottom of a pub page results in an infinitely spinning loop.

**Comment by gabestein** [comment]
Thanks, any my apologies. We made some changes late last week that appear to have introduced an issue leaving comments. I've rolled back for now so commenting is possible again.

**Comment by CommitsVortex** [comment]
Thanks, though I am still getting a hanging loop when attempting to comment on any Pub.

**Comment by gabestein** [comment]
It may require a hard refresh to clear cache. If that doesn’t work, you can send me the url at help@pubpub.org and I can take a look.
