### ISSUE TITLE
Feature request: rss-feeds for comments

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#203]
It would be great if articles could feature rss feeds for:

- newest comments

- most popular comments

- most controversial comments

- comments with longest discussion

- most referenced comments

**Comment by isTravis** [comment]
Agreed. We have a new discussion format coming soon that providing more topic-based conversations. See the rough wireframe below. An activity feed for these discussions will be generated for users who 'follow' a given pub, so there is no reason we couldn't make an RSS feed out of those activities. We're  hoping to have these new discussions and activity feeds live by the end of the year.

<img width="386" alt="screen shot 2016-11-12 at 10 05 42 am" src="https://cloud.githubusercontent.com/assets/1000455/20238722/ce338974-a8bf-11e6-95e5-e3d0a4047571.png">
