### ISSUE TITLE
Footnote text spacing errors on Word import

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#2033]
### What went wrong, step-by-step?
1. I imported a Word document to a new [Pub](https://hms.mediastudies.press/pub/c12honoc/draft?access=2fre4mr1)
2. The footnotes, unless there are very short, display in the popover and in the footer with spacing errors: about every line, a space is eliminated, leading to combined words. E.g., “Eden Medina, Cybernetic Revolutionaries: Technology and Politicsin Allende’s Chile (Cambridge: MIT Press, 2014); EgleRindzeviciute, The Power of Systems: How Policy Sciences Opened Upthe Cold War World (Ithaca, NY: Cornell University Press, 2016);Benjamin Peters, How Not to Network a Nation: The Uneasy History ofthe Soviet Internet (Cambridge: MIT Press, 2016)”
3. The actual rich text field has no such spacing errors. Deleting and re-typing a single space anywhere in the rich text field will, moreover, fix the problem. This is quite tedious in articles with over 100 footnotes.4. 
4. I tested this with two articles. Here is the original Word document of the [Pub not yet corrected](https://hms.mediastudies.press/pub/c12honoc/draft?access=2fre4mr1). Note, though, that we are likely to correct the footnotes today, so the team may want to test with a fresh upload of this Word document or another. 5. 

[Wu_FINAL 051722.docx](https://github.com/pubpub/pubpub/files/8730171/Wu_FINAL.051722.docx)

### What did you expect to happen?

Footnote text spacing to honor spaces. 

### What URL can we use to see the issue?

https://hms.mediastudies.press/pub/c12honoc/draft?access=2fre4mr1 (for now, though we may use the fix above soon)

### What browser/operating system were you using?

Safari for iPadOS 15.5

**Comment by jeffpooley** [comment]
No problem at all! I’m thrilled about the Pandoc updates.

**Comment by idreyn** [comment]
This was triggered by a change in Pandoc's default behavior in word-wrapping HTML output, and should be fixed now!

**Comment by jeffpooley** [comment]
Thanks Ian!
