### ISSUE TITLE
Feature request: Have a timeline view for versions and comments

### ISSUE THREAD

**Issue by trenkert** [pubpub/pubpub#204]
It would be great if users could easily switch to a view of a timeline which only shows the changes and comments on a text over time. Something like this: http://www.jqueryscript.net/demo/Simple-Animated-Timeline-Plugin-For-jQuery-Timelify/

**Comment by isTravis** [comment]
We definitely have a timeline view for versions in the works. I've been thinking of adding additional data to the view, such as Journal features, new discussions, etc. I'm a bit nervous it will get too dense too quickly with lots of discussions, but worth a design!

Will keep you posted!

**Comment by trenkert** [comment]
Cool. I agree with the potential for cluttering the view. Maybe it would make sense - especially with regard to collaborators or more "serious" commenters/users to have something like an "expert" view or a desktop client with enhanced functionality? 

I was thinking of an application similar to ungit (https://github.com/FredrikNoren/ungit) for having an intuitive yet versatile interface to the whole history of and discussion around a text. 

This would (if it runs on the machine of the user) also decrease the server load, I guess.

**Comment by gabestein** [comment]
3 years later...we have a timeline that includes version history for the document in our latest release. Still working on handling discussions in it, but that's on the roadmap so I'm closing this issue for now.
