### ISSUE TITLE
Custom CSS does not apply everywhere

### ISSUE THREAD

**Issue by joshdavenport** [pubpub/pubpub#2045]
### What went wrong, step-by-step?
1. Add custom CSS, see styles load on all pages. We are adding styles that affect global areas such as the header, for aesthetic purposes
2. Open one of pages listed below in the "What URL" section, styles are not loaded

### What did you expect to happen?
Styles apply on that page for consistent aesthetic throughout, styles aren't applied in the exceptions listed.

### What URL can we use to see the issue?
Page that loads CSS: https://tghp.pubpub.org/

**Pages that do not but should:**
* Search (https://tghp.pubpub.org/search)
* 404 (https://tghp.pubpub.org/this-page-definitely-does-not-exist)
* User profile pages (https://tghp.pubpub.org/user/kate-sprague)

**Pages that do not but can't have styles for non-technical reasons (kept here for prosperity but established that they shouldn't be styled:**
* Legal
  * Terms of Service (https://tghp.pubpub.org/legal/terms)
  * Privacy Policy (https://tghp.pubpub.org/legal/privacy)
  * Acceptable Use Policy (https://tghp.pubpub.org/legal/aup)
  * Privacy settings (https://tghp.pubpub.org/legal/settings)
* Signup (https://tghp.pubpub.org/signup)
* Password reset (https://tghp.pubpub.org/password-reset)

### What browser/operating system were you using?
N/A

**Comment by gabestein** [comment]
Hi Josh — this is deliberate, as giving people the ability to edit CSS on these pages could allow folks to change sensitive items like terms or login that could create legal or security risks. I'll have a talk with the team about this — perhaps we could allow modifying header and footer styles even on those pages, or find a way to otherwise restrict content — but it'll be next week before we can get to anything.

**Comment by joshdavenport** [comment]
That's understandable. It easy to see why that choice, as you mentioned for security on the pages that are more part of PubPub itself than the particular community. For those pages then, they shouldn't appearance from the community whatsoever (Legal pages, Signup, Password reset) at least in my opinion.

In the case of the 404 and search pages though it does feel like the styles should apply there, as they're very much part of the community.

**Comment by gabestein** [comment]
Thanks — I agree 404 and search should be fully customizable. That should be pretty straightforward, but I do want to run it by folks.

For legal, login, signup, etc., though, we're in a bit of a bind. For both legal and technical reasons, those pages need to live at the community's main domain, not on PubPub. That, to me anyway, implies that they should inherit community styles...so we'll see. Perhaps we can find a simple way to allow a subset of styles to apply to those pages that wouldn't allow for content manipulation, but would allow for fonts and colors, etc.

**Comment by joshdavenport** [comment]
Another example has come up since originally reporting is community user profile pages e.g. https://tghp.pubpub.org/user/kate-sprague

I've clarified the original issue to detail the pages that ought to have styles, and that there doesn't seem to be any non-technical reason why they don't:

- Search (https://tghp.pubpub.org/search)
- 404 (https://tghp.pubpub.org/this-page-definitely-does-not-exist)
- User profile pages (https://tghp.pubpub.org/user/kate-sprague)

I can try and PR the changes if it helps, though it is a complex codebase and right now at least not sure where to start. If that would help, any pointers would be highly appreciated @gabestein

**Comment by gabestein** [comment]
Hi Josh, we're taking a look at these this week.

**Comment by gabestein** [comment]
Hey Josh - heads up that this is now done, and looking good!
