### ISSUE TITLE
Show "parent" pub connections in pub previews

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#2070]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?

As it stands, it's possible to display a connection *if it is a child connection generated by the pub in question* in such a way that connections created by this pub appear on a pub's description/preview tile (i.e. on the landing page), as well as in the hover-and-colorize Connections tile in the pub body.

<img width="1223" alt="Screen Shot 2022-06-15 at 5 45 49 PM" src="https://user-images.githubusercontent.com/60357197/173935350-4b0654a7-c3e8-4314-ae30-4801b4ed1ea0.png">

It would be nice if this worked the other way around as well. It should be possible to display parent connections--e.g. the original language version of which this pub is a translation--from the landing page for a collection.

### What would this enhancement help you accomplish?

Although this would be useful for lots of different types of projects (literary criticism?), it would be really great for translation. 
For some context, the forthcoming Spanish version of Data Feminism is the motive of this req.

What we want is the connection to the English pub appearing in a spot that's currently reserved for child connections/"connections created by this pub". For now, it looks like it only works in one direction.

---

### What's the URL to your PubPub community?
https://data-feminism.mitpress.mit.edu/bienvenida

### Who requested this? (If not you)
based on preliminary feedback from  Catherine D'Ignazio and Lauren F. Klein.

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/7
