### ISSUE TITLE
Harvard-style citation

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#2077]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
it seems that the Harvard-style citation isn't quite right, it looks like this:
 Porta, S. et al., 2022. Urban MorphoMetrics + Earth Observation: An integrated approach to rich/extra-large-scale taxonomies of urban form C. Ahn, C. Ignaccolo, & A. S. Miranda, eds. _Projections_, 16. Measuring the City: The Power of Urban Metrics. Available at: https://projections.pubpub.org/pub/vfwe0fdj.

### What did you expect to happen?
the article title should be in quotes, the full issue name in italics, and the publisher be shown as well. at least this is what the editors say.

 Porta, S. et al., 2022. ‘Urban MorphoMetrics + Earth Observation: An integrated approach to rich/extra-large-scale taxonomies of urban form’, Ahn C., Ignaccolo C., & Salazar Miranda A., eds. _Projections, 16. Measuring the City: The Power of Urban Metrics._ MIT Press. Available at: https://projections.pubpub.org/pub/vfwe0fdj.

### What URL can we use to see the issue?
https://projections.pubpub.org/pub/vfwe0fdj

### What browser/operating system were you using?

===

### Who reported this? (If not you)
Projections editors, Carmelo Ignaccolo

**Comment by gabestein** [comment]
Took a look at his briefly — this is an issue with citation.js that can be partially fixed by bumping it to 0.6.2.

But there's an issue there, which is that the most common Harvard CSL (harvard-cite-them-right 11ed), which citation-js imports, [uses double quotes for titles](https://github.com/citation-style-language/styles/blob/master/harvard-cite-them-right.csl) for some reason, and I'm not actually sure it can be easily fixed?

Additionally, as of version 0.6.x, citationjs no longer uses the APA 6th edition as their default style, meaning PubPub no longer supports it.

Taken altogether, what I think we should do is:

- Bump citation-js to the latest
- Import specific CSLs for APA-6th, Vancouer, and Harvard, rather than using the citation-js defaults.
- Maybe modify the cite-them-right to use single quotes, as suggested in the above issue?

**Comment by carmelo92** [comment]
Hi, thanks for looking into this. My apologies for reopening this issue but on my end, the citation style is still not working properly. More specifically, the publisher is missing and the name of the journal is not italicized. 

See below:

**This is what is displayed now:**
Porta, S. et al. (2022) 'Urban MorphoMetrics + Earth Observation: An integrated approach to rich/extra-large-scale taxonomies of urban form', _Projections_. Edited by C. Ahn, C. Ignaccolo, and A.S. Miranda, 16. Measuring the City: The Power of Urban Metrics. Available at: https://projections.pubpub.org/pub/vfwe0fdj.

![image](https://user-images.githubusercontent.com/22218438/175490060-8f63a57a-c2f2-4931-aa78-d5a7a8214bbe.png)

**This is how it should look like:**
Porta, S. et al., 2022. ‘Urban MorphoMetrics + Earth Observation: An integrated approach to rich/extra-large-scale taxonomies of urban form’, _Projections, 16. Measuring the City: The Power of Urban Metrics_. Edited by C. Ahn, C. Ignaccolo, & A. Salazar Miranda. MIT Press. Available at: https://projections.pubpub.org/pub/vfwe0fdj.

Thanks a lot!~

**Comment by gabestein** [comment]
Hello — thanks for getting in touch. If I understand correctly, I think most of what you're describing is working as expected. For context: we use the industry standard Citation Style Language to generate citations. We need to use this to ensure citation quality and to make sure we can properly represent and deposit your journal in other places, such as Crossref and Google Scholar.

As you may know, Harvard style [isn't actually maintained by Harvard, or anyone](https://guides.library.harvard.edu/cite/guides#:~:text=About%20the%20%22Harvard%22%20Style,-also%20called%20the&text=In%20general%2C%20%22Harvard%20Style%22,bibliographic%20citations%20in%20appended%20bibliographies.), it's more of a convention, with lots of variants. We're now using the most commonly-accepted version of the Harvard CSL, from Cite Them Right, which is also what Zotero, Mendeley, and all the major players use.

- Journal title: Your journal title in PubPub is _Projections_, the name of the community (you can also override this using the Cite As field in community settings), which is properly italicized. You've put the rest of the text, "16. Measuring the City: The power of Urban Metrics," in the collection Volume field. Harvard style does not italicize Volumes. For what it's worth, I think this is probably where it belongs, and the correct citation behavior, as most Harvard guides do not recommend italicizing volume. No journal I'm aware of changes its title every issue, and in fact, many systems such as Crossref would reject such title changes. I'm not aware of any styles that natively support an issue title. A few, like MLA, and APA have support for special issues titles, and we could potentially add support for that field, but even in those cases the styles all add something like `[Special Issue]` to the display. So, I don't think this is fixable, or desirable to fix.

- Publisher: I'm not aware of any Harvard styles that includes the publisher for journal articles, so the CSL is properly ignoring this field.

If you'd like to develop your own version of Harvard, or adopt one that has the features you're looking for, you're welcome to do so. We can easily import a CSL file from the official [CSL repository](https://github.com/citation-style-language/styles/), and there's a nice [visual editor](https://editor.citationstyles.org/visualEditor/) for doing so, but unfortunately we're not in a position to support developing custom styles for individual communities at present.
