### ISSUE TITLE
Editor not listed on "show details"

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#2078]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. When clicking on "show details"
2. Not all of the editors set for the colection are displayed under "Contributors" -- Carmelo Ignaccolo is missing
...

### What did you expect to happen?
All the attributions to be shown. 

### What URL can we use to see the issue?
https://projections.pubpub.org/pub/xusawg1f

### What browser/operating system were you using?

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="781" alt="Screen Shot 2022-06-20 at 4 56 28 PM" src="https://user-images.githubusercontent.com/20121061/174676877-d3ba9623-a891-4a38-9801-621c5519e7d0.png">

### Who reported this? (If not you)
Projections editor: Carmelo Ignaccolo

**Comment by idreyn** [comment]
Attributions associated with user accounts are improperly de-duped when they have different roles.
