### ISSUE TITLE
New HTML title editor is triggering a `pub-updated` `ActivityItem` when the page loads

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#2089]
Which is producing weird stuff like this (only in Communities with HTML titles enabled):

![image](https://user-images.githubusercontent.com/2208769/175375214-95ee4cee-2849-47a3-a791-941a231b7533.png)

We could fix this at a few levels, either on the client or the server.

**Comment by gabestein** [comment]
Resolved by #2110
