### ISSUE TITLE
Down caret icon not rendering in navbar

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2102]
Probably node18-related.

### What went wrong, step-by-step?
<img width="404" alt="Screen Shot 2022-06-28 at 11 18 30" src="https://user-images.githubusercontent.com/639110/176216889-4c5a2205-169b-44d0-b783-3ad7e461ea51.png">

### What did you expect to happen?
Proper icons.

### What URL can we use to see the issue?
https://www.sareview.org/

### What browser/operating system were you using?

===

**Comment by idreyn** [comment]
Fixed in d0ae7726b6fd4d338f7b6b7010cb68456652900b 

(Same issue as #2095)
