### ISSUE TITLE
PDF export references not deduplicated

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2133]
### What went wrong, step-by-step?
1. Exported a Pub with multiple of the same citations
2. PDF "citations"/"references" section shows all those citations, rather than deduplicating.

<img width="909" alt="Screen Shot 2022-07-18 at 12 21 42" src="https://user-images.githubusercontent.com/639110/179557180-4f86919a-0245-4a66-9488-02b465dbc2bf.png">

### What did you expect to happen?
Same citations are deduplicated in list at end.

### What URL can we use to see the issue?
https://hdsr.mitpress.mit.edu/pub/wgss79vu/draft?access=cyrbnn61

### What browser/operating system were you using?

===

### Who reported this? (If not you)
Amara / HDSR

**Comment by idreyn** [comment]
Fixed in 42e470d6aaa64cd161176daa42870e023707e10d
