### ISSUE TITLE
math editor followups

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2137]
- make math nodes referenceable/linkable
- adjust css to account for different wrappers between old and new math, new math too big in both editor and export
- some errors when there is only a math node on the page
- math not importing/exporting via pandoc, see: https://github.com/pubpub/pubpub/discussions/1869#discussioncomment-3186517

**Comment by howebenhowe** [comment]
dollar signs give trouble, for example when you click to edit [on this pub](https://notes.knowledgefutures.org/pub/q8gh8lv2/draft)

also, whatever is going on [here](https://help.pubpub.org/pub/08907yo3/draft)

**Comment by gabestein** [comment]
one more: undo/redo don't seem to work within math blocks themselves (only after exiting the block, you can command-z to restore the old one0
