### ISSUE TITLE
Math appears when trying to write about US dollars

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#2141]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Whenever there are two instances of USD ($) mentioned in a Pub,
2. The text in-between turns into LaTex-looking mathematics.
...

### What did you expect to happen?
Just the $ sign to appear and leave the text in-between alone. Copying and pasting from other places doesn't seem to cause this, but typing in a $ will cause the issue.

### What URL can we use to see the issue?
https://help.pubpub.org/pub/08907yo3/draft

### What browser/operating system were you using?
Google Chrome/BigSur macOS

===

### Have any screenshots? (Attach them by dragging the image here)

<img width="1113" alt="Screen Shot 2022-07-25 at 12 10 47 PM" src="https://user-images.githubusercontent.com/20121061/180826165-fefaadd2-615e-4604-a9e7-293c4198aedb.png">

**Comment by gabestein** [comment]
nice catch. I think we should basically not treat a second $ as closing a math node if there's a space in-between (or perhaps a space before the closing $).
