### ISSUE TITLE
Error generating DOCX/EPUB/LaTeX/JATS/Plaintext/OpenDocument download in some Pubs

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2146]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Try to download generated DOCX/EPUB/LaTeX/JATS/Plaintext/OpenDocument in some files
2. ![image](https://user-images.githubusercontent.com/21983833/181288922-ac5eb494-1f39-48ab-b8aa-004197e34f58.png)

The weird thing is that this doesn't happen all the time, I couldn't narrow down what was causing the issue. See below for working/not working urls.

The Network tab shows requests to a worker (see below), which does not seem to happen for "successful" downloads, which shows the following error (prettified)

```json
{
  "id": "c439234c-424f-4234-9daf-66c5e0880a33",
  "isProcessing": false,
  "error": "Cannot destructure property 'id' of 'resources.note(...)' as it is undefined.",
  "output": null
}
```

### What did you expect to happen?
I could download the file.

### What URL can we use to see the issue?
Working:
- https://openpresstiu.pubpub.org/pub/kritisch-wetenschappelijk-1/release/1?readingCollection=19a3c21e
- https://openpresstiu.pubpub.org/pub/kritisch-wetenschappelijk-0/release/1?readingCollection=19a3c21e

Not working:
- https://openpresstiu.pubpub.org/pub/kritisch-wetenschappelijk-4/release/1?readingCollection=19a3c21e
- https://openpresstiu.pubpub.org/pub/kritisch-wetenschappelijk-2/release/1?readingCollection=19a3c21e

### What browser/operating system were you using?
-

### Have any screenshots? (Attach them by dragging the image here)
see above

![image](https://user-images.githubusercontent.com/21983833/181289818-35220ca3-8354-4f0e-94d9-d48cf4150f6a.png)

**Comment by gabestein** [comment]
Thanks, and sorry about the issue! It's almost certainly related to something with the references in those two docs. We recently made some changes to our exporter, so we'll take a look.

**Comment by Dawit-Tegbaru** [comment]
Problems with PDF exports

[Susan Poulton] reported via email
18 hours ago (Tue, Sep 20 2022 at 4:29 PM)
 
To:"PubPub Support" <help@pubpub.org>
I'm trying to manually make a master PDF in Adobe Acrobat Pro merging together auto-downloaded PDFs of all the sections of our full PubPub report (https://deepseacapacity.oceandiscoveryleague.org/), and when I download certain individual sections as PDFs (ones interestingly with map figures embedded in them), while they will open in a PDF reader, they cannot be merged together into a single PDF. I get all kinds of "unsupported PDF" or "Unidentified file" errors kicked up when I try to do it. Some of the PDFs worked without issue (but most did not).

I've attached two of the PDFs I'm having problems with and some screenshots of some of the errors I'm receiving. We're getting many requests for this master PDF that we'd like to create so would really like to solve this!

Also, if it's helpful, here are links to files that couldn't be merged together in Acrobat and those that did after download if you want to recreate them from the source.

DIDN'T WORK AFTER DOWNLOAD
https://deepseacapacity.oceandiscoveryleague.org/pub/2022-global-regions-summary
https://deepseacapacity.oceandiscoveryleague.org/pub/2022-africa-results

DID WORK AFTER DOWNLOAD
https://deepseacapacity.oceandiscoveryleague.org/pub/2022-preface
https://deepseacapacity.oceandiscoveryleague.org/pub/2022-data-collection

I also tried downloading one of the "didn't work" documents as a Word document and then saving it in Word as a PDF, and received the following error, if that helps for troubleshooting.

Thanks,
Susan

——————————————————
Susan Poulton
Director of Strategy and Communications
Ocean Discovery League

[Americas Summary.pdf](https://github.com/pubpub/pubpub/files/9617745/Americas.Summary.pdf)

<img width="980" alt="Screen Shot 2022-09-20 at 4 30 35 PM" src="https://user-images.githubusercontent.com/72410195/191536825-f413cc17-c3d5-4c6f-935b-292c0089fdea.png">
