### ISSUE TITLE
Backspace in the discussion thread does not delete characters

### ISSUE THREAD

**Issue by eff-kay** [pubpub/pubpub#215]
Steps to reproduce:

1. Create a document
2. Start a discussion, add the title
3. Add something in the discussion content, hit the "backspace" on the keyboard, when the cursor is in the edit box, should not work....

Environment:
Chrome, windows 7

**Comment by isTravis** [comment]
Thanks for filing this! The discussions architecture this is referencing just got a big update. This bug should now be fixed in these new interfaces.
