### ISSUE TITLE
Render (post release) pub setting updates in exports

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#2151]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
Update autogenerated downloads when fields are updated post-release (e.g., changes to title, description, contributors, custom publication date, license/copyright, etc...) or prompt users to create a new release.

### What would this enhancement help you accomplish?
Maintain continuity between user behavior, displayed content, and autogenerated file exports.
---

**Comment by gabestein** [comment]
Thanks — we've discussed this quite a bit. Ultimately, I think we'll want to fix it by solving the core issue here, which is that most settings and fields should be part of the release, not the pub itself. So we should allow people to draft changes to titles, settings, etc., and then release them. I don't know when that will happen, but it's not a quick thing.

**Comment by gabestein** [comment]
Closing as stale. Should receive attention in https://github.com/pubpub/roadmap-repo/issues/7
