### ISSUE TITLE
Not possible to select cells in tables

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#2156]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. Imported an epub for an article with multiple tables.
2. Attempting to edit Table 1, I held shift and clicked multiple adjacent cells to select.
3. The cells are not selected. 
4. Table menu opens (but it's not possible to e.g. merge cells without having selected multiple cells, so I can't do much from here).

...

### What did you expect to happen?
Selection to work for the cells I clicked on

### What URL can we use to see the issue?
https://tmb.apaopen.org/pub/gh4lwpep

### What browser/operating system were you using?
chrome

===

**Comment by idreyn** [comment]
Resolved in f0f998883a4ec9800325b4eba6f1534cf210174c
