### ISSUE TITLE
Pub Title of slightly older pubs disappearing in Settings?

### ISSUE THREAD

**Issue by tosteiner** [pubpub/pubpub#2165]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. When opening an already-published pub's settings, the Title field is empty, although Pub Title is present

### What did you expect to happen?

Title of an already-published Pub to be displayed under Settings > Detail: Title

### What URL can we use to see the issue?

e.g. 
* https://copim.pubpub.org/dash/pub/copim-outreach-overview/settings
* https://copim.pubpub.org/dash/pub/book-launch-of-citizen-science-guide/settings

seems to affect slightly older pubs in our community, more recent ones appear to be fine. And doesn't seem to do much harm, just wondered about the discrepancy ... 

### What browser/operating system were you using?

Windows 10 / Firefox 103.0.1

===

### Have any screenshots? (Attach them by dragging the image here)

![Screenshot 2022-08-04 at 17-59-01 Settings · Book Launch of Citizen Science Guide](https://user-images.githubusercontent.com/41517607/182908285-7fe3f0c3-a027-49f1-be9f-a931c4d95a8b.png)

**Comment by gabestein** [comment]
Thanks Tobias, and sorry about this issue! Likely related to upgrades to the title to support bold and italic. We'll take a look.

**Comment by gabestein** [comment]
Fixed in facets upgrades.
