### ISSUE TITLE
Unable to set development environment

### ISSUE THREAD

**Issue by dalareo** [pubpub/pubpub#218]
Hi!

I am very interested in explore this project as a production app for [EduCaaS](http://educaas.io).
I've cloned Pubpub and pubpub-api projects and set config with localhost values but I am not able to login or create content.

Is there any way to import sample data to the DB?
Any help??

**Comment by isTravis** [comment]
Howdy! Yes - quite shortly. We're getting ready to roll out the master branch (previously the v3) branch on Monday. The repo is in heavy flux right now, but we'll have better documentation and some easier sample DBs you can connect to early next week. 

When you enter an email in signup - are you seeing anything in the SignUps table of the Postgres DB? We're not actively sending signup emails now on this, but will be by end of the weekend.

**Comment by dalareo** [comment]
Yes. My user is there, but, how can I activate it?

**Comment by isTravis** [comment]
We'll be going live today, which means emails should be sending which would resolve this. But - if you take the `hash` from the signup table, and navigate to localhost:3000/users/create/`hash`, it will let you create your account.

**Comment by dalareo** [comment]
Great!
User created but still not able to create/edit pubs. I will come back later. Great job guys!!
