### ISSUE TITLE
Truncated file upload button in Pub Settings

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#2182]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
Upload file button text is illegible. 

### What browser/operating system were you using?
Chrome Version 104.0.5112.81 (Official Build) (64-bit)

===

### Have any screenshots? (Attach them by dragging the image here)
![image](https://user-images.githubusercontent.com/72410195/184665121-f373e821-a9d4-47b1-8217-5cc2e75f27f1.png)

**Comment by gabestein** [comment]
Fixed in #2233
