### ISSUE TITLE
Undo/redo not working with LaTeX

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2186]
### What went wrong, step-by-step?
1. Create a math node and add some math.
2. Exit out of the math node
3. Undo via keyboard or menu.
4. Nothing happens.
5. Click into math node and undo.
6. Last change in the math editor is undone, but then the editor closes and you're unable to keep going.

### What did you expect to happen?
Cmd-z allows you to go back through math and other changes seamlessly.

### What browser/operating system were you using?

===

**Comment by howebenhowe** [comment]
it  works from #2268
