### ISSUE TITLE
[a11y] Only use 1 H1 tag per Pub

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2207]
### What's your enhancement request?

Currently, selecting a `Header 1` style results in a `h1` tag in the Pub. However, [a11y best practices encourage/require only having a single h1 tag per page.](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/#headings-in-html)

So ideally, only the title of the pub would be an `<h1>`, and `Header 1` would result in a `h2`, `Header 2` in `h3`, and so forth.

I try to accomplish this myself by just setting everything to `Header 2`, which works fine, except for the special `Abstract` header. If you want the abstract in the metadata, you need to create a `Header 1` header with the text "Abstract". I want this special header, but if I do that the order of the page is incorrect and the ToC doesn't represent the content correctly.

### What would this enhancement help you accomplish?

Better SEO, and better compliance with accessibility best practices.
---

**Comment by gabestein** [comment]
Closing as not planned. We've done a lot of research about the issue, the conclusion of which you can view [here](https://github.com/pubpub/pubpub/issues/2303).

Long story short, most of the debates over H1s and screen reader compatibility involve whether screen readers can correctly interpret nested headers on a page that contains only H1s and uses sections to signal header level. This is moot for PubPub, which doesn't support it. You can use multiple H1s on a page and produce viable document outlines as long as you intend them to all be at the same level, which we've confirmed both in the WCAG and in actual screen reader testing. You can also easily break outlines by incorrectly, for example, nesting an H3 below an H1. As a Word processor, we can nudge people towards best practices, but we can't reasonably prevent people from creating poorly structured documents.

The separate, more direct question here is how to create an abstract that doesn't use an H1. For this, and other related functionality, we'll be implementing #2000 as part of Layouts Iteration 2, hopefully in Q2 of this year in [our roadmap](https://github.com/orgs/pubpub/projects/12/views/5).

**Comment by tefkah** [comment]
thanks for doing such thorough research on this, I didn't know this was only really an issue when using `section` tags!

everythings good for me then, looking forward to seeing what you do with semantic boxes!
