### ISSUE TITLE
Comments on words or paragraphs

### ISSUE THREAD

**Issue by danicotillas** [pubpub/pubpub#221]
I´m following the development of pubpub for quite a long time, great tool.
I saw few versions before it was possible to comment just highlighting a word or a paragraph, is this possible yet or not anymore?

Thanks for the answer

**Comment by isTravis** [comment]
This feature is disabled for a moment, as we roll out the updates and formalize the structure of PubPub markdown and commenting. Highlights will be back with functionality on markdown, rich documents, and PDFs - which much better support and UI functionality all around.

Hopefully early next week!

**Comment by danicotillas** [comment]
Thanks @isTravis for the answer! You are doing an amazing development! Keep it going!

**Comment by trenkert** [comment]
Great to hear, @isTravis !

**Comment by ThariqS** [comment]
This is back!
