### ISSUE TITLE
Math in captions not displaying in pub body

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2210]
### What went wrong, step-by-step?
1. Add math to a caption
2. It properly displays in the caption box
3. It shows as raw latex in the pub body

### What did you expect to happen?
It should show as math in the Pub body

### What URL can we use to see the issue?
https://hdsr.mitpress.mit.edu/pub/sfzyu2c5/draft

### What browser/operating system were you using?

===

### Have any screenshots? (Attach them by dragging the image here)
![Screenshot (29)](https://user-images.githubusercontent.com/639110/187470799-1390ee92-1b8c-43a1-9b82-3f514799b2ca.png)

### Who reported this? (If not you)
Amara / HDSR

**Comment by 3mcd** [comment]
Fixed by #2221
