### ISSUE TITLE
Dashboard menu on mobile off left of screen

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2218]
### What went wrong, step-by-step?
1. Visit on a mobile device
2. Click top dashboard menu
3. Flows off left of screen!

### What did you expect to happen?
- Stays on screen.

### What browser/operating system were you using?
iPhone / iOS

===

**Comment by gabestein** [comment]
An example on iPhone Safari in portrait mode: https://hdsr.mitpress.mit.edu/pub/ftwzgrij/release/1

**Comment by djagdish** [comment]
1. when the width is capped at 300px
2. when width is capped, and text is wrapped

<img width="443" alt="image" src="https://user-images.githubusercontent.com/316939/202485530-3c63128d-4bf3-4c14-9245-1823b8809c0a.png">
