### ISSUE TITLE
An error has occured in the editor

### ISSUE THREAD

**Issue by ALedl** [pubpub/pubpub#2236]
### Discussed in https://github.com/pubpub/pubpub/discussions/2225

<div type='discussions-op-text'>

<sup>Originally posted by **ALedl** September  5, 2022</sup>
Hi,

when trying to go to this draft pub (https://0277.pubpub.org/pub/ailrzesn/draft?collectionSlug=critical-library-perspectives), I get the message: 

****
An error has occured in the editor.
We've logged the error and will look into the cause right away.

All previous changes have been successfully saved.

To continue editing, please refresh the page.
****

By refreshing the page, I get the same message again and editing remains blocked.</div>

**Comment by gabestein** [comment]
Thanks, I'm going to close and follow up on the discussion side if that's alright.
