### ISSUE TITLE
following a review link without being logged in is confusing

### ISSUE THREAD

**Issue by tomerweller** [pubpub/pubpub#225]
You get a "Pub Not Found" although you followed an official pubpub email link.
Ideally, the user should be redirected to login and then back to this pub.

**Comment by tomerweller** [comment]
Actually, I can't see it when I'm logged in as well. Closing this

**Comment by isTravis** [comment]
Hmm - what was the problem? The pub was actually set to private? Perhaps there is still a bug: It shouldn't be possible to invite reviewers to a Private pub.
