### ISSUE TITLE
Pub Download Errors in Chrome

### ISSUE THREAD

**Issue by kyledenlinger** [pubpub/pubpub#2259]
### What went wrong, step-by-step?
1. Open any pub in Chrome ([example)](https://genderhistory.pubpub.org/pub/welfare-queen-incarceration-black-mothers/release/1)
2. Attempt to download the pub in any format (I checked most, but definitely EPUB, XML, PDF, Doc)
3. Chrome opens a new tab, but does not initiate a download. Replicated in incognito, with extensions off, etc. Works fine in Firefox.

### What browser/operating system were you using?
MacOS 12.5.1, Chrome 105.0.5195.125, Firefox 105.0

**Comment by Dawit-Tegbaru** [comment]
Hi Kyle, I'm not able to replicate (also using Chrome). I just scheduled a quick chat to see if we can troubleshoot in real-time.

**Comment by kyledenlinger** [comment]
@Dawit-Tegbaru thanks for following up. Something must've been happening in the background with my Chrome setup. I've fixed it; I'll close this report.
