### ISSUE TITLE
idea: allow anonymous commenting with view access link

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2280]
to discuss, but, could we make it so you can add a comment anonymously if you have the "view" access link? (even on a release).

**Comment by metasj** [comment]
I'd welcome this. Ideally w/ session- or cookie-based pseudonyms (a la [nymity](https://threads-vue.dev.berkmancenter.org/)) so multiple comments from the same viewer are linked to the same nym, and could be migrated to a user if they decide to log in later in that session.
