### ISSUE TITLE
Word and Markdown exports are duplicating footnote text

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#2296]
### What did you expect to happen?

* That exporting a Pub with footnotes to Word and/or Markdown would produce only a single copy of each footnote
* Instead, the footnote text of each footnote is printed twice, with a line break in between

### What URL can we use to see the issue?

* Any Pub with footnotes, as far as my testing

Gabe's test: https://demo.pubpub.org/pub/o8c78ua9/draft

### What browser/operating system were you using?

* Safari for macOS Ventura beta

===

### Have any screenshots? (Attach them by dragging the image here)

![duplicate-footnotes](https://user-images.githubusercontent.com/6372329/196464154-2ddad7ea-2558-47f7-9038-234eda791e77.png)

**Comment by gabestein** [comment]
Thanks for the report Jeff. We'll get on it.
