### ISSUE TITLE
Cascading Menus: 'Header' section not working in Community settings

### ISSUE THREAD

**Issue by tosteiner** [pubpub/pubpub#2322]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. We just launched a new PubPub community today. 
2. When seeking to change the header image & layout via Community > Settings, click on 'Header' section, the whole page turns completely blank, appears to crash the whole PubPub instance. 
3. One then has to reload the whole page to get back to initial settings.

### What did you expect to happen?

Reaching the Header settings

### What URL can we use to see the issue?

https://expub.pubpub.org/

### What browser/operating system were you using?

OS: Windows 10 Pro / Version 22H2 / OS build 19045.2193
Browser: Firefox 106.0.3

===

### Have any screenshots? (Attach them by dragging the image here)

![Screenshot 2022-11-03 at 16-26-09 Settings · Experimental Publishing Conference](https://user-images.githubusercontent.com/41517607/199777994-c8ed4c7a-4f80-4961-b482-2abb90ed8e8a.png)
![Screenshot 2022-11-03 at 16-26-09 Settings · Experimental Publishing Conference2](https://user-images.githubusercontent.com/41517607/199778004-bbb547ff-be6c-45c1-a4f1-9e75cdc85376.png)

**Comment by idreyn** [comment]
Thanks for the report, @tosteiner. I just put up a fix for this. Let me know if you run into any more trouble with the new Settings page!

**Comment by tosteiner** [comment]
oh, wow, brilliant, thanks so much @idreyn - all looking good now, perfect!
