### ISSUE TITLE
Review link returning internal server error

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2331]
### What went wrong, step-by-step?
1. Create review link on any pub that has it enabled
2. Visit link, e.g. https://notes.knowledgefutures.org/pub/a1rpfgp0/review/86?access=oliak7o5
3. Get internal server error

### What did you expect to happen?
Loads page with review modal.

### What URL can we use to see the issue?
https://notes.knowledgefutures.org/pub/a1rpfgp0/review/86?access=oliak7o5

### What browser/operating system were you using?

===

**Comment by idreyn** [comment]
Fixed in 207dd48907dc5482a937243208390108d40c8703
