### ISSUE TITLE
"Computational Law" bug: new pub shows up as old one; trouble creating new pub

### ISSUE THREAD

**Issue by dazzaji** [pubpub/pubpub#234]
I posted a pub in Feb, then tried to edit my pub now.  
* I couldn't see my old pub.  Just a blank screen for a new directory?  with an intro message "logging you in" which was confusing, since I was already logged in...
* The new edit screen shows a test txt and test md file (which I can't open)
* After creating a new title and saving it, it doesn't show up; had to reload the page.
* Couldn't find a way to delete an extra blank new file I created
* After pasting an article from Medium in as a new pub, and saving it (as "v 0.0.2"), I saw a button to "view pub".  That took me to the old pub from Feb!
* From that new view of "my pubs" I see a list of revisions of that pub, w edit summaries, including my "v 0.0.2"... but clicking "view" for that revision again shows the Feb pub [which is totally different content].

Finally... it took me a while to figure out how to post a feature request / bug report here :)  a more explicit link would be neat.   Thanks!

**Comment by isTravis** [comment]
With the new release, many of these issues have been addressed in the new design. I'll close the issue for now, but if issues still remain - happy to reopen.
