### ISSUE TITLE
Column-width wrapping for Inline equations

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#2351]
In-line equation looks fine on laptop but bleeds off screen when viewing on mobile.  

### What URL can we use to see the issue?
https://jbt.pubpub.org/pub/b0nisrdj/release/1?from=18905&to=18931

### What browser/operating system were you using?
Chrome / Android

===

### Have any screenshots? (Attach them by dragging the image here)

Here's the eq. on laptop: 

![image](https://user-images.githubusercontent.com/72410195/201976780-992b003a-b5b4-4317-a307-198210cb9796.png)

On mobile:

![Screenshot_20221115-105147_Chrome](https://user-images.githubusercontent.com/72410195/201979544-e109d566-1348-4226-87b7-674499eaae21.jpg)

**Comment by gabestein** [comment]
Did a little research — KaTeX support just isn't there (yet?) for block equations (https://github.com/KaTeX/KaTeX/issues/1023). 

There are a few workarounds discussed in [this thread](https://github.com/KaTeX/KaTeX/issues/327) that I think might be worthwhile. The simplest/easiest/most aesthetically viable may be allowing overflowed equations to be scrolled until KaTeX figures out how to break block math effectively.
