### ISSUE TITLE
Full-width and full-screen iFrames

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2360]
### What's your enhancement request?
- Allow iFrames to be full-screened by adding required HTML attributes (see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute)

### What would this enhancement help you accomplish?
Create better experiences for iFrame-based content

---

### Any attachments or reference images? (Drag them here)
Should follow roughly this interface (without the link to):

<img width="413" alt="Screenshot 2022-11-28 at 10 24 57" src="https://user-images.githubusercontent.com/639110/204341864-0ca3c12d-1f65-4522-9b88-4fdc50504e3f.png">

### Who requested this? (If not you)
#2320

**Comment by BEvanGelderen** [comment]
We often use buttons in our iFrame to show the iFrame fullscreen, but this is only possible if the _allowfullscreen_ attribute is added to the html tag. Does this issue help with that as well?

**Comment by gabestein** [comment]
Ah, that's great. I am conflating full-width with full-screen, but we'll make sure to do both.

**Comment by BEvanGelderen** [comment]
Awesome!
