### ISSUE TITLE
Guest comment hash doesn't appear if there's no release

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2362]
### What went wrong, step-by-step?
1. Visit a draft with comment ability
2. Copy the comment on draft link
3. No access hash appears in link

### What did you expect to happen?
Get draft link with access hash

### What URL can we use to see the issue?
https://research.arcadiascience.com/pub/idea-defining-actin/draft

### What browser/operating system were you using?

===

**Comment by qweliant** [comment]
we use the release number in the url so we do not generate a url if there is no release. does the draft url not appear as well?

**Comment by gabestein** [comment]
the draft url appears but without a hash. See: https://research.arcadiascience.com/pub/idea-defining-actin/draft
