### ISSUE TITLE
Pub only show the same image

### ISSUE THREAD

**Issue by agrignard** [pubpub/pubpub#238]
I use to write this article few months ago (in september)
https://www.pubpub.org/pub/57ac6dedada4e9002dca9d4a

I've just recheck it and it seems that there is a problem in the figure as it is always the same picture that is displayed

**Comment by isTravis** [comment]
Don't know how it happened - but it seems all of the uploaded images on that pub share identical names: https://www.pubpub.org/pub/57ac6dedada4e9002dca9d4a/files. This will cause a problem for the renderer as it doesn't know which image to use. 

I'm happy to go and reupload all these images with new names, but you'll likely have to confirm they're in the right place afterwards.

**Comment by isTravis** [comment]
Ok - file names have been changed, so the original issue is now fixed, but you'll have to go into the editor now and make sure the images are in the right location. Use the '@' mention to quickly insert images in the right place.
