### ISSUE TITLE
.mov video not render

### ISSUE THREAD

**Issue by agrignard** [pubpub/pubpub#241]
I am trying to include a video that illustrates my work in this paper

https://www.pubpub.org/pub/andorra-cityscope

I have uploaded a .mov file which is around 50mb but i cannot see the rendering

Do I need to use another format? .mow should be ok no?

**Comment by isTravis** [comment]
.mov is unfortunately a proprietary Apple format and does not render on the web. We recommend converting it to a .mp4 instead. In the future, we should have a service that automatically offers this conversion on .mov upload.
