### ISSUE TITLE
zotero: OAuth key exchange

### ISSUE THREAD

**Issue by howebenhowe** [pubpub/pubpub#2414]
Notes:
If authentication token is absent or invalid, re-prompt user to authenticate with Zotero.

### implementation steps:
1. register application with zotero
2. add pubpub's client key and secret key to `config.js`
3. set up callback url for redirection from zotero
4. add ExternalLoginProvider model for storing authentication token, linked to User model (following [this model](https://vertabelo.com/blog/user-authentication-module/))
5. implement standard oauth handshake pattern [per zotero's criteria](https://www.zotero.org/support/dev/web_api/v2/oauth)

### new dependencies
one of the [TS](https://github.com/retorquere/zotero-sync) or [JS](https://github.com/tnajdek/zotero-api-client) clients (probably the latter)
investigate tradeoff with passport or oauth.io for credential storage

### Server side implications
+ change user model to hold:
  + OAuth long-lived token
  + zotero user id
+ new routes for OAuth callback urls

### Testing
1. Successfully grant OAuth access to PubPub account
2. Abandon then resume OAuth handshake
3. After success, revoke authentication

**Comment by gabestein** [comment]
new table w/creds rather than on user table

**Comment by gabestein** [comment]
look into passport for oauth functions/storage
