### ISSUE TITLE
Submit generated Datacite metadata to Datacite API

### ISSUE THREAD

**Issue by 3mcd** [pubpub/pubpub#2417]
Add a button to the deposit preview (developed in #2416) that, when clicked, executes an API endpoint that creates the final deposit and sends it to the Datacite API.

Required attributes on the deposit payload:

```ts
{
  id: <DOI>,
  type: 'dois',
  attributes: {
    event: 'publish',
    doi: <DOI>,
    url: 'https://schema.datacite.org/meta/kernel-4.4/index.html',
    xml: <Deposit XML>
  },
}
```

Current rules implemented in Crossref implementation should be re-implemented here, e.g. deposits should only be allowed when there is at least a single Pub release, and the DOI should be customizable for communities with a managed prefix.

### Error states

Since the Datacite API is synchronous (i.e. deposit requests are not added to a queue like Crossref), we should be able to report errors to the client immediately.

### Out of scope

* Pre-release DOI option will be implemented in a follow-up task.

**Comment by gabestein** [comment]
Missing: error states, when you wouldn't be allowed to submit, etc.

**Comment by gabestein** [comment]
Talk to Gabe about pre-release DOI option

**Comment by gabestein** [comment]
Error: print message from API and send to sentry.
