### ISSUE TITLE
Change `twitter:card = summary` to `twitter:card = summary_large_image` (+ some more ideas)

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2424]
# What's your enhancement request?

I would like a large preview card to show up on Twitter when I share a link to a pubpub page.

Optionally, I would also love the ability to set a "share" image that is different from the "preview" image. A share image is a) usually a different format than the preview image you see e.g. in a pub block (share image is 2x1 ish, preview is more square), and b) would maybe have different content (share image might have the title, preview probably wouldn't). I realize that this is unlikely to be implemented, as there already two image slots to worry about (preview and background), but I thought i'd shoot my shot!

REALLY optionally, integrating some way to automatically create share images through e.g. a custom url or by you through Vercel's [og-image library](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation) would be AMAZING, but I see that as kind of a niche demand.

## Current
Currently, PubPub links show only a small card on twitter.
![image](https://user-images.githubusercontent.com/21983833/207598076-f2a8d745-da30-4af0-bc77-6bdff92a85ab.png)

## Ideal
I think it'd be better if PubPub would show large card previews, like e.g. Nature. These incentivize clicks more. 
![image](https://user-images.githubusercontent.com/21983833/207598435-ac5ad585-ea14-4a06-8849-0ad2071e4d14.png)

## Potential cause

I have no idea actually. I thought it might be due to 
```html
<meta property="og:image:width" content="500"/>
```
or because the following tags 
```html
<meta name="twitter:image:width" content= "1200" />
<meta name="twitter:image:height" content= "630" />
```
are missing (the size the image needs to be to show the large card). I'm aware that by default the images are not that size (I think), but I managed to have PubPub point directly to our og image at https://og.trialanderror.org/api/og/jote?doi=10.36850%2Fe11 instead of converting and put it on assets.pubpub.org (please don't remove the abilitiy to do that 🙏😅).

However, I tried hosting a local copy of the HTML page through ngrok with either the image width meta tag removed or the width/height set properly, but they still showed the same small card. This might be a twitter caching thing, but I don't think so I used a url with different query params for the latter (https://og.trialanderror.org/api/og/jote?doi=10.36850%2Fe11&something=323 to be precise).

So I'm not sure why Twitter refuses to show the large card. It's kind of annoying to debug as well, since Twitter's preview thingy doesn't work anymore and all other "og preview" tools i've used show the card properly, so I have to post it on twitter directly to see the results.

# What would this enhancement help you accomplish?
In general, improve CTR from Twitter, which is one of the larger places where academics gather.

Very specifically, I created a custom integration that creates (imo) nice cards for our articles, but they do not get shown fully or in any legible fashion on Twitter. 

## How it's shown on twitter
![image](https://user-images.githubusercontent.com/21983833/207598803-f60c766b-7150-4d10-aa41-8fae19bd5f07.png)

## How it's shown on e.g. WhatsApp (ideal)
<img width="363" alt="image" src="https://user-images.githubusercontent.com/21983833/207598893-b3024904-3b99-4028-9554-f74bb36fe887.png">
 

---

### What's the URL to your PubPub community?
https://journal.trialanderror.org

The specific page is https://journal.trialanderror.org/pub/attentionalsmoker/release/2

**Comment by tefkah** [comment]
One thing I haven't tried yet is explicitly adding 
```html
<meta name="twitter:card" content="summary_large_image">
```

**Comment by gabestein** [comment]
Thanks for the suggestion! I think it'll work fine with the current recommended image size, in most cases. Tagging as a quick win for someone to take when they have some spare time.

**Comment by tefkah** [comment]
Glad to hear you're open to it! I'll have a look to see if I can implement it from my end and submit a pr :)
