### ISSUE TITLE
Export as PDF / docx query

### ISSUE THREAD

**Issue by r0bis** [pubpub/pubpub#244]
As I have said - `PubPub` is a fantastic piece of work; people can really cooperate, they can keep their texts private until they choose not to. About every necessary feature works, but there is no possibility presently to export the text and its images as a **PDF** and **docx**. (I am not a fan of docx by far, but there are some settings where it is just expected you would be able to present a word document) 

I understand at least PDF export was previously possible and I hope it comes back. As on my linux laptop I use a text editor and I can run `pandoc` from the editor to give an immediate PDF or docx output from my original markdown, I would hope that a similar mechanism could be employed here. 

`PubPub` in my team's experience would be far better than `Authorea` - which is also a good platform, but is more limited, however it produces PDF and docx output. 

And lastly if **EPUB** format could be supported too, it would be absolutely fantastic.

**Comment by ThariqS** [comment]
Thanks for the feedback Roberts! I'm working on getting PDF export back this week, so sorry for the delay. Docx is also possible but might take ab it longer.

**Comment by r0bis** [comment]
Wow, this is really good and encouraging. In fact we are just now thinking of putting a piece of collaborative work in progress on PubPub and I even proposed I could do the conversion (to PDF docx) on my computer, but it would be so much better to be able to do this from the interface. We especially like the fact that the Pub can be seen/shared as a webpage and an e-book type material can be produced from it too. We would hope to produce version 1 before end of June. For myself I will also experiment how to make an .epub via pandoc locally if I save the markdown, references and images. Would you think PDF might work before the end of June?

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

Potentially thanks to this thread, exporting to PDF, docx, and many other formats have been supported as of (I believe) V4!

**Comment by r0bis** [comment]
Wow, I just checked. It is very, very impressive. It now works, PDF is really nice quality, just like pandoc, ODT is superb and other formats work too. Congratulations it is very useful and our publication benefits from it immensely.

**Comment by gabestein** [comment]
Thanks, glad it'll be helpful for you! We're still working on getting some kinks out -- notes in particular aren't a great experience currently. But this is hopefully a pretty solid improvement.
