### ISSUE TITLE
Images and formulas are broken in pdf and epub exports

### ISSUE THREAD

**Issue by zudanievil** [pubpub/pubpub#2459]
### What went wrong, step-by-step?
1. i've created a community  on pubpub.org and created a new "pub" to test how the system works. i've inserted some random text and images with captions and some formulas. I've tried html, pdf and epub export.
2. The rendered pdf result lacks the images, while captions were present. formulas and links were  behaving as expected.
3. The epub handles the images but some formulas appear as $ ... $ latex expressions. it appears that the `\over` latex command triggers this behavior
Html output looks fine.

### What URL can we use to see the issue?
test pub url:
https://zhuda.pubpub.org/pub/oaw73lbv/release/1

### What browser/operating system were you using?
various chromium-based browsers

===

### Have any screenshots? (Attach them by dragging the image here)
missing images in pdf:
![image](https://user-images.githubusercontent.com/57864233/211835148-cea9e4a3-6525-4beb-88ff-d6fe5498f441.png)

in epub some formulas remain unformatted while other formulas render fine:
![image](https://user-images.githubusercontent.com/57864233/211836251-deffc995-b535-4793-acde-cab6ad7bcf7d.png)

### Who reported this? (If not you)
I've sent the URL above to some of my colleagues and they've confirmed to have the same issues with downloadable pdf and epub.

**Comment by gabestein** [comment]
Thanks for bringing this to our attention! We're taking a look at the image issues now.

Unfortunately, the equation formatting is expected. There's a subset of latex that Pandoc, which we use to produce non-HTML/PDF exports, doesn't support. When this happens, we output the raw latex rather than a blank mathml node.

**Comment by 3mcd** [comment]
Here's a stop-gap fix for images not appearing in PDF exports while I investigate this issue:

Select the image in the editor, and enable the option "Always use full resolution", as seen below.

![Screen Shot 2023-01-11 at 5 20 14 PM](https://user-images.githubusercontent.com/6402908/211930613-9e9584e1-bc79-4bab-9c3b-71c6595edcaf.png)

**Comment by 3mcd** [comment]
We just rolled a fix for the broken images in in PDF exports. You should be able to re-export the above Pub as a PDF with correct images!
