### ISSUE TITLE
Citation & render problems - bibtex file parsing issue?

### ISSUE THREAD

**Issue by r0bis** [pubpub/pubpub#246]
Hi,

We are putting our collaborative effort on PubPub; one of the authors encountered a problem in this pub https://www.pubpub.org/pub/03-institutional-therapy and was working on `references.bib` there. His internet  connection broke and when he came back online on his phone he could no longer get to the article. 

Here is quote from him "I was in the process of revising the file references.bib when my internet connection quit. I tried to access the publication again on my mobile phone, but it was impossible to access it for the whole evening. The internet connection came back this morning, but I still can't have access to the publication. Maybe there is an internal problem with PubPub internal server?"

From my part I previously noticed problems with bibtex file in the sense that editor just hung as I was typing and I worked around it through copying entire bib file content into text editor, working on it and then pasting it over and saving. I noticed if the syntax was not right the file also would not save, which I think is good, but there was no error message. 

So I am not sure if there are 2 problems or 1, but it would be great help if you could assist with the issue in the above pub. 

I suppose if I could access the pub files via ftp or shell, I might possibly resolve the issue; in situation like this one thinks about the value of alternative access or backups.

Thank you for your help

**Comment by r0bis** [comment]
I discovered I could still edit files by appending `/edit` to the link above. Basically bibtex file lacked a comma and that lead to error reference not found. I also found the inexplicable tendency for the editor to just add repeat bibtex entries at the end of file as in this pub https://www.pubpub.org/pub/01-psychoanalysis-chapter:
```
@misc{npsa_history_2017,
	author={Editor NPSA},
	title={{History of Neuropsychoanalysis}},
}
@misc{npsa_history_2017,
	author={Editor NPSA},
	title={{History of Neuropsychoanalysis}},
}
@misc{npsa_history_2017,
	author={Editor NPSA},
	title={{History of Neuropsychoanalysis}},
}
@misc{npsa_history_2017,
	author={Editor NPSA},
	title={{History of Neuropsychoanalysis}},
}
```
Your ideas on how to best use references.bib file would be appreciated. Can the file be edited after references have been inserted? Should it be edited offline and only when all references are clear then upload file? The process seems a bit depending on one's luck for now.

**Comment by ThariqS** [comment]
Hi Robert,

Thanks for clarifying this with us! You're right, our support for manually editing the bibtex file is not great for errors, we'll be sure to add display errors on the bibtex file. But yes, you should be able to edit the references.bib file at any time.

The repeat additions is definitely a bug, I'll have to look into why that is happening.

Regarding your collaborators problem, I've never heard of that before. While you're editing, only saving and uploading files depends on an internet connection. Otherwise you should be fine. Is he still unable to access the publication? Can he send a screenshot of what he sees?

Thanks!

Thariq

**Comment by r0bis** [comment]
Hi Tariq,

Thanks for the prompt response, I appreciate it a lot.

I managed to rectify the thing through appending "/edit" to the pub http
link. This gave me the list of files and allowed to open them (main.md and
references.bib) in edit mode. There were 3 errors:
1) a comma was missing in references.bib
2) the reference identifier was changed in references.bib but not in main.md
3) there was reference type used in references.bib that I do not think
exists. My colleague changed @book to @conference.

It seems to me that the all above confused the system so that it could not
render html. After I corrected the above errors it is now ok. And in
addition the main.md in editing mode gave error at the end - something like
'reference not found' in the place of the actual reference. That was
helpful and it still happened after I corrected errors 2 and 3 and went
away when I corrected the missing comma.

Best wishes,

Roberts

**Comment by ThariqS** [comment]
Thank you Roberts, that was a really useful bug report, we really appreciate that you take the time to work around this. These should all be pretty easy to be fixed. It's fine to keep it all in this issue.

**Comment by r0bis** [comment]
Yes, I can confirm that used citations get re-appended to the end of bibtex file. There is one citation used [@oury_psychotherapie_1970] and that is repeated at the end of the file many times; with braces inserted.

```
@incollection{dosse_borde_2011,
	address = {New York, NY},
	title = {La {Borde}, between myth and reality},
	isbn = {978-0-231-14561-9},
	language = {English},
	booktitle = {Gilles {Deleuze} and {Félix} {Guattari}: {Intersecting} {Lives}},
	publisher = {Columbia University Press},
	author = {Dosse, Francois},
	translator = {Glassman, Deborah},
	month = oct,
	year = {2011},
	pages = {40--54}
}

@incollection{dosse_daily_2011,
	address = {New York, NY},
	title = {Daily life at {La} {Borde}},
	isbn = {978-0-231-14561-9},
	language = {English},
	booktitle = {Gilles {Deleuze} and {Félix} {Guattari}: {Intersecting} {Lives}},
	publisher = {Columbia University Press},
	author = {Dosse, Francois},
	translator = {Glassman, Deborah},
	month = oct,
	year = {2011},
	pages = {55--75}
}

@book{delion_accueillir_2005,
	address = {Paris, France},
	title = {Accueillir et soigner la souffrance psychique de la personne : {Introduction} à la psychothérapie institutionnelle},
	isbn = {978-2-10-055259-7},
	language = {Français},
	publisher = {Dunod},
	author = {Delion, Pierre},
	year = {2005}
}

@inproceedings{oury_psychotherapie_1970,
	address = {Poitiers, France},
	title = {La psychothérapie institutionnelle de {Saint}-{Alban} à {La} {Borde}},
	publisher = {Archives IMEC},
	author = {Oury, Jean},
	year = {1970}
}

@incollection{bourg_institutional_2007,
	address = {Montreal, Ithaca},
	title = {Institutional psychotherapy \& the {La} {Borde} psychiatric clinic},
	isbn = {978-0-7735-3199-4},
	language = {English},
	booktitle = {From {Revolution} to {Ethics}: {May} 1968 and {Contemporary} {French} {Thought}},
	publisher = {McGill-Queen's University Press},
	author = {Bourg, Julian},
	month = may,
	year = {2007},
	pages = {125--137}
}

@misc{barere_borde_1977,
	address = {Paris, France},
	type = {Documentaire},
	title = {La {Borde} ou le droit à la folie},
	publisher = {Télévision Française 1},
	author = {Barère, Igor},
	year = {1977}
}

@misc{philibert_moindre_1996,
	address = {Paris, France},
	type = {Documentaire},
	title = {La {Moindre} des choses},
	publisher = {Éditions Montparnasse},
	author = {Philibert, Nicolas},
	year = {1996}
}

@misc{djemai_a_2012,
	address = {Paris, France},
	type = {Documentaire},
	title = {À peine ombre},
	publisher = {Nazim Djemaï, Images de la Culture (CNC), La Maison du Doc},
	author = {Djemaï, Nazim},
	year = {2012}
}

@misc{godard_au_2016,
	address = {Paris, France},
	type = {Documentaire},
	title = {Au jour le jour, à la nuit la nuit},
	publisher = {Abacaris Films},
	author = {Godard, Anaëlle},
	year = {2016}
}

@article{duprez_psychosocial_2012,
	title = {Psychosocial rehabilitation and institutional psychotherapy},
	volume = {84},
	issn = {0020-0204},
	url = {http://www.cairn.info/revue-l-information-psychiatrique-2008-10-p-907.htm},
	language = {fr},
	number = {10},
	urldate = {2017-06-22},
	journal = {L'information psychiatrique},
	author = {Duprez, Matthieu},
	month = nov,
	year = {2012},
	keywords = {politique, psychose, Psychothérapie institutionnelle, réhabilitation psychosociale},
	pages = {907--912}
}

@article{pouillaude_schizophrenia_2012,
	title = {Schizophrenia, alienation and institutional psychotherapy},
	issn = {0297-1194},
	url = {http://www.cairn.info/revue-de-psychotherapie-psychanalytique-de-groupe-2012-2-p-45.htm},
	language = {fr},
	number = {59},
	urldate = {2017-06-22},
	journal = {Revue de psychothérapie psychanalytique de groupe},
	author = {Pouillaude, Élie},
	month = dec,
	year = {2012},
	keywords = {aliénation, institution, Psychanalyse, Psychiatrie, Psychothérapie institutionnelle, Schizophrénie},
	pages = {45--54}
}
@article{wenger_paranoia_2011,
	title = {Paranoia and {Institutional} {Psychotherapy}},
	volume = {76},
	issn = {0751-7696},
	url = {http://www.cairn-int.info/revue-adolescence-2011-2-p-355.htm},
	number = {2},
	urldate = {2017-06-22},
	journal = {Adolescence},
	author = {Wenger, Stephan},
	month = jul,
	year = {2011},
	pages = {355--383}
}@inproceedings{oury_psychotherapie_1970,
	author={Jean Oury},
	address={Poitiers, France},
	publisher={Archives IMEC},
	title={{La psychothérapie institutionnelle de {\textless}span class="nocase"{\textgreater}Saint{\textless}/span{\textgreater}-{\textless}span class="nocase"{\textgreater}Alban{\textless}/span{\textgreater} à {\textless}span class="nocase"{\textgreater}La{\textless}/span{\textgreater} {\textless}span class="nocase"{\textgreater}Borde{\textless}/span{\textgreater}}},
	year=1970,
}
@inproceedings{oury_psychotherapie_1970,
	author={Jean Oury},
	address={Poitiers, France},
	publisher={Archives IMEC},
	title={{La psychothérapie institutionnelle de {\textless}span class="nocase"{\textgreater}Saint{\textless}/span{\textgreater}-{\textless}span class="nocase"{\textgreater}Alban{\textless}/span{\textgreater} à {\textless}span class="nocase"{\textgreater}La{\textless}/span{\textgreater} {\textless}span class="nocase"{\textgreater}Borde{\textless}/span{\textgreater}}},
	year=1970,
}
@inproceedings{oury_psychotherapie_1970,
	author={Jean Oury},
	address={Poitiers, France},
	publisher={Archives IMEC},
	title={{La psychothérapie institutionnelle de {\textless}span class="nocase"{\textgreater}Saint{\textless}/span{\textgreater}-{\textless}span class="nocase"{\textgreater}Alban{\textless}/span{\textgreater} à {\textless}span class="nocase"{\textgreater}La{\textless}/span{\textgreater} {\textless}span class="nocase"{\textgreater}Borde{\textless}/span{\textgreater}}},
	year=1970,
}
@inproceedings{oury_psychotherapie_1970,
	author={Jean Oury},
	address={Poitiers, France},
	publisher={Archives IMEC},
	title={{La psychothérapie institutionnelle de {\textless}span class="nocase"{\textgreater}Saint{\textless}/span{\textgreater}-{\textless}span class="nocase"{\textgreater}Alban{\textless}/span{\textgreater} à {\textless}span class="nocase"{\textgreater}La{\textless}/span{\textgreater} {\textless}span class="nocase"{\textgreater}Borde{\textless}/span{\textgreater}}},
	year=1970,
}
@inproceedings{oury_psychotherapie_1970,
	author={Jean Oury},
	address={Poitiers, France},
	publisher={Archives IMEC},
	title={{La psychothérapie institutionnelle de {\textless}span class="nocase"{\textgreater}Saint{\textless}/span{\textgreater}-{\textless}span class="nocase"{\textgreater}Alban{\textless}/span{\textgreater} à {\textless}span class="nocase"{\textgreater}La{\textless}/span{\textgreater} {\textless}span class="nocase"{\textgreater}Borde{\textless}/span{\textgreater}}},
	year=1970,
}
```

**Comment by isTravis** [comment]
With the release of v4, we no longer rely on a bibtex file for tracking citations. Citation data is stored in-line with the WYSWIG editor, so these issues are resolved.
