### ISSUE TITLE
Pub cannot be deposited to Crossref (account not connected) 

### ISSUE THREAD

**Issue by Dawit-Tegbaru** [pubpub/pubpub#2463]
### What went wrong, step-by-step?
Depositing pubs to Crossref is currently unavailable reportedly due to Crossref accounts not being connected to PubPub.  

...

### What did you expect to happen?
Communities with Crossref membership can deposit PubPub content.
Communities with Crossref membership can update PubPub deposits. 

### What URL can we use to see the issue?
https://jbt.pubpub.org/dash/pub/wc73gn00/settings/doi
https://jbt.pubpub.org/dash/pub/b0nisrdj/settings/doi
https://hdsr.mitpress.mit.edu/dash/pub/b2tswdg6/settings/doi

### What browser/operating system were you using?
Chrome

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="1155" alt="Screenshot 2023-01-18 at 10 23 36 AM" src="https://user-images.githubusercontent.com/72410195/213241062-b6da2f68-fc33-4dfd-82cb-2dbf20532453.png">

**Comment by Dawit-Tegbaru** [comment]
Thanks!

**Comment by gabestein** [comment]
Thanks for reporting, and sorry about that! It'll be up in 15 mins or so.
