### ISSUE TITLE
Suggestion: Markdown cheatsheet readily available

### ISSUE THREAD

**Issue by r0bis** [pubpub/pubpub#248]
No matter how much I like WYSIWYG editor, I believe it is very important for authors to have an accessible markdown help available at a single click. Perhaps as an overlay. Examples of good cheatsheets this way I have sen include Ghost Blog markdown editor, Rstudio markdown help and I think Github also implemented this somewhere. For PubPub this would need to show essential features supported by PubPub (headers, links, lists, images, references, maybe tables).

**Comment by isTravis** [comment]
With the new release of PubPub v4, we no longer implement a markdown interface. WSYWIG is the only interface.
