### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by agrignard** [pubpub/pubpub#249]
I am reopening an old paper that was already published and I am surprised to see that all the images are not there anymore.

https://www.pubpub.org/pub/57ac6dedada4e9002dca9d4a

Also it asks me to click to download the new image but it doesn't work.

If the paper was published it would be great to have something like a pdf or a bake version of it (for instance to remember which image was there).

**Comment by ThariqS** [comment]
Hi Arnaud,

Thanks for reporting this! It was a problem migrating your older paper to the newer version of pubpub. I've fixed this and the images should now show!

Cheers,

Thariq
