### ISSUE TITLE
"Filter by collection" should exclude those pubs not in all ticked collections--not add all contents of every ticked collection

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#2491]
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?

When setting up a pubs block, I still expect that choosing two filters in the "filter by collection" field will result in displaying only the pubs that are in both collections.

That isn't the case. When I do this, I get all of the pubs in both collections.

### What would this enhancement help you accomplish?

In the case I was just working with, I wanted a pubs block to include all of a certain type of contribution (tagged "reflection") for a particular year ("2020"). If multiple filter-by-collection collections resulted in a more excluding display (as opposed to inclusive: the overlap in the Venn diagram, not both circles entire), I would be able to do this easily. Right now, the only way of doing it is to select/pin all the individual pubs with category overlap. 

This is especially relevant and aggravating when using a submissions workflow, where new items under the old tag could come through any old time.

---

### What's the URL to your PubPub community?
domesticknowledge.pubpub.org

### Who requested this? (If not you)
myself

**Comment by gabestein** [comment]
Thanks -- it's certainly come up, and we'll be addressing it (and other block issues) as part of https://github.com/pubpub/roadmap-repo/issues/7, currently planned for next quarter.
