### ISSUE TITLE
Import new Modal Link Component from Figma

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2497]
# Overview

To create a new dev/design process we are considering building a component library in Figma based on MUI(google's material UI). This means defining each component PubPub uses in Figma. This makes the design process more cohesive. We can then copy the design of components defined there using a token file. The file will describe the styling of each component. 

## There are a few strategies we can use when designing this. 

We could parse the token file to describe the MUI theme. This is something that shipwright does [automatically](https://github.com/headwayio/shipwright-tokens/tree/a51ff008ead1d6faf47eca719ac1a3f278032d48). We could use shipwright or the code that transforms token files into MUI themes from their repo. 

This way we could generate component styling from MUI [ThemeProvider](https://mui.com/material-ui/customization/theming/) using them MUI theme json. 

We could also use [style-dictionary](https://amzn.github.io/style-dictionary/#/README) to generate sass variables that can be used across the codebase

### Notes/Links

https://notes.knowledgefutures.org/pub/nvca64jw/draft

**Comment by qweliant** [comment]
Closing this issue as refinement is required. 

### A comment
There are some interesting [conversations](https://github.com/mui/mui-design-kits/issues/10) going around [design systems](https://github.com/mui/mui-design-kits/issues/26#issuecomment-948472476) that can leverage design tokens to be the source of truth for component library files defined in figma **and** some component library that can be imported. 


We need a design token that is constant in its structure to flatten. 

We need to transform that token and add it to style dictionary

We need to consider how token files arrive in our code base
