### ISSUE TITLE
Support for Altmetrics

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#250]
It is becoming more and more standard that journals need to provide article level metrics. Request to provide support for Altmetrics by including the necessary meta-data on pub pages.

https://help.altmetric.com/support/solutions/articles/6000086842-getting-started-with-altmetric-on-your-journal-books-or-institutional-repository

**Comment by gabestein** [comment]
Hey Devin -- I think we've decided, for now anyway, not to integrate with Altmetric for a few reasons: there's less community support/requests for it than we anticipated, it doesn't currently consider paywalled articles as part of its metric, and those are becoming a larger part of the media landscape, and it feels increasingly less aligned with our values.

We are planning to support other (lowercase a) altmetrics, and will still consider Altmetric if more people request it. If you have any advice/ideas in that department, let us know.
