### ISSUE TITLE
URL for Google Scholar

### ISSUE THREAD

**Issue by jermainkaminski** [pubpub/pubpub#251]
Please verify, but I think that the actual URL for Google Scholar is missing the `citations?user=`. The  preview URL below the input field seems to be correct.

**Comment by isTravis** [comment]
Good catch. This was indeed missing. I just [added a fix](https://github.com/pubpub/pubpub/commit/def0f5ae2c969be461babf784cd1071dc92cd6fb) for this to v4. This will be live on all v4 communities shortly.
