### ISSUE TITLE
Add Mastodon profile to Community settings (and, thus, to Header & Footer social media sections)

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2514]
### Discussed in https://github.com/pubpub/pubpub/discussions/2513

<div type='discussions-op-text'>

<sup>Originally posted by **tosteiner** February  7, 2023</sup>
With the increasing popularity of Mastodon as the major Fediverse alternative to Twitter, I was wondering if it would be possible to have a dedicated Mastodon line in the community settings, which would then auto-populate to Header and Footer areas in a similar way to what we currently have for Twitter?

In addition to that, if this could be rendered with the HTML `rel`-tag intact, this would help with direct integration with Mastodon's profile [link verification](https://docs.joinmastodon.org/user/profile/#verification) feature.

Screenshot of the area I'm referring to [here](https://cloud.flavoursofopen.science/index.php/s/MQDQWjgC5XNnecM).</div>

**Comment by tosteiner** [comment]
come to think of it, this would also relate to PubPub users' personal profile pages, where there's also a section on social media profiles 😉

**Comment by yaxu** [comment]
Came here to suggest the same thing! Perhaps it could replace the twitter field, as that platform no longer exists apart from a far-right messaging platform under a different name.
