### ISSUE TITLE
How to subscribe to RSS feeds? 

### ISSUE THREAD

**Issue by amicoleo** [pubpub/pubpub#252]
Can anybody tell me if available and where I can find address for pubpub journal RSS feed? In particular I was looking to subscribe to https://pubpub.ito.com/ and https://jods.mitpress.mit.edu/

PS
Apologies if this is not the best place for asking such a question. I couldn't find any relevant information elsewhere and as some issues here mentions the RSS feeds (#71, #59) I figured out there might be somebody able to help me.

**Comment by trenkert** [comment]
in version 4 of pubpub, you can subscribe to RSS feeds by clicking on the link in the footer:

![image](https://user-images.githubusercontent.com/143727/33180412-e3f89058-d06c-11e7-93f9-bb9149204851.png)

**Comment by isTravis** [comment]
Thanks for answering that, Thomas! Thomas is correct, though not all journals and pubs are migrated to v4 yet, so if you don't see the RSS button, hang tight a couple weeks!

Thanks!

**Comment by amicoleo** [comment]
Ok, I asked because I was looking for RSS for the Journal of Design and Science. I guess that is not migrated yet, then. 

Thanks!
