### ISSUE TITLE
Publish a pubpub?

### ISSUE THREAD

**Issue by franziska-art** [pubpub/pubpub#2542]
### What went wrong, step-by-step?
1. I have filled in all text into a pubpub and it is saved as a draft
2. I am unable to publish. I sought help and understand that I need to locate the Publish Button to create a release. I cannot find a Publish Button!? I am using Chrome.
...

### What did you expect to happen?
I am looking for a publish button - it is said to be in the Header, but I am unable to see it/publish the draft.

### What URL can we use to see the issue?
This is the draft but it is not public, from what I can see: https://aimc2023.pubpub.org/pub/8x9jxz9a

### What browser/operating system were you using?
MAC Book Pro M1/Venutra /Chrome Version 110.0.5481.100 (Official Build) (arm64)

### Have any screenshots? (Attach them by dragging the image here)
<img width="1196" alt="Screenshot 2023-03-01 at 14 22 46" src="https://user-images.githubusercontent.com/125808555/222168456-b466543f-363a-46d2-a0d6-5c0e20dacb12.png">

**Comment by gabestein** [comment]
Hello! Taking a look, I believe you don't have permissions required to create a release. You'll need to contact your Community's admins/editors to see how they want you to proceed. They may give you more permissions, or they may ask you to request publication, depending on how their process is setup.
