### ISSUE TITLE
Private Discussion Space

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#259]
Add support for private discussion spaces on Pubs. These could be used for the following scenarios:

- A journal club wants to review and discuss a paper in private
- A classroom wants to annotate and understand a written work
- Blind reviewers want to have conversations with the managers without the author's access.

The privacy, access, and management of these spaces needs design consideration.

**Comment by gabestein** [comment]
_Closing some old issues. Going forward, feel free to post feedback to [https://discourse.knowledgefutures.org](https://discourse.knowledgefutures.org)_

Supported since V5 via discussion channels!
