### ISSUE TITLE
Images always display at full-width regardless of setting (except for breakout mode)

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2624]
### What went wrong, step-by-step?
1. Paste an image
2. Try to change the width using the width slider
3. Nothing happens

This also retroactively happens to already existing images, not just to new ones.

The `data-size` property seems to update fine, it just does not reflect in the UI.

https://user-images.githubusercontent.com/21983833/233319578-93a297f2-9d25-46fe-8465-c73aced80ad5.mp4

### What did you expect to happen?
The width of the image to change

### What URL can we use to see the issue?
https://journal.trialanderror.org/pub/gamified-inoculation
Check the `data-size` property and see that it is set to 22, while the image is obvs bigger

### What browser/operating system were you using?
Latest Chromium, Mac

**Comment by gabestein** [comment]
Sorry Thomas! We introduced this inadvertently, and it is now fixed.

**Comment by tefkah** [comment]
Thanks for the quick fix!
