### ISSUE TITLE
bug: adding a connection

### ISSUE THREAD

**Issue by johav** [pubpub/pubpub#2646]
### What went wrong, step-by-step?
I experienced this: As I tried to add a connection external url [scholarlykitchen.sspnet.org/2023/04/19/guest-post-mapping-open-science-resources-from-around-the-world-by-discipline/](http://scholarlykitchen.sspnet.org/2023/04/19/guest-post-mapping-open-science-resources-from-around-the-world-by-discipline/) to https://access2perspectives.pubpub.org/dash/pub/uwl451tj/connections - the issue seems to be with the http:// prompt, as the page then flips away to a blank page of the same url.

### What did you expect to happen?
adding a connection

### What browser/operating system were you using?
Firefox

**Comment by gabestein** [comment]
Thanks for reporting, Jo. We’re taking a look.
