### ISSUE TITLE
open graph image missing 

### ISSUE THREAD

**Issue by tomerweller** [pubpub/pubpub#27]
tag is there but the content is an empty string. same for twitter card. 
tested:
http://www.pubpub.org/pub/esp32-osx-setup
http://jods.mitpress.mit.edu/pub/designandscience

<meta data-react-helmet="true" property="og:image" content=""/>
<meta data-react-helmet="true" name="twitter:image" content=""/>

**Comment by isTravis** [comment]
Fixed with new architecture.
