### ISSUE TITLE
When logged in, one (seemingly) random item from the bundle will take 30seconds to load

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2715]
### What went wrong, step-by-step?
1. Log in to a pubpub community (e.g. frankenbook.org)
2. Pages take very long to load
3. Look at network requests while loading
4. See that either a css or js file is pending (just one, rest load fine)
5. After 30 sec, the file will load or the request will fail

This does not happen when not logged in. Does not seem to matter what account (admin for community or not)

I cannot reproduce this on dev

### What did you expect to happen?

Pages loading in a reasonable time

### What URL can we use to see the issue?

https://frankenbook.org

### What browser/operating system were you using?

MacOS Ventura, Safari/Chromium

### Have any screenshots? (Attach them by dragging the image here)

Pending (the page does load if its a js file that "gets stuck", won't if its a css file)
<img width="1370" alt="image" src="https://github.com/pubpub/pubpub/assets/21983833/109c8b45-2ddd-4f7d-98a8-dc3a03309839">

Fail
<img width="1370" alt="image" src="https://github.com/pubpub/pubpub/assets/21983833/55aa0bf0-473d-4fdb-9bb6-bbe31edfa3dc">

**Comment by gabestein** [comment]
Thanks Thomas. Something happened with the automated daily restart that caused some connection errors. I had to restart the app. I believe it's resolved now.
