### ISSUE TITLE
Search that works on pub content.

### ISSUE THREAD

**Issue by sawevans** [pubpub/pubpub#272]
[Searching](https://www.responsivescience.org/search) for anything on responsivescience.org returns no results.

**Comment by isTravis** [comment]
The 'bug' here is that search only looks at article titles and descriptions. It would be nice to have a more robust and deep-text search tool. I'm going to rename this issue and label it as a feature request.

As we consider this better community-wide (and pubpub-wide) search, we should also consider intra-pub search for pubs with multiple chapters. That may or may not require the same architecture.
