### ISSUE TITLE
Page bullets are too large and overlap weirdly with aligned left/right images

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2737]
### What went wrong, step-by-step?
1. See page with bullets, e.g.: https://hdsr.mitpress.mit.edu/podcast 
2. Notice that all the bullets on the page are very large.
3. Notice that bullets in grafs with aligned-left images are overlapping the images.

Seems to only occur on Pages, but we should check on Pubs as well.

### What did you expect to happen?
- Bullets sized similarly to pubs.
- Bullets aligned with text, not with images.

### What URL can we use to see the issue?
https://hdsr.mitpress.mit.edu/podcast

### What browser/operating system were you using?
Mac / Chrome

### Have any screenshots? (Attach them by dragging the image here)
![image](https://github.com/pubpub/pubpub/assets/639110/ef068228-bb65-495a-b927-2531d40123d1)

### Who reported this? (If not you)
Amara / HDSR

**Comment by qweliant** [comment]
The bullet points are set to https://github.com/pubpub/pubpub/blob/b1318bb80749677601010c5d3100f4e7200743c9/client/components/Editor/styles/main.scss#L84 making them override the specificity of any content before it, which is an image. Not sure how to fix though

http://localhost:9876/dash/pages/home
