### ISSUE TITLE
Bullets appearing incorrectly at some widths

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2748]
Likely related to SE changes.

### What went wrong, step-by-step?
1. Visit https://homeworld.pubpub.org/pub/intro-biotech-cdr/release/2?readingCollection=ef534b7c
2. See bullets, which are appearing on the line above the graph.

### What did you expect to happen?
They should appear to the left of the graf.

### What URL can we use to see the issue?
https://homeworld.pubpub.org/pub/intro-biotech-cdr/release/2?readingCollection=ef534b7c

### Have any screenshots? (Attach them by dragging the image here)
<img width="712" alt="Screenshot 2023-07-04 at 13 04 22" src="https://github.com/pubpub/pubpub/assets/639110/389d61c8-aaf2-43fb-9779-79699fde65b0">

**Comment by kalilsn** [comment]
This isn't from the bullet changes I'd made for suggested edits, it's [community-level custom CSS](https://homeworld.pubpub.org/dash/scripts):

![image](https://github.com/pubpub/pubpub/assets/473542/d5478760-79fa-4762-ba49-04983cb49d06)

**Comment by gabestein** [comment]
Ah. Sorry! I should have checked.
