### ISSUE TITLE
Uncaught ReferenceError: _paq is not defined

### ISSUE THREAD

**Issue by Andrewyg** [pubpub/pubpub#276]
I not sure is it my fault, since it looks like the error occurs due to I use Chinese title. So if you go to [my site](https://writerwrite.com), and visit any pub like [this one](https://writerwrite.com/pub/vsrumc-rgb) and open the console, you'll see the error `Uncaught ReferenceError: _paq is not defined` and with that error, all script related stuff won't work, like pinning discussion to side, or replying to discussion, or even you can't access layout section if it's a page. But the error doesn't occurs on Edge (which goes with Win10), not sure why, but this is what I've experienced.

**Comment by isTravis** [comment]
I can reproduce this. Will take a look - thanks for the issue report!

**Comment by Andrewyg** [comment]
@isTravis Actually I want this bug to be fixed as fast as you can, since with this error here, I can't do any action then create/view pub without switching to Edge.

**Comment by isTravis** [comment]
I believe this bug is fixed now with 7739cae. Please confirm if it is fixed on your end as well. Thanks for your patience!

**Comment by Andrewyg** [comment]
Yep, fixed
