### ISSUE TITLE
Zotero integration not working?

### ISSUE THREAD

**Issue by yaxu** [pubpub/pubpub#2772]
I've reproduced the below issue in firefox and chrome, on two different computers.

### Discussed in https://github.com/pubpub/pubpub/discussions/2771

<div type='discussions-op-text'>

<sup>Originally posted by **yaxu** July 14, 2023</sup>
I'd love to be able to add citations from zotero! When I click the 'zotero integration' button, it takes me to a privacy page. I click 'activate' under the zotero section, nothing happens for a while, and then it times out with an error page. 

![image](https://github.com/pubpub/pubpub/assets/27940/25caffa3-f6e8-46bb-a836-db9d0f37b4f2)
</div>

**Comment by gabestein** [comment]
(Accidentally) duplicated in #2775
