### ISSUE TITLE
Zotero integration not working

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2775]
Confirmed this isn't working. To flesh out/discuss tomorrow.

### Discussed in https://github.com/pubpub/pubpub/discussions/2771

<div type='discussions-op-text'>

<sup>Originally posted by **yaxu** July 14, 2023</sup>
I'd love to be able to add citations from zotero! When I click the 'zotero integration' button, it takes me to a privacy page. I click 'activate' under the zotero section, nothing happens for a while, and then it times out with an error page. 

![image](https://github.com/pubpub/pubpub/assets/27940/25caffa3-f6e8-46bb-a836-db9d0f37b4f2)
</div>

**Comment by howebenhowe** [comment]
Yep yep, saw this this morning. I reproduced it both in duqduq and in dev. In dev, the page waits, devtools logs a navigation to the auth endpoint (though it's not reflected in the visible URL) and then nothing. In duqduq, you get the following:
![Screenshot from 2023-07-17 15-43-05](https://github.com/pubpub/pubpub/assets/14115194/5e8d7259-0819-4fc5-85a5-e26dd9e5028a)

**Comment by gabestein** [comment]
Huh, thanks! It shouldn't be cached. I'll check it out in fastly.
