### ISSUE TITLE
Add loading indicator for editor page

### ISSUE THREAD

**Issue by tomerweller** [pubpub/pubpub#28]
There's a gap between when the edit page loads and when the content loads. It can easily take over 2 seconds. Some sort of loading indicator could ease the pain.

![wgyarolhqg](https://cloud.githubusercontent.com/assets/815704/14252492/9c0b0f94-fa55-11e5-826a-e489d2830328.gif)

**Comment by isTravis** [comment]
Architecture this was referencing has since been replaced.
