### ISSUE TITLE
Make deletion reversible

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#281]
Make deletion reversible by an admin; there are always ways to make a mistake you want to recover (which might wipe out dozens or hundreds of hours of work).

If something firmer than 'reversible deletion' is desired, you could add a second type of deletion (that only admins, not authors, can carry out on request).

**Comment by metasj** [comment]
Include deletion of pages as well as of whole communities.

**Comment by metasj** [comment]
Highlighting this again: I just now found my first case of practical linkrot: I had a link to a kfg pub (I didn't bother to include metadata like title, author, date in my note) which is now dead, w/ no forwarding address.   It's entirely possible that it was deleted and recreated somewhere else (in another community? merged?), but I won't be able to find it this way.

Is there any way to recover context?  Private pubs wouldn't be archived by any web archiver, either.

**Comment by gabestein** [comment]
Closing as duplicate in favor of the linked roadmap issue #2509
