### ISSUE TITLE
Spike: Propose New V6 Endpoints

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2840]
- Request firebase token / firebase auth
- Get endpoints for Collections
- Get endpoints for Pub attributions

**Comment by tefkah** [comment]
Here the link to the routes proposal: https://gist.github.com/tefkah/10441040d070fb8efc71051b897bbe08

@3mcd  @qweliant

**Comment by tefkah** [comment]
@3mcd Agreed with this proposal, but recommended (and i agreed) that the endpoint for firebase be split into a full import endpoint, and one that accepts ProseMirror steps.

this minimizes the amount of data that gets sent over the wire, and allows people to basically do arbitrary operations on pub docs.
