### ISSUE TITLE
discussions (anchored comments) disappeared from the main text 

### ISSUE THREAD

**Issue by molotro** [pubpub/pubpub#2848]
### Discussed in https://github.com/pubpub/pubpub/discussions/2845

<div type='discussions-op-text'>

<sup>Originally posted by **molotro** September 21, 2023</sup>
We were editing a document, suddenly all the discussions (visible anchored comments) disappeared from the main text. They are still at the bottom of the page, but they are no more visibile in the text. If we add a new discussion it is visibile in the text, but all the old discussion are not visibile. We don't find any "show/hide discussion" button or similar. Does anyone know what may have happened? </div>

**Comment by gabestein** [comment]
Closing this in favor of the discussion because it is posted in multiple places.
