### ISSUE TITLE
Links should open in new tab

### ISSUE THREAD

**Issue by theghostofmaya** [pubpub/pubpub#293]
When I read articles on PubPub and click on something cited, it takes me completely out of the article to the new page. I usually end up closing out of it and then realizing I accidentally closed out my path back to the article too. It's frustrating. 

Of course other people might use it differently, but for me a nice feature would be links defaulting to opening in a new window/tab.

**Comment by isTravis** [comment]
Thanks for posting this issue. We find that opening links in the same tab is the preferred default behavior.

One argument that guides this decision is that automatically opening in a new tab takes control away from the user. The user can force a link to open a new tab with a Command+click, Ctrl+click, or a right click. However, if we force links to open new tabs, there is no way for a user to dictate that they want the link to open within the same tab.

There are some arguments that internal links should open in the same and external links should open in new tabs, but I feel more swayed by the user-control argument.
