### ISSUE TITLE
analytics: set up analytics endpoint as an AWS lambda instead of on our server

### ISSUE THREAD

**Issue by tefkah** [pubpub/pubpub#2997]
### What?

Set up a repo for a very simple analytics endpoint that receives track events from `use-analytics` and sends them through to Stitch.

### Why?

- We need a server side solution as otherwise anyone could send any data to Stitch, and since stitch just takes any json payload and flattens it to create columns in the redshift table, it would be bad to have the client send tracking payloads directly to stitch.
- Better to host this thing on a lambda since the analytics could be a somewhat large source of traffic, kind of wasteful.
- Lambda could possibly be reused by v7

### Initial estimate

1 - 2 days

### Extra Work
- Add tests for API

### Implementation checklist

- [ ] lambda validates data in some way, otherwise we have the same problem as before where any data could get sent to Stitch/redshift
- [ ] lambda only sends over a one layer deep json payload, not nested ones, as this creates ugly columns.

## Issue Readiness

Not ready, needs to be determined whether a lambda is really necessary and what the best way to share validation schemes between the lambda and v6 would be.

**Comment by gabestein** [comment]
What's left: change endpoint that plugin sends to to lambda
