### ISSUE TITLE
Page flicker/loading blank page on pubpub & pub settings

### ISSUE THREAD

**Issue by sheishistoric** [pubpub/pubpub#3050]
### What went wrong, step-by-step?

1. User wanted to edit pub settings
2. User opened pub settings 
3. Page started to load before turning to white.

Also occurred when trying to load pubpub.org homepage. 

### What did you expect to happen?
Pub settings would open, page would load 

### What URL can we use to see the issue?
Currently visible on https://www.duqduq.org/. 

### What browser/operating system were you using?
Confirmed in Firefox, Safari, Chrome, and Microsoft Edge

## Optional
Related to https://github.com/pubpub/pubpub/pull/3049

### Who reported this? (If not you)
Reported by CrimRxiv, confirmed by me.

**Comment by gabestein** [comment]
FYI — I rolled back to the prior PR, which resolved the issue.

**Comment by tefkah** [comment]
Thank! i was wondering why i couldn't reproduce this, just ran into it myself as well, will look into it.

**Comment by gabestein** [comment]
Thanks! It's reproducible currently on duqduq.
