### ISSUE TITLE
Issue menu displaying duplicate pubs

### ISSUE THREAD

**Issue by sheishistoric** [pubpub/pubpub#3084]
### What went wrong, step-by-step?

1. User wants to view all pubs in an issue
2. User selects drop down menu from the issue title
3. Issue has two pubs, but menu displays the links twice.

### What did you expect to happen?
Only the two pubs in the issue should appear.

### What URL can we use to see the issue?
https://research.arcadiascience.com/pub/open-question-measuring-reuse/release/1

### What browser/operating system were you using?
Firefox & Chrome (Mac)

## Optional
Limited to the two pubs in this specific collection, but nothing stands out tag- or collection-wise to cause this.

### Have any screenshots? 
![Screenshot 2024-05-06 at 5 32 04 PM](https://github.com/pubpub/pubpub/assets/8959416/1b3ffc6b-be39-4d54-aa68-3076fa941960)

### Who reported this? (If not you)
Megan/Arcadia

**Comment by tefkah** [comment]
I think I have a good idea of why this happens!
