### ISSUE TITLE
Draft timing out upon opening

### ISSUE THREAD

**Issue by sheishistoric** [pubpub/pubpub#3105]
### What went wrong, step-by-step?

1. User selected "Go to Pub" from the pub dashboard. 
2. New tab received "Application Error". 

### What did you expect to happen?
Draft should load

### What URL can we use to see the issue?
https://emergencies.pubpub.org/pub/in-humanitarian-emergencies/draft

### What browser/operating system were you using?
Firefox//Chrome 

## Optional
Returns a 503 error

### Who reported this? (If not you)
https://emergencies.pubpub.org//Salesforce

**Comment by sheishistoric** [comment]
Happening here as well -- https://harperlab.pubpub.org/pub/nlrp3/release/1

**Comment by sheishistoric** [comment]
and this one: https://homeworld.pubpub.org/pub/aqueous-solvents/release/3

**Comment by gabestein** [comment]
Closing for now. These were due to changes to the Crossref API partially addressed in #3108. We'll have more fixes to come, but for now these pubs are loading again.
