### ISSUE TITLE
PubPub editor not loading current form / database connection error?

### ISSUE THREAD

**Issue by phoenfrisur** [pubpub/pubpub#3122]
### What went wrong, step-by-step?

We have some trouble saving our Pubs, connection to the PubPub Server seems to be the problem. This "verifyCustomToken"/"returnSecureToken" responded

```json
{
  "error": {
    "code": 400,
    "message": "INVALID_CUSTOM_TOKEN",
    "errors": [
      {
        "message": "INVALID_CUSTOM_TOKEN",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

### What browser/operating system were you using?

Google Chrome, Firefox

### Have any screenshots? (Attach them by dragging the image here)

Screenshots are taken from Chrome.

![pubpub-error](https://github.com/pubpub/pubpub/assets/110530511/3615d181-b9e7-426d-815d-dcecf9895e90)

![pubpub-error-2](https://github.com/pubpub/pubpub/assets/110530511/f3711a9d-2991-4ae3-8c3e-88bd65c32ec2)

**Comment by sheishistoric** [comment]
Closed after communicating on Salesforce (disabling extensions worked successfully!): 

> We aren't able to reproduce the issue on our end, which usually means it is something specific to your environment. Have you already tried these steps:
> 
> - Log out/log back in of your account
> - Hard refresh of the pub in your browser
> - Disable all browser extensions (particularly ad blockers can interfere with pubs loading)
