### ISSUE TITLE
Pub pages permanently "connecting"

### ISSUE THREAD

**Issue by TheConnectedCorpus** [pubpub/pubpub#3152]
### What went wrong, step-by-step?

1. I opened a draft of my page
2. The page's status showed as "Connecting" (Yellow) and never changed to "Connected" (Green)
3. Comments in this draft do not show up in the body of the page, only at the bottom in a list. (My project is an annotated text: comments are linked to specific lines and passages.)
4. When I added to this draft, the work did not save. Refreshing the page lost the work.
5. I've waited over a week for the issue to resolve itself and it has not.

### What URL can we use to see the issue? At least these, though other pages might also have the same issue:

https://theconnectedcorpus.pubpub.org/pub/bv4g48tx/draft

https://theconnectedcorpus.pubpub.org/pub/evuxi9f3/draft

https://theconnectedcorpus.pubpub.org/pub/uiyljukq/draft

https://theconnectedcorpus.pubpub.org/pub/xrhfkclz/draft

### Have any screenshots? (Attach them by dragging the image here)
![Image 8-21-24 at 2 48 PM](https://github.com/user-attachments/assets/92fb5677-774c-4762-b50f-9d92abf6e860)

**Comment by sheishistoric** [comment]
Thanks for bringing this to our attention! I performed a cache reset and both the draft and comments for each of these pubs seems to be loading properly now in different browsers. Make sure to close any open tabs of these pubs and reload to restore the current version. Let us know if you continue to encounter issues or if this solution addressed the bug.

**Comment by TheConnectedCorpus** [comment]
Hi there,

Thanks for this! Unfortunately, the problem is persisting on my end: the pages are stuck in “connecting” status and I can’t see the comments in the body of the page. Is there something else you could try?

Thanks again for your help –

Christiana

From: Emily Esten ***@***.***>
Date: Thursday, August 22, 2024 at 9:56 AM
To: pubpub/pubpub ***@***.***>
Cc: Olfert, Christiana M. ***@***.***>, Author ***@***.***>
Subject: Re: [pubpub/pubpub] Pub pages permanently "connecting" (Issue #3152)

Thanks for bringing this to our attention! I performed a cache reset and both the draft and comments for each of these pubs seems to be loading properly now in different browsers. Make sure to close any open tabs of these pubs and reload to restore the current version. Let us know if you continue to encounter issues or if this solution addressed the bug.

**Comment by TheConnectedCorpus** [comment]
Hi again,

In fact, the problem is not only persistent … it’s now occurring on all the pages I’m working on drafts of (not just the few I sent in my original report).

Thanks again for your help with this --
Christiana

From: Emily Esten ***@***.***>
Date: Thursday, August 22, 2024 at 9:56 AM
To: pubpub/pubpub ***@***.***>
Cc: Olfert, Christiana M. ***@***.***>, Author ***@***.***>
Subject: Re: [pubpub/pubpub] Pub pages permanently "connecting" (Issue #3152)

Thanks for bringing this to our attention! I performed a cache reset and both the draft and comments for each of these pubs seems to be loading properly now in different browsers. Make sure to close any open tabs of these pubs and reload to restore the current version. Let us know if you continue to encounter issues or if this solution addressed the bug.

**Comment by sheishistoric** [comment]
Okay, thanks! I notice the cache doesn't seem to stay cleared for long on our end either.

Does [this link](https://theconnectedcorpus.pubpub.org/pub/uiyljukq/draft?breakCache=1721142562) connect properly for you?

**Comment by TheConnectedCorpus** [comment]
Thanks, Emily! Yes, that link connects.

From: Emily Esten ***@***.***>
Date: Thursday, August 22, 2024 at 1:28 PM
To: pubpub/pubpub ***@***.***>
Cc: Olfert, Christiana M. ***@***.***>, Author ***@***.***>
Subject: Re: [pubpub/pubpub] Pub pages permanently "connecting" (Issue #3152)

Okay, thanks! I notice the cache doesn't seem to stay cleared for long on our end either.

Does this link<https://theconnectedcorpus.pubpub.org/pub/uiyljukq/draft?breakCache=1721142562> connect properly for you?

**Comment by sheishistoric** [comment]
Okay, great - that's a good sign. We may need to investigate further. In the meantime, here are a few steps you should take:
- Log out of PubPub
- Completely close and reopen your browser.
- Log into PubPub and return to your community.
- If you encounter a pub that's not connecting, add the following text to the end of the pub URL and refresh: `breakCache=1721142562` 

That should take care of the issue in the short-term for you to edit pubs. Be careful to not have too many active tabs open with drafts as well.
