### ISSUE TITLE
Nav Bar: Dropdown Menu Accessibility

### ISSUE THREAD

**Issue by smendez92** [pubpub/pubpub#322]
Dropdown menus are not accessible via keyboard, seemingly because the trigger button isn't a button/link or a span that can be accessed via tab key.

Dropdown menu components do not appear to have aria-labels.

See [W3 tutorial on flyout menus](https://www.w3.org/WAI/tutorials/menus/flyout/)

**Comment by idreyn** [comment]
Resolved by #582.
