### ISSUE TITLE
Footnotes Accessibility

### ISSUE THREAD

**Issue by smendez92** [pubpub/pubpub#323]
There's no context for the footnotes list at the end of articles. The editor could automatically include a Heading 2 element to demarcate the section within the html structure.

When using a screenreader, there's also no indication of what the superscript numbers are in the body of the text. They could be turned into anchor elements that link to the associated footnote at the bottom of the page. However, this would also make it hard to get back to the spot in the body of the text where the footnote first appears. Alternatively, the tooltip that currently pops up could be made keyboard accessible.

**Comment by gabestein** [comment]
We've done a fair amount of accessibility auditing, which includes a default structured view of footnotes that should all be keyboard accessible (and searchable!). This should resolve this issue. If it doesn't, feel free to re-open and let us know.
