### ISSUE TITLE
Banner images look downsampled

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#328]
It's nice to have high-res banners.  When uploading a banner I expect the resolution to be preserved, and there is no warning that the image for a banner block will be limited to some max resolution.  However high-resolution images seem downsampled, to a resolution that doesn't look especially good.   

Is the full-res image stored?

**Comment by gabestein** [comment]
We've recently partially resolved this in #1162 and #1257 and are now working on implementing srcsets site-wide!
