### ISSUE TITLE
Default JODS layout too small on OS X/Chrome

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#330]
[http://jods.mitpress.mit.edu](http://jods.mitpress.mit.edu) defaults to a mobile layout on Chrome 73 on Mac OS High Sierra & El Capitan.
This is probably not intended, and too small to be legible.

**Comment by metasj** [comment]
<img width="1051" alt="jods-mobile-bug" src="https://user-images.githubusercontent.com/1615548/56099288-d6ba6f00-5ed8-11e9-840b-2d1ca3b6a2fa.png">

**Comment by gabestein** [comment]
Is this still an issue? We've been unable to reproduce, and I think we chatted in-person about it potentially being a zoom issue.

**Comment by isTravis** [comment]
It is not. We found it was a local browser zoom-setting issue. Apologies for not closing sooner.
