### ISSUE TITLE
Broken links on the pubpub site

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#335]
Fix broken link to https://frankenbook.org on main page (make https work or change link)

Fix this broken Cursor link: https://cursor.pubpub.org/pub/cursor-editorial-manifesto

**Comment by isTravis** [comment]
Thanks for these. Fixes have been pushed up for both. 

The cursor bug is a bug in [citation.js](https://github.com/citation-js/citation-js). I've filed an [issue here](https://github.com/citation-js/citation-js/issues/35), but in the meantime have pushed up a temporary fix that will let the page load.

**Comment by metasj** [comment]
It was luck of the demo!  That was a random sampling from what people asked about during member week.  We should run a linter to catch these automatically (links on the main pages, on the front page of top pubs).
