### ISSUE TITLE
Support opening links in new tabs

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#337]
Some of the tabs/links in pubpub (like creating a new pub) are JS that don't support shortcuts for opening them in a new tab.  This makes some standard browser workflows harder.  
As an editor, I sometimes want to make many new pubs at once, and switch among them.

**Comment by metasj** [comment]
Bumping this: introducing new people to pubpub over the weekend, two examples:
* Newbies wanted to create pubs in a new page
* I would be looking at something in a community (showing someone how it works), and want to clone that tab to create a pub.  No easy way to do that: have to open some other non-js link within that community and then select 'New pub' from the new page.

**Comment by pcuellar** [comment]
Wanting to add to this. I created a community for a compendium on an ACM conference and folks have asked for this functionality. Currently, there doesn't seem to be way to make a link open on a new tab or to html-edit text on a pub to make this happen.

**Comment by gabestein** [comment]
Currently in progress! Closing as dupe in favor of linked roadmap issue https://github.com/pubpub/roadmap-repo/issues/4
