### ISSUE TITLE
Saving pub details doesn't work as expected

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#342]
As an admin, in the popup interface for adding details about a pub: if you enter data in one tab (like Details) but don't save it, and move to another tab, your changes are lost without a warning.  Some changes in some tabs save automatically, others require a button press.  

Expected behavior: Uniform auto- or button-save default; progress saved across tabs; reminder before closing that interface to save (if not automatic).

**Comment by gabestein** [comment]
This is addressed in V6, which now have distinct pages rather than popover tabs.
