### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#349]
Needs to be broken down into an MVP version.

https://kfg.mit.edu/pub/y0fobcjj/draft

**Comment by isTravis** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Build GDPR compliance summary page #387](https://github.com/pubpub/pubpub/issues/387)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9285389) | Cycle 10 | gabestein | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by gabestein** [comment]
We've mostly completed this, save for a writeup of our GDPR policies, so I am closing this for now (leaving open the summary page task).
