### ISSUE TITLE
HDSR

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#353]

**Comment by isTravis** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [GDPR Compliance #349](https://github.com/pubpub/pubpub/issues/349)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9114295) | N/A | N/A | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues
