### ISSUE TITLE
V6

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#354]
https://discourse.knowledgefutures.org/t/whats-left-for-v6/126

**Comment by isTravis** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Saving doesn't seem to go through; dupes easy; needs confirmation dialogue #338](https://github.com/pubpub/pubpub/issues/338)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9114302) | N/A | N/A | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues
