### ISSUE TITLE
Complex Imports

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#355]
Needs to be broken down into an achievable spec for supporting the needs of ALIFE and other communities.

First pass: https://kfg.mit.edu/pub/a4w1refa/draft

**Comment by isTravis** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Feature: Wordpress import #125](https://github.com/pubpub/pubpub/issues/125)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9114322) | N/A | N/A | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by gabestein** [comment]
I'm closing this for now, since we're kinda retiring epics and we did a lot of the initial work here.

**Comment by writingpoli** [comment]
Is there a plugin or other fix for this?

**Comment by gabestein** [comment]
Hello! We're actually actively working on this now in #844. It won't be direct support for wordpress yet, but we should have a way to do it this week. Write in to help at pubpub dot org if you need to import from wordpress.
