### ISSUE TITLE
Discussion designs

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#357]
https://www.figma.com/file/D0V2YxOUhgSqYgyhfnVKYMpp/Discussions_Design_DJ?node-id=0%3A1&viewport=134%2C382%2C0.15088163316249847

**Comment by isTravis** [comment]
These designs have been implemented as of 6115e6b31a87b2c071ecba2c372bf20509c32cfa.

<img width="1129" alt="Screen Shot 2019-06-12 at 8 14 14 AM" src="https://user-images.githubusercontent.com/1000455/59350453-18557380-8cea-11e9-890d-731b60946140.png">


There are a few edge-cases to handle that I will make new issues for.
