### ISSUE TITLE
Custom header/landing features for HDSR

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#361]

**Comment by isTravis** [comment]
The bulk of these needed features (i.e. Pub Header customizations) land in 288732b0822b4605430dc2cdd533722885207d8d.

![Screen Shot 2019-06-04 at 3 08 12 PM](https://user-images.githubusercontent.com/1000455/58906747-98704d80-86da-11e9-928f-7b00dc0aa134.png)

We may want to make a separate issue for custom Landing page Blocks at some point - but for the sake of this issue and deadline, that is out of scope.
