### ISSUE TITLE
Add collection-level DOI information to citationJS output

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#366]
What it say on the tin — this is a quick change, but something I overlooked when getting Collections out the door.

**Comment by gabestein** [comment]
Did we end up addressing this ever?

**Comment by idreyn** [comment]
IIRC we determined that there's no field in the CitationJS model (or any of its outputs like Bibtex) that captures the notion of "DOI of parent collection", so we put it on hold for now.

**Comment by gabestein** [comment]
Oh right, I remember this now as part of the conversation of adding the booktitle. Moving out of the cycle.

**Comment by gabestein** [comment]
In further research, it doesn't appear that this is possible or desired. Closing out.
