### ISSUE TITLE
Rewrite PubSyncManager

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#370]
The PubSyncManager component:

- Is beginning to become a catch-all place to store local editor state which should be more carefully structured
- Could probably be refactored into a set of hooks(?) that would make it more ergonomic

At any rate, I'd like to take a crack at making this nicer.

**Comment by gabestein** [comment]
@idreyn Did we do this as part of the recent stability re-writes?

**Comment by idreyn** [comment]
No, we didn't. As it stands, this issue is still a good representation of a thing we want to do soonish, as it's where a lot of the remaining editor performance bottlenecks live.

**Comment by gabestein** [comment]
Time for my ... yearly-ish check. Was this addressed at all as part of the release stuff, or is this still something causing bottlenecks?

**Comment by idreyn** [comment]
The component is still a bit of an abomination but it is no longer responsible for these bottlenecks so I'm going to close this issue. We'll continue breaking its functionality into smaller bits until it no longer does anything useful and we can remove it.
