### ISSUE TITLE
Signup button disabled on Internet Explorer

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#375]
**Who reported**
Anna / RTI

**Browser & Operating System (if required)**
Windows TK
Internet Explorer TK

**Plain-language description**
The user was unable to signup because the signup button was disabled, even when they typed in their email.

**What the user expected**
The signup button to be enabled.

**Steps to reproduce**
1. Visit https://pubpub.org/signup on IE TK
2. Type in email

**Screenshots**
![iebug](https://user-images.githubusercontent.com/639110/58718152-edd6f280-839a-11e9-810e-119052bc1b39.jpg)

**Comment by gabestein** [comment]
Note: I'm not sure we want to support IE. But worth logging, since we will have a certain number of users on it.

**Comment by isTravis** [comment]
I've seen a similar issue before, where form-autofillers don't properly trigger React onChange events. Can we confirm this happens in IE even when the email address is manually typed in?

It doesn't look like there is a 1Password or similar extension (does IE even support extensions?) - but worth a sanity check first perhaps.

**Comment by gabestein** [comment]
Yup, I'll ask to confirm that this was an issue with manual typing in.

**Comment by gabestein** [comment]
We've gotten confirmation from a few folks on < IE 11 that this is an issue, and I suspect it's a problem with React onChange, as you said. My preferred solution is to warn on < IE 11, rather than solve for that small percentage.

**Comment by gabestein** [comment]
We've decided not to support IE < 11. We should probably warn about incompatibility, but that's a separate issue.
