### ISSUE TITLE
On resetting a password, a mistaken error message appears

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#377]
Reported: SJ

Browser: Win/Chrome  

Description:  On resetting a password, I was automaticlaly logged in, and saw my user icon in the far upper-right.  But got the attached error message in the main browser window.  Ignoring its suggestion and reloading worked.

![password-reset-bg](https://user-images.githubusercontent.com/1615548/58732430-7d8e9800-83bf-11e9-8fb2-795abf573f78.JPG)

**Comment by gabestein** [comment]
I'm unable to reproduce, and password reset code was recently refactored and tested for V6. If you encounter the issue again, feel free to re-open.
