### ISSUE TITLE
Update export task to cache branch versions by Prosemirror history key

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#378]
The pub export feature is time consuming and computationally expensive. To avoid calling it repeatedly on the same pub version, v5 would cache a reference to the resulting file's URL in the `Pub.downloads` database column. There are two issues with that approach:

- In v6, we need to cache downloads by `(branchId, historyKey)`, since a branch by a given ID could have its contents change in the future.

- The v5 code would try calling the `/api/pub` route to update the `Pub.downloads` info, which would only work if the user performing the export was a pub manager. We want to move this logic to the client side so that the download gets cached regardless of who initiates it.

In the meantime, I've disabled the download caching altogether.

**Comment by gabestein** [comment]
Looks like this was resolved in #379?

**Comment by idreyn** [comment]
Ah, no — I created this task as a side effect of working on #379.

**Comment by gabestein** [comment]
Done in #636!
