### ISSUE TITLE
Journal curation pub link goes to Not Authorized page

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#38]
On the journal admin curation page under the "Submitted Pubs" column, the links to each pub go to a draft version of the pub with a URL such as http://example.com/pub/pub-title/draft. This page says just says "Not Authorized" when logged in as the journal admin. The link should probably not include the draft portion so that the article can be viewed before featuring.

**Comment by devinberg** [comment]
Just noticed the same is true for pub links in the "Featured Pubs" column.

**Comment by isTravis** [comment]
Fixed with cd31d48a2aaf0215d034cc1da934688a7771f340. Needed to include history in pub autocompletes and populate since we check history length to automatically route to /draft if there are no saved versions.
