### ISSUE TITLE
Investigate collections-related regressions in v6

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#380]
When I visit the collection editor on v6 (e.g. [here](https://v6.pubpub.org/dashboard/collections/9f72a7b6-966c-4d1c-b2f1-f2714ac82dd2)) I see a few problems:

- The "saving" spinner is present when it should be hidden
- The list of pubs doesn't scroll correctly, and overflows its bounding box instead.

Neither of these issues are present in prod. Just making this task to remind me to go see what's up.

**Comment by gabestein** [comment]
I'm unable to reproduce, and HDSR collections seemed to work fine. Is this still an issue?

**Comment by idreyn** [comment]
Yep, these got fixed a while ago, by the by. Seems okay to close.
