### ISSUE TITLE
Formatting bar input fields don't update when switching between same-typed nodes

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#381]
**Who reported**
Rhys (and Travis, Ian back in March)

**Browser & Operating System (if required)**
All

**Plain-language description**
When using the `FormattingBar` component (e.g on PubBody, Page TextBlock, etc), moving your selection from one Node with a given NodeType to another Node with the same NodeType does not properly update input fields (e.g. captions).

**What the user expected**
When selecting new Nodes, the input fields should show the proper associated metadata (e.g. caption)

**Steps to reproduce**
1) Create a document with two images and give them separate captions.
2) Click on one image, and then click on the other. 
3) The caption field will still have the content of the first-clicked image, rather than the second.

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/1000455/58980664-dd5db800-879e-11e9-8fe3-5fcb807f3a59.png)

This was previously addressed in #310, but that solution does not seem to work on Pages (in Rhys's case) or in v6.

**Comment by gabestein** [comment]
Addressed in #673
