### ISSUE TITLE
Allow citation journal titles to be different from issue collection titles

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#382]
**Who requested**
jpooley / discourse

**Stories**
- As a community admin, I want to set the journal title as distinct from the collection title, so I can cite volumes within a collection properly.

**Implementation Notes & Context**
"I am proposing a Collections-level setting, either in the “Metadata” or “Details” pane, that allows for citation-specific collection title override. I might, for example, want my collection to be called “Volume 1” but want the citation title to appear as “Journal of Applied Neurochemistry”."

**Technical Specification**

_To be completed by the Engineering team/broken into sub-cards as needed."_

**Mockups or reference images**

**Comment by gabestein** [comment]
I think our plan had been to use the community title as the journal title for journal issues (and eventually conference series and book series/sets). The title of the issue itself is largely internal (and maybe could be auto-generated), as volume/issue numbers are what's supported by CSL/crossref/etc.

**Comment by idreyn** [comment]
In the end, we decided that:
- No changes are needed for Crossref deposits
- When a collection is an Issue, we'll use the community name as the `container-title` that shows up in the citations generated by CitationJS. For Books and Conferences, we'll continue to use the collection title.

I made this small change in 2e2b5635.
