### ISSUE TITLE
Include community title or primary collection title in page title

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#385]
**Who requested**
https://twitter.com/judell/status/1136381509932240896

**Stories**
- As a scraper (spider, annotation tool, etc.), I want the community or collection title to appear in the page title, so I can give more context to users about what collection the pub belongs in.

**Implementation Notes & Context**
- For example, [this pub](https://bookbook.pubpub.org/pub/926svib6) just says `Chapter 1` in the title. There's no way to know what community or collection the Pub is in just from looking at it. This has implications for SEO, for social sharing, annotation tools, and for users looking for Pubs in browser tabs.
- There are probably other places we need to provide this, such as RSS feeds.

**Technical Specification**
- If the pub has a primary collection set that's not a journal, use the title of that collection; else, use the title of the community.

**Mockups or reference images**

**Comment by judell** [comment]
Hi Gabe, we meet again!

From a Hypothesis perspective (but also broadly relevant) a critical thing would be to include a work-specific ID in the URL.

Thanks for picking up on this.

**Comment by gabestein** [comment]
👋 again.

Thanks, that's really helpful. Does the pub slug at the end of the url work as a unique id? Right now it can be overridden with a pretty permalink, but we're ultimately planning to move to a world where that slug is always in the url.

ie: [https://bookbook.pubpub.org/pub/**926svib6**](https://bookbook.pubpub.org/pub/926svib6)

**Comment by judell** [comment]
That appears to be a per-chapter ID. If you're Remi, and you want to review all the annotations on your book, you'd need to do a per-chapter search. You'd rather do a book-wide search to find annotations on all chapters.

**Comment by xolotl** [comment]
Also, if that ID ever changes (eg, versioning?), it would be good to think through how annotations would aggregate around/despite those changes.

**Comment by gabestein** [comment]
> That appears to be a per-chapter ID. If you're Remi, and you want to review all the annotations on your book, you'd need to do a per-chapter search. You'd rather do a book-wide search to find annotations on all chapters.

Ah, I see, thanks. I'm not sure exactly how we'll approach that, but worth thinking about -- potentially we could append an id for the collection to the URL. We'll add it to the hopper.

> Also, if that ID ever changes (eg, versioning?), it would be good to think through how annotations would aggregate around/despite those changes.

Yeah, that's gonna be a challenge for sure. For crossref and other linking purposes, we've always wanted to have a single, unchanging ID/URL that represents the current 'canonical' or 'stable' public version of the work, while also supporting multiple versions with their own unique, citable URLs (that we deposit as linked components). 

We're about to launch a new version of PubPub that will take this further -- it will allow authors to create distinct branches for different working versions of the document, and also allow authors to potentially create unique URLs for every change to the document in its history. And all of it will roll up to a single pub ID with something like: `pub/{pubId}/branch/{branchId}/history/{historyID}`.

So in that case, I think most people will annotate the base (`pub/{pubId}`), which should work the same as any other document when the contents change. If you want to annotate only a specific branch, that'll also be possible (`pub/{pubId}/branch/{branchId}`). And you could even annotate a specific moment in the document history (`pub/{pubId}/branch/{branchId}/history/{historyId}`).

To be honest, I'm not familiar enough with Hypothesis/web annotation architecture to know if that structure would be sufficient to search for annotations across different versions of the document, but we'd certainly be open to hearing about ideas for making that possible.

**Comment by judell** [comment]
I don't think the point I'm making is necessarily related to annotation. There are lots of reasons why it's useful to make URLs, and/or page metadata, that identify both whole works and parts of works.

It seems to me that in  `pub/{pubId}`, the `{pubId}` is a chapter-like unit. 
 
Nothing in `https://bookbook.pubpub.org/pub/926svib6`  (or its page metadata) says it's a chapter of Annotation, just as nothing in `https://bookbook.pubpub.org/pub/zrlj0jqb` (or its page metadata) says it is a chapter of Data Feminism.

**Comment by gabestein** [comment]
Gotcha, understood, and thank you for sticking with me. At minimum, I agree we should put the title of an associated work in the page title (ie `Chapter 1 | Annotation`), for SEO, bookmarking and all the other things that make use of page titles.

Referencing the work in the URL probably isn't going to happen unless it's absolutely required for annotations to work (hence why I'm focusing on that piece), since we don't have strict collection -> item hierarchies in PubPub. `{pubId}` isn't always a chapter, so we can't always say it belongs to a higher collection (and often it belongs to more than one).

So, I guess the ask would be: if there are other places we should consider putting an identifier for the work in page metadata in addition to the page title that would make annotations (or the general experience better), let us know!

**Comment by judell** [comment]
There are several possibilities for page metadata. DOI is one, if you wish to mint a DOI per work. Another is the `dc.identifier`/`dc.relation.ispartof` described here:  https://web.hypothes.is/help/how-hypothesis-interacts-with-document-metadata/#what-happens-when-urls-change.

**Comment by gabestein** [comment]
Perfect, thank you, that's exactly what I was looking for. We don't implement Dublin Core (yet), but we can definitely do that pairing.

(We do allow users to mint DOIs, but it's not universal.)

**Comment by xolotl** [comment]
In an ideal world, the latest/best version of a publication would always be available at a stable, canonical location (as @gabestein suggests), AND publishers would have granular control over the annotations that aggregate on that location.

Thus, if there were annotations on versions 0, 1, 2... of a work, readers would always be able to visit specific versions in the history that would still carry the annotations made/published with that version AND publishers would be able to make granular choices about whether the annotations on each version would also appear on the next version.

Likely easier to describe than to support ;)
