### ISSUE TITLE
Opt users out of all cookies that are not "strictly necessary" by default

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#390]
See "Cookie Compliance," here: https://gdpr.eu/cookies/

From what I can tell, our strictly necessary cookies are the ones we use for login. By default in a new session, we appear to be dropping two that probably do not meet the definition: `keen`, and probably `__cfduid` (although I'm not sure what this does).

These should not be dropped until a user consents to them.

**Comment by isTravis** [comment]
_cfduid is a Cloudflare cookie that [seems to be exempt from GDPR](https://community.cloudflare.com/t/disable-cfduid-cookie-for-eu-law-compliance/19323)
