### ISSUE TITLE
"Edit Landing Page Design" button leads to Not Authorized

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#40]
Logged in as journal admin. On the design page there is a "Edit Landing Page Design" button. Clicking it leads to a Not Authorized page.

**Comment by isTravis** [comment]
Seems like the bug is that only the _first_ admin listed is successfully authorized. I've always been first admin on the journals I tested so never noticed this... Sorry about that. Looking into fixing it right now.

**Comment by isTravis** [comment]
Fixed with 68ffdba.
