### ISSUE TITLE
Special treatment for Abstract headers

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#414]
**Who requested**
eng team

**Stories**
- As an author, I want to add abstracts to my papers, so I can conform to academic standards.

**Implementation Notes & Context**

As discussed: adding an H1 to the top of the Pub body called `Abstract` (and we should eventually support other languages) will cause it to get different styling.

In the future, it will be parsed and deposited/put in other metadata ie DC tags.

**Technical Specification**

For now, this can be pure CSS. In the future, we'll want to parse this out of firebase and store on a per-branch level for depositing, metadata, etc.

**Mockups or reference images**

**Comment by isTravis** [comment]
Implemented with minimal styling 9846166f3e62b5bb47cfda532e106a609827af53. Happy to have Deepak or others reopen to make styling requests.

![Screen Shot 2019-06-13 at 3.12.48 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/66570108-a105-406b-9914-71fc514f3cf4/Screen+Shot+2019-06-13+at+3.12.48+PM.png)

**Comment by castedo** [comment]
@isTravis @gabestein I've just started trying out for the first time this very cool system y'all have created. Here is a small bit of my user experience that could be improved, in case y'all want to add a new discoverability feature.

The way to add an abstract could be more discoverable. After failing to see how to add an abstract, I briefly assume PubPub does not support abstracts. My first intuition is that some UX element under the title would let me add/edit an abstract. I first edited the "Description" box under the title which seemed like that might be an abstract. In the end I found out how do this this by searching these github issues and found this closed issue.

**Comment by gabestein** [comment]
Thanks for taking it for a spin! I agree Abstracts need to be more discoverable. Under the hood, the issue is that the editor (based in Prosemirror) doesn't have any semantic understanding of abstracts (or anything else beyond what's built into HTML) at all. So, we're just using CSS and then when we need to extract the abstract for another purposes, querying for the content directly below the first H1 if it has the id "abstract".

Given that, my sense is we'll lean more on the rough concept of "[semantic boxes](https://github.com/pubpub/pubpub/issues/2000)" to enable better abstract discoverability (and just support -- right now we only support single-paragraph abstracts!) as well as support for other fields that have no semantic meaning in HTML, but do in other academic contexts, such as data discoverability statements.
