### ISSUE TITLE
Expandable details pane

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#416]
**Who requested**
eng team

**Stories**
- As a reader, I want quick access to article details, so I can easily learn more without being initially distracted by lots of metadata.
- As an author, I want to see the details pane in a non-distracting way, so I can edit in as close to a WYSIWYG environment as possible.

**Implementation Notes & Context**
- Collapsible bar
- When collapsed, displays DOI (if present), badges (if present), and contributor avatars (if there are more than 1).
- When opened, displays the detail view, which now includes the full list of contributors.

**Technical Specification**

_To be completed by the Engineering team/broken into sub-cards as needed."_

**Mockups or reference images**

**Comment by djagdish** [comment]
Figma workspace showing the different options for Details pane, showing collapsed and expanded views:
https://www.figma.com/file/xnAUq0gL7tjlBCHNx3Rvju/Details_pane_designs?node-id=0%3A1

**Comment by isTravis** [comment]
Functionality and initial design implemented in #424
