### ISSUE TITLE
New PubMeta with TOC, downloads, share as popovers

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#418]
**Who requested**
eng team

**Stories**
- As a reader, I want to easily share, browse article contents, and download, so I don't have to hunt for these options when I make return visits to pages.

**Implementation Notes & Context**
- TOC button in the pub meta with deepak's icon and popover like the top bar TOC
- Download button with popover, displaying default download first and prominently if available
- Share button with popover

**Technical Specification**

_To be completed by the Engineering team/broken into sub-cards as needed."_

**Mockups or reference images**

**Comment by isTravis** [comment]
Added Deepak's Table of Contents in dbc1b7b7a6cf473b2a462d64d7334932b98009e8. Can be used with `<Icon icon="toc" />`.

**Comment by isTravis** [comment]
Implemented in a handful of commits - but functionality completed by fd524b34aaabbb111c51820a46b63a5db4fbfcca.
