### ISSUE TITLE
Full and half-bleed image support

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#419]
**Who requested**
eng team

**Stories**
- As an author/editor, I want to use full- and half-bleed images, so I can create more visually interesting articles.

**Implementation Notes & Context**
- Support for everything on Travis' list (full, half-left, half-left-full, half-right, half-right-full)

**Technical Specification**
- Something about grids

**Mockups or reference images**

**Comment by isTravis** [comment]
Addressed and merged in #422
