### ISSUE TITLE
Pipeline for inviting read-only collaborators

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#43]
There is a bit of confusion with the links being sent to read-only collaborators. They are being sent to /draft even though their primary view is the pub reader. See the following message from Erika:

> Kevin wants to add me as a collaborator on this pubpub paper, but when I click the link it just says "Not Authorized" because I have read-only access. I can get to the paper and read it, but only by going to my profile and finding it under 'read only.' You should rework which link is sent in the notification email.
> 
> Also a 'request access' button would be nice!

**Comment by devinberg** [comment]
Came here to second the request for a "request access" button.

Another nice feature would be to provide a public read-only link that can be shared for non-published pubs. Overleaf handles this by providing public links that are read-only and with edit permission (no account needed to edit). This may be desirable for some situations but would probably require revision tracking (again as Overleaf uses).

**Comment by isTravis** [comment]
Request access sounds good. 
Read-only link is in the works (no account needed). 
Haven't given edit-access-without-account as much thought. Right now anyone with edit-access can save a version/publish/etc. That seems like something that should be reserved to non-anonymous users. Perhaps this is a needed feature regardless of the edit-access link idea. Perhaps only certain editors should be allowed to publish.
