### ISSUE TITLE
Community admin cannot edit/delete an empty pub

### ISSUE THREAD

**Issue by r0bis** [pubpub/pubpub#430]
**Who reported**: Roberts Klotins - community for epg.pubpub.org

**Browser & Operating System (if required)**
Chrome, Linux

**Plain-language description**
There is an empty pub from a user who no longer is active. Name is "New Pub on Nov 11", address is https://epg.pubpub.org/pub/sor1y4zv. I am community admin and I can edit/delete other pubs in the fold (https://epg.pubpub.org/dashboard/pubs), but not this. It perhaps is a bug - I was able to delete the same user's other empty pub. For this one I do not have any edit rights, nevertheless it appears in EPG community.

**What the user expected**
As a community admin I should be able to delete pubs.

**Steps to reproduce**
I notice PubPub is also one community admin with EPG community (which is perfectly fine, btw) - could you try to look into this and delete that empty pub as that would reporduce the issue or perhaps pinpoint where the glitch is. Name is "New Pub on Nov 11", address is https://epg.pubpub.org/pub/sor1y4zv.

**Screenshots**
![Screenshot from 2019-06-23 11-50-21](https://user-images.githubusercontent.com/183669/59975192-2c805700-95ad-11e9-9828-65c280f7804c.png)

**Comment by gabestein** [comment]
This has been resolved in the latest Dashboard updates (#769). Community Admins now have the ability to manage all pubs in their communities, including deletion.
