### ISSUE TITLE
Add 'recent changes'

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#435]
**Who requested**: SJ

**Stories**: As an editor, I want to see the last things I edited.  As a reader, I want to see the last pages anyone edited.

Common example for active pubs: everyone is working on X, it doesn't have a memorable short name yet, and it's hard for everyone to get to + see the same page.  

I could imagine a time-ordered list of pages by last edit time; or including last-edited as a bit of metadata that appears on the full list of Pubs, and allowing sorting by time (and reverse time) as well as by alpha.  Compare MediaWiki's [RecentChanges](https://en.wikipedia.org/wiki/Special:RecentChanges) and [Watchlist](https://en.wikipedia.org/wiki/Special:Watchlist)

**Comment by gabestein** [comment]
We did this as part of #1379!
