### ISSUE TITLE
Improve footnote and citation display

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#437]
**Who requested**
Gabe

**Stories**
- As a READER, I want footnotes and citations to display consistently and in accessible ways, so I can read them without annoyance.

**Implementation Notes & Context**
Right now there are a number of issues with the way we handle footnotes and citations. The biggest are:

1. They always display up, meaning if you hover one at the top of the page, they display off the screen (see screenshot).
2. They're not accessible. Like at all.
3. We don't handle long footnotes well.

We should re-think how we handle and display these. 

**Technical Specification**

_To be completed by the Engineering team/broken into sub-cards as needed."_

**Mockups or reference images**

<img width="1029" alt="Screen Shot 2019-06-28 at 9 00 55 AM" src="https://user-images.githubusercontent.com/639110/60344090-c405f100-9983-11e9-9871-f9724f48ab4b.png">

**Comment by gabestein** [comment]
Just one thought: now that our comments aren't inline by default, perhaps we could do them inline expanding a la Harvard Law Review?

**Comment by djagdish** [comment]
I was under the impression that we had already taken care of this design-wise last month. Related design assets can be found in **Citations_Composing&Viewing** figma file in PubPub project.

**Comment by gabestein** [comment]
yup, I think we have. We have another card for composing them.
