### ISSUE TITLE
Get pub text in markdown programmatically

### ISSUE THREAD

**Issue by r0bis** [pubpub/pubpub#443]
Roberts Klotins:

We have a project on PubPub that is a book in chapters. Possibility to download pubs is now functioning (great!), but still with some difficulty. What I want is to set up a system where I can **download chapters (i.e. pubs) programmatically** - preferably as markdown. Preferably also images and references (citations). I then could manipulate the downloads in `R/bookdown` to auto compile a good looking PDF or ePub when needed. 

I was wondering if there was some system/APIs in place to allow for this, or whether I could hack it up somehow. I have fair `bash` `html/css` and `R` skills and spme `perl` experience too.  I possibly could do a lot of this with `wget`, but I was wondering if there were a better way?

Thanks,

Roberts

**Comment by gabestein** [comment]
Hi Roberts,

Thanks for this -- just a heads up that we typically use GH for more formal feature requests (hence the template). More open-ended questions like this one are best suited to our [Discourse forum](https://discourse.knowledgefutures.org).

That said, improving exports, including bulk exporting, is on our roadmap for the fairly near-term. It'll be helpful to have this use-case in mind as we build that, and if it's ok with you, I may reach out to get your feedback as we build. If any other ideas come up, feel free to reach out (again, Discourse probably preferable unless it's a very specific request

Thanks so much!
