### ISSUE TITLE
Updated on date

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#444]
**Who requested**
Xiao-Li / HDSR

**Stories**
- As an author, I want an updated on date to appear when I update my articles, so I can communicate it is a new version.
- As a reader, I want an updated on date to appear on articles that have been updated, so I can tell the article has changed post-publication and inspect those changes if needed.

**Implementation Notes & Context**
If last updated differs from published on, show last updated on under Published on in expanded Pub details pane

**Technical Specification**

_To be completed by the Engineering team/broken into sub-cards as needed."_

**Mockups or reference images**

**Comment by isTravis** [comment]
Added by 4294e061fbc64b949a796fc4efbf480090e5e765
