### ISSUE TITLE
Real-time highlighting and cursor position showing on public branch

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#450]
**Who reported**
Gabe

**Browser & Operating System (if required)**

**Plain-language description**
See screenshot. When logged out and viewing https://jods.mitpress.mit.edu/pub/tliexqdu, I can see highlights and cursor positions of other users, all of which say anonymous.

**What the user expected**
No highlights or cursors should show (also, seems like we shouldn't be syncing this on the backend at all for bandwidth/speed/etc.

**Steps to reproduce**
1. Visit https://jods.mitpress.mit.edu/pub/tliexqdu
2. Visit https://jods.mitpress.mit.edu/pub/tliexqdu again, in an incognito window.
3. Highlight text from the incognito window.
4. See highlighted text in the first window.

**Screenshots**
<img width="1020" alt="Screen Shot 2019-07-15 at 2 00 09 PM" src="https://user-images.githubusercontent.com/639110/61239528-13327c80-a70d-11e9-8037-b100ce30e4df.png">

**Comment by isTravis** [comment]
I was wrong about this being a trickier, deep Prosemirror collaborative issue. It was actually a simple fix: ec36c2528ac4c2b37ac8086c88314e901cb31966
