### ISSUE TITLE
Fix discussion bubble overlaps on mobile

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#455]
Not sure why this is happening, but here's an example on JoDS:

![Screen Shot 2019-07-22 at 12.38.15 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/353ee548-fe22-46b2-a7ec-0068990dbd78/Screen+Shot+2019-07-22+at+12.38.15+PM.png)

**Comment by gabestein** [comment]
I'm pretty sure we fixed this as part of the release stuff, right?

**Comment by idreyn** [comment]
I think so, and I no longer see this happening on this specific pub, so I'm gonna close it.
