### ISSUE TITLE
PubPub test suite

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#464]

**Comment by isTravis** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Local firebase server with corresponding test pubs #462](https://github.com/pubpub/pubpub/issues/462)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9674900) | Cycle 11 | idreyn | Untriaged | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Local database of test data #461](https://github.com/pubpub/pubpub/issues/461)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9674899) | Cycle 11 | idreyn | Untriaged | Open
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Easy way to call Express routes for testing #460](https://github.com/pubpub/pubpub/issues/460)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/iP2k/issues/9674894) | Cycle 11 | idreyn | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by gabestein** [comment]
Closing as most of this is done and we're retiring epics.
