### ISSUE TITLE
Make the collaborative editing plugin testable, and test it

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#466]
Brain dump below:

The "collaborative editing" Prosemirror plugin is a bit of a misnomer — this piece of code handles synchronizing and persisting Pub state to Firebase whether you're collaborating with other authors or not. Most of our heavy-duty interaction with Firebase happens in this plugin, and we're interested in making it more reliable (as in #457) and legible.

We need to some combination of these things to improve the testability of the collab code:

- Create a dummy Firebase server (handled in #462 — this part is fairly straightforward)

- Break the methods of the Prosemirror plugin itself into smaller functions that can be indivdually tested, e.g. subsets of the `apply()` method that deal individually with cursors or discussions. To get really specific for a second, consider this method from the plugin:

```
receiveCollabChanges(snapshot) {
    this.mostRecentRemoteKey = Number(snapshot.key);
    const snapshotVal = snapshot.val();
    const compressedStepsJSON = snapshotVal.s;
    const clientId = snapshotVal.cId;
    const meta = snapshotVal.m;
    const newSteps = compressedStepsJSON.map((compressedStepJSON) => {
        return Step.fromJSON(this.view.state.schema, uncompressStepJSON(compressedStepJSON));
    });
    const newStepsClientIds = new Array(newSteps.length).fill(clientId);
    const trans = receiveTransaction(this.view.state, newSteps, newStepsClientIds);

    if (meta) {
        Object.keys(meta).forEach((metaKey) => {
            trans.setMeta(metaKey, meta[metaKey]);
        });
    }
    this.pluginProps.onUpdateLatestKey(this.mostRecentRemoteKey);
    return this.view.dispatch(trans);
}
```

Most of this method can be wrapped in a pure function of `Snapshot -> Transaction` that can be broken out of the class body and then unit tested.

- Find a way to wrangle Firebase ref objects so we can mediate their interactions with the server, i.e. requests are sent (or dropped) in a predictable order so we can write tests that deal with race conditions and intermittent connectivity. Maybe we can wrap them them in a Proxy, or maybe there's an in-band way to do this with the Firebase SDK.

- I think we need some way to fake timers as well (probably with sinon.js)

In the end, this leaves us with two distinct sets of tests:

- A suite of unit tests that examine the internal behavior of the collaborative plugin and test the reliability of things like loading and persisting steps.

- A suite of something that looks a little more like integration tests, where we set up multiple clients and see how they interact with a (fake) Firebase instance. There are some single-user cases, such as with out-of-order transactions and dropped steps, that can be examined here too. 

I don't want to refactor code for refactoring's sake, but I think this is one of the touchiest parts of the codebase, and given that other test infra stuff has worked itself out a little bit ahead of schedule (famous last words) this is something I want to focus most of my attention in Cycle 11. While we're testing this code I expect there will be some places where low-hanging performance improvements present themselves, and hopefully these will come out in the wash as well.

**Comment by gabestein** [comment]
@idreyn: did we do some of this recently as part of the release enhancements? I vaguely remember something along these lines.

**Comment by idreyn** [comment]
No, not really — we did something along these lines for the discussions plugin. I don't really think it's necessary to keep this issue open, though. The collaborative plugin works perfectly right now; if we did ever have to modify it, we'd write some tests, but also probably forget to reference this issue.

**Comment by idreyn** [comment]
> Create a dummy Firebase server 

Ah hm we did actually do this part!
