### ISSUE TITLE
Transition Annotations to Marks rather than Decorations

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#467]
For improved copy/paste, better location tracking, and other improvements.

![Frame 2.png](https://codetreeusercontent.s3.amazonaws.com/uploads/4991a0c8-c66e-4320-996c-f0fb14f9e4e6/Frame+2.png)

**Comment by gabestein** [comment]
@idreyn: same question, re, release enhancements. And are we still planning to do this?

**Comment by gabestein** [comment]
Closing as stale. Will get attention in https://github.com/pubpub/roadmap-repo/issues/8
