### ISSUE TITLE
iFrame support in Pub Markdown and Rich Editor

### ISSUE THREAD

**Issue by han-sh** [pubpub/pubpub#47]
**requested feature:** embedding videos (etc) from vimeo, etc., instead of uploading massive video files to pubpub.

**context:** i use pubpub to hash down thoughts, background research, etc., and think that it is excellent for that. a lot of research, interviews, etc, are well-documented in videos, which can be embedded in a pub where relevant.

**Comment by ThariqS** [comment]
This is something we're torn on because while we recognize it's way easier to upload a venmo or youtube link, we would like all data with a pub to be stored with it, so there's never a possibility of broken links. Regardless though, you can use the iframe widget and paste in the venmo or youtube URL to simulate this.

**Comment by han-sh** [comment]
in reply, i'll begin thus: history is littered with examples of those who _thought_ they could control it all—make something that stands the test of time, is eternal, and unfailing. funnily, history is _equally_ glittered with examples of each of them failing, sooner or later. 

anyone using pubpub for serious publishing will be responsible enough to ensure sufficiently permanent sources. heck, even the most rigorous of writers cite books which go out of print or are utterly impossible to find. and—i say—that's fine! people should have _the option_ for uploading content to pubpub, if they want to, and the option of embedding. unfortunately, when i try and use pubpub for my less-than-serious writings, pubpub's lack of flexibility convinces me to move off to medium or some other platform. 

if you're building purely for the uber-serious writers, then i'm certainly not your audience. but if this is, as i believe, a platform to help people improve and write more seriously, then it might be a good idea to keep things more open, connected, etc. yes, we must build robust things, but building a silo in a connected world (in the name of data- security/ownership/privacy/<insert other cool word here>, no less) might not be the wisest approach at building an audience on a fledgeling platform. 

i just find it silly to dump a 200 MB video on pubpub when vimeo and youtube are an whole empires that spend all their time trying to figure out how a video can be best presented to an audience. but hey, i might be wrong :)

**Comment by ThariqS** [comment]
Yeah there's definitely a middle ground, maybe we can automatically archive youtube links automatically, etc.

**Comment by han-sh** [comment]
uhm, sorry to sound daft: but where is the aforementioned 'iframe widget'?

**Comment by ThariqS** [comment]
Ahh, sorry! We didnt include it in the formatting bar yet, but you can type [[ and then select iframe. Working on making this more intuitive.
