### ISSUE TITLE
Footnotes - URLs and DOIs not linking & Structured Data overriding Text

### ISSUE THREAD

**Issue by sarahelizabethk2** [pubpub/pubpub#475]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. When inputting Structured Data in the form of DOIs removes any information in the Text field
2. These Structured Data inputs isn't reading all the information: E.g., footnote 2 in "Setting Context" of the Landscape report is Fitzgerald 2006, but is missing his first name or initial (Brian/B). This is an issue when the Text says "Fitzgerald, Brian 2006" but then is overriding it.
3. Including any hyperlink in the footnotes (either URLs or DOI links) don't actually hyperlink when the Footnote list is generated in the Pub itself.
4. I think this might already be a ticket, but there's no formatting in general in footnotes when text is put into the unstructured field (ie lose italics and bold).
5. An additional annoying part about adding footnotes is when you add any text into either section, the page goes back up to the top (such that if you are midway through the doc and you add a footnote, the page view will go to the very top). 
...

**What URL can we use to see the issue?**
Any Pub page (as far as I know).

**What browser/operating system were you using?**
Chrome

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by sarahelizabethk2** [comment]
This is actually also an issue for citations too, by the way!

**Comment by gabestein** [comment]
Thanks for this. We are going to be embarking on a bit of an overhaul of how we display footnotes and citations. This cycle I believe we'll be able to address 3 in #491, and possible 5. The others are somewhat larger changes to how we want to manage footnotes in the long run, but they're on our radar and we will be making improvements.

**Comment by gabestein** [comment]
Addressed in #671 and #673, which also includes the ability to add formatting to notes and citations.
