### ISSUE TITLE
Continuous refresh error message when adding footnote or citation on dev

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#476]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. Visited https://kfg.duqduq.org/pub/egfkxqjm
2. Added a citation
3. Clicked the citation [1] to edit the citation
4. Received "uh oh" popup
5. Refreshed, error popped up immediately
...

**What URL can we use to see the issue?**
https://kfg.duqduq.org/pub/egfkxqjm

**What browser/operating system were you using?**

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by isTravis** [comment]
Aha! Great. The new system working!

This looks like a bug that has been around for a long time, and was just never caught. The onError updates let us pinpoint it and now we have a simple fix here: pubpub/pubpub-editor@51f45854bf7ccd3245423f6f025548d1aba47a9f

Latest version pushed to dev has the fix.

**Comment by gabestein** [comment]
If this issue isn't in a slideshow about how making time for tech debt saves time and money by next week I'll be shocked.
