### ISSUE TITLE
featureRequest // An index/outline of a Pub for readers

### ISSUE THREAD

**Issue by han-sh** [pubpub/pubpub#48]
Since pubs are likely to be fairly long, it might be useful to have an Index or navigable outline. This is not only to help navigate _while reading_, it should also help us obtain/share links to specific sections or topics in a long piece.

This is one way such an index might be implemented (2 images: one shows how a pub-page currently looks, and the second show how it _might_ look):
![1](https://cloud.githubusercontent.com/assets/9903574/14529769/04e57194-024e-11e6-8ae1-e6fd0ad2d03b.gif)
![2](https://cloud.githubusercontent.com/assets/9903574/14529789/1f85a028-024e-11e6-809f-5cffc84b2b61.gif)

**Comment by ThariqS** [comment]
Totally a good point! We used to have a table of contents but it got hidden with the latest refactor. What do you think we should do if the outline is too long to show on the left handside without hiding other things?

**Comment by han-sh** [comment]
quick suggestion: if the outline's too long, you _may_ begin by collapsing it. there's a precedent for that: you're already collapsing the left-sidebar for mobile devices, etc.

however, that would be a myopic fix. the larger issue lies in how you use the space around the pub-piece (i.e., the space in the left- and right- sidebars, and also the top title-bar). once you eliminate duplicate functions (like the link to 'discussions'), group similar tasks, and let the left sidebar be different for different people (to the logged-in author, what you have now is good, but you could add a collapsed outline : but, to the casual reader, the left sidebar have an expanded outline and the other links might be either grouped or actually go elsewhere ——perhaps), then you would be making better use of space. i haven't spent more than a few minutes mulling over this, but i'm sure you could do away with most links in the left sidebar, except if the reader explicitly chooses to see an 'outline' there. all the other options in the left sidebar can easily be moved elsewhere (and be more useful): for example, follow & print are utilities, and can be moved to the bottom or be placed as icons on top of the central piece. source, history and journals can be at the head of the write-up, because a person is less likely to resort to them once they've begun scrolling down and reading the write-up (i am working on many baseless hunches here, and could be wrong. but i hope you see my point). discussions, right now, seems like a futile link, and could be replaced by a 'maximise' option on top of the right-sidebar. that would leave only 'read' and 'edit' in the left sidebar, and, well, i'd wager they don't belong there either.

i'd have been happy to get to really understand the platform better and draw up wireframes (etc), but can't till july. (sorry.)

**Comment by isTravis** [comment]
Collapsable Table of Contents section added to design in architecture2. Will be live shortly!

<img width="1162" alt="screen shot 2016-07-24 at 8 14 29 am" src="https://cloud.githubusercontent.com/assets/1000455/17083722/c46a7f9c-5176-11e6-9b87-08cf635e5988.png">
