### ISSUE TITLE
Live links in notes

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#484]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required

---

**What's your request?**
Add live links in notes (both in the pop-up and the generated citations/notes list)

**What would this feature help you accomplish, and why is that important to you?**
Ask from multiple communities (most recently John Maxwell for Mind the Gap). Right now readers would need to copy the link and paste it in a new window to visit site. 

**What's the URL to your PubPub community?**

### Optional

---

**Are there any other products or services that do this well?**

**Any attachments or reference images? (Drag them here)**

**Who requested this? (If not you)***

**Comment by gabestein** [comment]
This should be addressed in #491, so I'm adding it to the milestone and assigning to Travis and Deepak.

**Comment by gabestein** [comment]
We decided: when you type or paste in a link + move the cursor, we'll auto-create a link.

**Comment by gabestein** [comment]
Addressed in #673
