### ISSUE TITLE
Pub footer metadata

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#490]
How do we display the following metadata:

- Footnotes
- References
- Annotations
- License

With the idea that in the future we might display more things like:

- Credits
- Linked Pubs
- Funding
- Acknowledgments
- Read next/recommended reading
- Subscription widget
- Donate widget
- Badges

In general, this content will not be editable inline. It will either be generated from the document (in the case of footnotes & citations) or entered in management/user profiles (ie in the case of funding, acknowledgements, etc.)

**Comment by djagdish** [comment]
Figma file can be accessed in the Pubpub folder: https://www.figma.com/file/bG3HP8aRo5Z5kvDXVvxKV4/PubMetaFooter?node-id=0%3A1

Some screenshots of options:


**1. continuing white background as pub content area, minified row views for each meta section, clicking on each row shows expanded view**

![image](https://user-images.githubusercontent.com/316939/63283019-beff5700-c2cd-11e9-92ae-ea7b6b59bdda.png)




**2. different background color for pubmetafooter section, lightgray-ish tone of accent color, comment threads appear in a single white box each**

![image](https://user-images.githubusercontent.com/316939/63283174-3503be00-c2ce-11e9-8ae4-6b71eacce7f3.png)




**3. when there are no general comments, subtle prompt to add a comment or create a new linked pub**

![image](https://user-images.githubusercontent.com/316939/63283234-54025000-c2ce-11e9-9a54-17e81cb042e9.png)




**4. showing the Search feature expanded for an example section**

![image](https://user-images.githubusercontent.com/316939/63283295-785e2c80-c2ce-11e9-9361-b29c1baf9a78.png)




**5. showing Footnotes and minified view of comments along with a button to show comments before pubmetafooter begins**

![image](https://user-images.githubusercontent.com/316939/63283353-9c217280-c2ce-11e9-9b4e-86772242fb28.png)

**Comment by idreyn** [comment]
Done as of #517.
