### ISSUE TITLE
DOI deposit errors

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#496]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. Assigned a DOI for this article: https://jods.mitpress.mit.edu/pub/jyzg7j6x
2. All seemed ok
3. When you clicked on the DOI link from the article view page, it took you to a page that said "error DOI not found"
4. Ian stepped in and fixed it for this instance. He said, "Something odd happened with Crossref where it rejected the deposit the first time, but I went in and re-submitted it and it seemed to have no problem this time. Not sure what the underlying issue is yet."
5. The issue also pops up for this article: https://jods.mitpress.mit.edu/pub/2gnso48a?readingCollection=eb8e12ec
https://doi.org/10.21428/7808da6b.45957184
6. All other assigned DOIs for issue 6 seem to be ok (only 2 others)
...

**What URL can we use to see the issue?**
see above

**What browser/operating system were you using?**
Chrome

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Seems to have been a one-time error with Crossref. We resolved by removing the DOI from the database and re-assigning in PubPub.
