### ISSUE TITLE
Inserting Footnotes

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#497]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. When adding text to a new footnote sometimes (but not all the time) the page will scroll to the top.
2. Nothing about the note or the article itself will be changed, you'll just be at the top of the page, in the footnotes text field.
3. It doesn't happen every time within the same doc, but so far I can't figure out why it happens some times and not others. 
4. First noticed it in this draft: https://mindthegap.pubpub.org/pub/47c55bz4
...

**What URL can we use to see the issue?**
probably any draft

**What browser/operating system were you using?**
chrome

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Addressed in #673
