### ISSUE TITLE
Feature Request: Plagiarism screening tool

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#50]
This may be a topic for debate. However, plagiarism screening is a recommendation for a journal to be included in the Directory of Open Access Journals (https://doaj.org/publishers#advice) as well as for membership in the Open Access Scholarly Publishers Association (http://oaspa.org/membership/membership-criteria/).

**Comment by ThariqS** [comment]
That could definitely be a good idea, even if the plagarism tool is more interactive and just encourages people to cite more. Do you know of any good open source services for checking plagiarism against the broader internet?

**Comment by devinberg** [comment]
Unfortunately I don't know of any free open source options. Most publishers
seem to use either TurnItIn or iThenticate. Neither of which are free.
There are free websites for doing this but really what they do is compare
sentences against Google search results looking for duplicates.

There are open source duplicate checkers but they only compare within
existing text files. Thus only useful if you have a source to compare
against.

Maybe others will have some ideas.

**Comment by isTravis** [comment]
Given the new API that will launch with architecture2, I think I'd prefer to see this as an external tool.

Essentially, we or someone else builds a site that pulls from the PubPub API and pipes everything through the plagiarism checker of their choice. 

I'd be happy to even spend some cycles on this, but it seems a bit too rife with debate, legal consequences, and proprietary tools to be integrated into core PubPub anytime soon.
