### ISSUE TITLE
Page title should update in real-time with Pub title

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#501]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. Created new pub.
2. Changed pub title.
3. Page title did not update in real-time. I had to refresh.

I know we used to update the page title. Seems like that's regressed.

**What URL can we use to see the issue?**
Any new Pub.

**What browser/operating system were you using?**
Mac OS / Chrome

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by isTravis** [comment]
Addressed in #529.
