### ISSUE TITLE
Images and text switched on pubpub/explore 

### ISSUE THREAD

**Issue by schwettmann** [pubpub/pubpub#515]
<img width="867" alt="Screen Shot 2019-08-25 at 8 19 53 AM" src="https://user-images.githubusercontent.com/26309530/63649889-64249000-c711-11e9-92b3-9c3f310b5497.png">

Projections text (on left) displays cover image for M x M x M hack (links to M x M x M hack); M x M x M hack text (on right) shows projections image and links to Projections [google chrome]

**Comment by isTravis** [comment]
Thanks, Sarah! A fix has been added here dde74dc8c9b621e9667af4b457387e39dc0b16c4 - and it will go live early this week.
