### ISSUE TITLE
Better mobile table sizing

### ISSUE THREAD

**Issue by joeltg** [pubpub/pubpub#516]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required

---

**What's your request?**

Better table sizing, _at least_ on mobile. Currently tables never scroll horizontally, often creating long columns just a few characters wide, which makes the contents effectively unreadable.

This is true of tables on displays of any size if they have enough columns, so this isn't strictly mobile-specific.

**What would this feature help you accomplish, and why is that important to you?**

It would let me view large tables on my phone.

**What's the URL to your PubPub community?**

https://kfg.mit.edu

### Optional

---

**Are there any other products or services that do this well?**

**Any attachments or reference images? (Drag them here)**

**Who requested this? (If not you)***

![File](https://user-images.githubusercontent.com/8454646/63702858-d1a9ec80-c7f5-11e9-8c66-11e7a9490e9b.jpg)

**Comment by gabestein** [comment]
Adding some recent research to this:

It appears that at some point, for reasons not well understood, tables switch from having a max-width set to a width when you resize certain columns. It currently appears to not be possible to resize columns so that all of them appear with a set width.

In sum: we really just need to re-do tables.

**Comment by metasj** [comment]
I would love a range of display modes for tables.   In order of how often this feels like a good idea:
* "popped out" (as with iframes) w/ up to a 100% width -- addresses most issues on desktop.
* "horizontal-scroll" (with either the current max-width, or the above popped-out version) -- necessary on mobile
* "vertical-scroll"  (with tall tables, may want to set explicit height and width) -- useful on mobile
* "downloadable / zoomable" (important for very large tables - render the table as a single file, which can be downloaded or zoomed in on: image or pdf)

**Comment by gabestein** [comment]
Resolved by #2423
