### ISSUE TITLE
Visibility of branches is now too hard to understand; Errors common

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#520]
I hope this isn't a dup; it is a broad issue but couldn't find the core aspect addressed.

Ex 1: 
1. I create a pub and expect it to be visible to site admins. 
2. A site admin visits it and cannot see anything.  
3. I add them explicitly as someone who can view the article.

Ex 2: 
1. I create a draft pub, then go to the public branch.  Nothing is there.  From the view saying nothing is there, it is not clear how to fix this.
2. I go back to the draft and click 'Publish' to merge it into the #public branch.  
3. I realize I made a mistake, and want to unpublish that version.  I don't see an obvious way to do this [like looking at two branches and choosing to change the public-branch-visibility of a revision], so I disallow the public from being able to View any branch.  
4. I do not see a way to make a new draft public without making the old revision public.  I create a new pub instead.

[Chrome]

**Comment by gabestein** [comment]
This has been resolved in the Dashboard updates (#769). Branches have been replaced with a draft/release system. Forks will, eventually, replace branches for maintaining multiple simultaneous versions of pubs in parralel.
