### ISSUE TITLE
display issues in IE 11

### ISSUE THREAD

**Issue by awetterberg** [pubpub/pubpub#522]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. We have one publication on PubPub.  Government clients are complaining that they cannot see it properly in Internet Explorer, which is the only browser available to them.
2. I checked the page using IE 11 and saw the following issues (see notes and screenshots below)
...

**What URL can we use to see the issue?**
https://rtipress.pubpub.org/pub/interactive-visualization 
**What browser/operating system were you using?**
IE 11
### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**
1. very close left justification and text spilling off the page at right
![image](https://user-images.githubusercontent.com/54723486/64046226-646dc280-cb39-11e9-9ac1-8d2a76b8cca0.png)
2. figures oddly sized relative to text
![image](https://user-images.githubusercontent.com/54723486/64046300-9bdc6f00-cb39-11e9-8965-bdbbcaa7a124.png)
3. pubpub logo distorted in footer
![image](https://user-images.githubusercontent.com/54723486/64046358-b1519900-cb39-11e9-99b3-39c66c901222.png)
4. interactive figure elements display horizontally (rather than preferred vertical layout which displays correctly in Chrome) and with a large empty field at bottom
![image](https://user-images.githubusercontent.com/54723486/64046525-07bed780-cb3a-11e9-93df-241b99b12d4a.png)

**Who reported this? (If not you)**

**Comment by isTravis** [comment]
The items noted above have been addressed in #528. Other IE11 design inconsistencies remain, but pubs are much more legible now.
