### ISSUE TITLE
User Profile Design

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#523]
First pass the design of elements that should exist on a user's profile page.

**Comment by djagdish** [comment]
Figma file for this view is located here: https://www.figma.com/file/Cpy0Z2trC6FEz9uAoOM7UD/UserProfileViews?node-id=0%3A1

Render of frame-base14 included below as current status:
![base14](https://user-images.githubusercontent.com/316939/65787805-626a4400-e177-11e9-8083-2015907c7719.png)
