### ISSUE TITLE
may be Affero GPL?

### ISSUE THREAD

**Issue by yarikoptic** [pubpub/pubpub#53]
I have noted that you licensed pubpub under GPL 2+ . Since PubPub is primarily a hosted web service I wondered, if you are trying to "secure" the open-sourceness of the PubPub uses, wouldn't Affero GPL (see eg https://en.wikipedia.org/wiki/Affero_General_Public_License) be a better fit.

**Comment by isTravis** [comment]
Thanks for the contributions - and sorry for the delay in responding! 

Great suggestion - we've been working with MIT licensing office to convince them to support Affero (and GPLv3 for that matter - they currently only support GPLv2). We're still graduate students and the work is being built at MIT - so for the time we'd like to keep them happy with us :)

All that said, the more arguments and users we have in support of Affero vs GPLv2, the stronger case we have as we try to get them to support it - so feel free chime in with reasons and example uses ([edX](https://github.com/edx/edx-platform) - previously MITx uses Affero - so maybe that's a good precedence to point out).

Beyond that though, there is also the social aspect of a license. GPLv2 is much more familiar to people than Affero - and some teams won't touch code if the license is foreign. Any thoughts on that aspect are also welcome (Old articles like [Google banning Affero](http://www.theregister.co.uk/2011/03/31/google_on_open_source_licenses/) stick in my mind).

**Comment by isTravis** [comment]
Closing for now. Will re-open if the anything chances with MIT licensing office and we are open to consider Affero. Thanks!
