### ISSUE TITLE
Width: What Is It For?  Fully using display space

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#530]
Wide visual elements foil pubs.  Images, tables, iframes, detailed/nested lists.

Ideally there would be a way to support wide elements for layout and format, separate from the roughly 80-character width of text columns.  Or a way to choose a wide-rendering page.  

Compare github, which has am 80char-wide approach to issue text, which is expected to be ... mainly text!, and a 110-char-wide approach to wiki pages, which are expected to have more layout.

**Comment by isTravis** [comment]
We've added a 'breakout' option for images, videos, iframes, and audio. Does that solve what you're referring to?

Check it out here: https://demo.pubpub.org/pub/lbypv22u/branch/2

<img width="1173" alt="Screen Shot 2019-09-04 at 6 11 36 PM" src="https://user-images.githubusercontent.com/1000455/64276334-9b7c1380-cf3f-11e9-9751-416157b6cab3.png">

Tables are still a work in progress on that front. I'm not convinced yet that it's a good idea to support lists that are nested so deeply they need more than the text-width.

**Comment by metasj** [comment]
Yes! The feature pipeline is way ahead of me.
