### ISSUE TITLE
Pub preview visibility relies on lowest-ordered branch being visible

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#532]
A change I made for #499 makes `formatAndAuthenticatePub` unnecessarily strict about branch visibility, and if the lowest-ordered branch on the pub is not visible, it will prevent previews for that pub from showing up. This doesn't need to be fixed immediately because there's no user-facing action that can trigger this situation, but over time it could cause things to break in unexpected ways.

**Comment by gabestein** [comment]
This has been more or less resolved in the Dashboard updates (#769), which functionally removes branches.
