### ISSUE TITLE
Some footnotes blank in exports

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#536]
### Required
---

**What went wrong, step-by-step?**
1. Visit https://wikipedia20.pubpub.org/pub/lifecycles/branch/2
2. Export the doc to word or markdown
3. Observe that most footnotes are blank, and the ones that aren't have spacing issues (newlines before and after the citation text).
...

**What URL can we use to see the issue?**
https://wikipedia20.pubpub.org/pub/lifecycles/branch/2

**What browser/operating system were you using?**

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Joseph Reagle / https://knowledgefutures.freshdesk.com/a/tickets/307

**Comment by idreyn** [comment]
Fixed as of 09aa6db6
