### ISSUE TITLE
Padding and min/max overrides for images on Pages

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#537]
### Required

---

**What's your request?**
Images added on pages and aligned left or right currently do not have any padding between wrapped paragraphs and the images, making them look bad. It would be great to add the same padding around those images as we have on Pubs.

Additionally, the min/max override field we added to allow folks to make images smaller or larger than the slider allows on Pubs is not available on pages, making it difficult to resize images smaller than what most would consider a medium-size image, in particular. It would be great to implement this functionality on pages, as well.

**What would this feature help you accomplish, and why is that important to you?**
It would help make pages with images look professional and give folks more image options in the short-term before we overhaul pages. I think this also may have been a regression related to editor updates.

**What's the URL to your PubPub community?**
One example: https://goldsmithspress.pubpub.org/academicdiary

### Optional

---

**Are there any other products or services that do this well?**

**Any attachments or reference images? (Drag them here)**
<img width="1238" alt="Screen Shot 2019-09-12 at 9 49 15 AM" src="https://user-images.githubusercontent.com/639110/64789578-9cfe9a80-d542-11e9-843b-49d930b39971.png">

**Who requested this? (If not you)***

**Comment by gabestein** [comment]
(fwiw, I think we can just do padding for this cycle)

**Comment by isTravis** [comment]
Left and right padding has been added for all floated figures in https://github.com/pubpub/pubpub-editor/commit/8b4295281d14b5363f03c6376fb48a145fd03165.

Regarding the min/max override: that was only an option we enabled for the height of iframes. No images (or other figure elements) allow min/max override for width values. I think the logic is maybe a bit different there - as we don't ever want to allow more than 100% on widths. It's also a bit more complicated because the min/max override works well for `px` value lengths. Width, for all figures, is a percentage value. We could simply lower the minimum allowed value on figure widths (currently set to `25%`).

**Comment by gabestein** [comment]
ah, right. I got that mixed up. I think it would be good to lower the minimum value, perhaps to 10%? 25%, especially for wide pages, is quite large.

**Comment by gabestein** [comment]
also, not to be super picky, but I'm wondering if we should overwrite the margin for `.editor figure` entirely for floated figures. Right now there's a top and bottom margin of 1em. That top margin looks pretty odd, as it creates misalignment with the top of the paragraph we float against.

<img width="1184" alt="Screen Shot 2019-09-13 at 12 26 39 PM" src="https://user-images.githubusercontent.com/639110/64878565-cb9f7280-d621-11e9-9750-abbaa8f8f9d6.png">
<img width="1207" alt="Screen Shot 2019-09-13 at 12 22 36 PM" src="https://user-images.githubusercontent.com/639110/64878567-cc380900-d621-11e9-8d71-2d16fe9707b5.png">

**Comment by isTravis** [comment]
Good points. The margins have been further tweaked in https://github.com/pubpub/pubpub-editor/commit/1ad793be160dfe306337243165b7f0628d6823cb.

I also reduced the minimum allowed figure size in https://github.com/pubpub/pubpub/commit/d9e43944dca04927db57d66dbfc85227c412531b. I only went down to 20% - as 10% for video, audio, and iframe felt too low (controls were cut off).
