### ISSUE TITLE
Second citation doesn't fill in structured data

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#548]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. Create new pub.
2. Create a first citation and enter `https://doi.org/10.1109/5.771073` into structured output.
3. Create a second citation and enter `10.1109/5.771073` into the structured output.
4. First citation will work properly. Second will not fill in structured citation (nor, it seems, ping the server).
...

**What URL can we use to see the issue?**
https://kfg.mit.edu/pub/kzh7dyjz/branch/2

**What browser/operating system were you using?**
Chrome Latest / Mac Latest

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Harrison / IA State

**Comment by isTravis** [comment]
Nice catch. Fixed in https://github.com/pubpub/pubpub-editor/commit/893ac2652895c2acdbe987333eb673c058952f4a.
