### ISSUE TITLE
Feature Request: DOI assignment for Pubs

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#55]
I believe this is possibly in the pipeline for development. However, I'd like to request that PubPub provides DOI assignment for pubs published using the platform. This will help journals being created on the platform to be taken seriously and also aid in indexing of pubs published on the platform.

**Comment by isTravis** [comment]
Yes - indeed in the pipeline, but thank you for adding it as an issue here. 

Need to do a bit of coordination so that we have a good strategy for keeping the issuance of DOIs free for users (seeking university or other support to keep these free in the long term). But, we do have a short-term plan ready that we should probably roll out until we solidify longer plans. 

Coming this week or next hopefully (feel free to bump this thread if I fall behind on that time table).

**Comment by devinberg** [comment]
Perhaps there is a mechanism for limiting the number of DOIs assigned by some criteria. I'm not sure what that criteria is exactly.

1) Once featured in a journal, DOI is assigned. (more restrictive)
2) Once determined not SPAM, DOI is assigned. (less restrictive)

**Comment by kyleniemeyer** [comment]
Option 1 seems most appropriate, considering the intended persistence of a DOI (and typical association with a published/peer-reviewed article).

**Comment by devinberg** [comment]
There I suppose is also a decision to be made if DOIs are assigned for
things like reviews themselves. www.scienceopen.com does this for
comments/reviews by verified members.

I don't believe there is any requirement that DOIs are only for
peer-reviewed artifacts. Figshare provides a DOI for just about anything.
The main requirements of a DOI are that it captures a reliable snapshot of
the item and that the publisher will make sure the item is always available
even if they move it (the DOI needs to be updated).

**Comment by kyleniemeyer** [comment]
Yeah, fair point.

One reason for leaning towards the "more restrictive" model (less DOIs overall) is that they cost a certain amount each, which for CrossRef is $1.00 per article, I believe. I'm not sure if this holds for versioned DOIs like what Figshare does—those might be just independent DOIs only connected internally. However, this is probably a topic best served for a different issue (and further down the line).

**Comment by isTravis** [comment]
I'm tempted to lean towards the more utopian case here. The cost of DOIs should not be a barrier. At the end of the day, it's essentially free - it's just an ID in a database. It doesn't require huge resources to create or manage, so I foresee the long-term trajectory being that DOIs (or whatever comes next) to be essentially zero-cost. 

If we don't worry about the cost, it seems pretty interesting to give everything we can imagine a DOI. Let's not limit what could be possibly cited - and instead see how and what people cite. And perhaps if we can show that an abundance of DOIs facilitates better practices and more open reference, then we can make the argument for their commoditization and reduction in price. 

I'm tempted to do a DOI at the moment of publication (regardless of journal status, but perhaps pending some spam-check as suggested) and build a sub-DOI mechanism for routing to assets, paragraphs, etc. I do like the idea of giving reviews a DOI - but it seems a bit heavy to give a DOI to a simple typo fix suggestion. But perhaps that's just the price of having a DOI-heavy approach - some of them are never going to be used.

**Comment by devinberg** [comment]
Sounds good. It could be an interesting use case to allow sub units of a pub to be issued a DOI. Perhaps even on a "by-request" basis. For example, you highlight a section and one of the options is "Request DOI". Maybe the same could be done for reviews. On-demand DOIs™.

The only reason I mentioned the spam issue is that I had noticed there was a bunch of it on pubpub.org when I was searching through for specific pubs. I'd hate to waste resources on the spam but maybe someone would like to easily cite it ;-)

**Comment by isTravis** [comment]
How else will we actionably identify and cite the spam if it doesn't have a DOI...

That said - apologies about that spam. It's all from one person/bot as far as I can tell (all from a similar batch of IPs geographically). We haven't had a chance to sit down and really fix that - but ideas for blocking spammers welcome. Perhaps we just have to start requiring email validation on registration.

**Comment by gsarma** [comment]
[The Winnower](http://www.thewinnower.com) is worth taking a look at for a possible model.

**Comment by isTravis** [comment]
DOIs finally implemented. Happy to iterate on the solution as it exists, but at the moment any user is allowed to assign a DOI to a specific published version of their Pub. A DOI can only be assigned to one version, and cannot be changed. 

Changing the metadata of the DOI (journal associated with it, etc) is possible, though the UI for that needs a bit of clarity.

**Comment by r0bis** [comment]
Sorry, is it possible to know how the DOI feature works from the user perspective? I also found that there is v2.pubpub.org and www.pubpub.org - I am not sure in which version the DOI mechanism is implemented and how to access that. With thanks,
Roberts
