### ISSUE TITLE
"Uh oh" modal thrown when trying to arrow-key out of table

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#550]
_When I do the following:_

- Create a new Pub
- Put a table in the pub
- Move my cursor to the first cell and then hit the left arrow key

I get the "Uh oh! An error has occured in the editor." modal and I am forced to refresh. This is probably some Prosemirror range issue that needs to be cleaned up.

_What I expect to see:_
I'm not sure...it would be nice if this actually moved the cursor out of the table to the previous position, but at the very least it should not cause an error.

_Tested on:_
 macOS Chrome, Firefox

**Comment by gabestein** [comment]
Resolved here-ish: https://github.com/pubpub/pubpub/commit/c317843903cb6b776ff9d5b95fbe46d981bf8200
