### ISSUE TITLE
Smart apostrophe import

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#554]
**What went wrong, step-by-step?**
1. Import a document with smart apostrophes [‘]
2. Result is rendered as dumb apostrophes [']

This has required a lot of manual change after import.

**What URL can we use to see the issue?**
N/A

**What browser/operating system were you using?**
Safari

**Who reported this? (If not you)**
Jeff Pooley

**Comment by idreyn** [comment]
It would be helpful to know what kind of document was provided as input — I just plugged in a `.docx` and it preserved the smart quotes just fine.

**Comment by jeffpooley** [comment]
It was a markdown import, and not that smart quotes import is fine. It is just smart apostrophes. Thanks.

**Comment by jeffpooley** [comment]
Investigating this further, it seems that this is a bug in the markdown export of my text editor (iA Writer for iOS) rather than an import bug for PubPub. My apologies.

**Comment by idreyn** [comment]
No worries! Thanks for taking the time to make a report.
