### ISSUE TITLE
Trying to edit a public doc fails (can't discover / reach draft branch)

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#556]
I have a public document (that I created, and published).  I try to edit it from a new device or browser, and fail.   Someone else I sent a link to, w/ an invite to edit, also fails and tells me it is not editable.

The 'public' branch is not designed to be edited because it is not the 'draft'.  The 'draft' branch is hidden from readers, they have to both know how to find it in a dropdown and know that it might have different editability properties than the 'public' branch [e.g.: it's not just a matter of two different branches each of which can be edited; the public branch can't be edited]

**Comment by metasj** [comment]
Reported in the wild:
https://discourse.knowledgefutures.org/t/just-cant-find-edit-mode-losing-my-mind/210/3

**Comment by gabestein** [comment]
This has been resolved in the Dashboard updates (#769), which makes it much clearer how to find the draft.
