### ISSUE TITLE
Trying to edit a public doc fails, Part 2 (learning how to edit drafts)

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#557]
Related to #556 : I again try to share and edit a public document, that I created and published and made no effort to make private.  I share a link to the draft branch with others.  They can't see this branch at all and say the link is broken.

I have to view the doc (no bulk actions possible on a set of docs), go to 'share' and set public visibility for 'draft' to 'edit'.

**Comment by gabestein** [comment]
This has been resolved in the Dashboard updates (#769). Releases are not editable; you can now simply share an editable link of the draft.
