### ISSUE TITLE
Newbie creating a page, cannot find familiar edit or save interfaces

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#558]
Working with a new editor: we were creating a page to add to the nav of a new community.  Aiming for a page with 1-2 sections and a pubpub-style editor.

Two challenges: 
1) The default page setup did not start with a text section w/ a familiar editing interface. It was not obvious how to change that.
2) Saving was different from pubs, and not obvious once one had scrolled down a bit and no save button was visible on the screen.  A natural instinct to visit other pages would have lost the changes made. 

**Solution**: 
* Delete the default pub-filled sections
* Add a new section.  [Seeing how to add a new section took some experimentation]
* Make the new section 'text', not 'html' or other.  'Text' in fact means rich pubpub-editor text.

* Save.  Remind them to explicitly save, unlike in pubs.  If you don't see a save button, keep searching until you find it.  All the way up, good.

**Comment by metasj** [comment]
Migrating the comment from the old merged FR.  I know some of this is already in progress.

> The most common problem new editors face is knowing whether or not they have saved an edit to a page.
> If you scroll down to work on various sections, it's easy to forget you haven't saved.
>
> Possible improvements: A floating or larger 'save' button, or more catchy warning when leaving the page without saving, or explicit visual walkthrough of this difference on the first contribution to a Page.

**Comment by gabestein** [comment]
Closing as stale. Will be given attention in https://github.com/pubpub/roadmap-repo/issues/7
