### ISSUE TITLE
Feature Request: Author affiliation information in profile and on pubs

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#56]
It would be nice to have a field in the account profiles for affiliation. 

Also, if this information could be included on each pub page in some way. Either under the author's name or shown on hover over the author's name.

**Comment by isTravis** [comment]
This is something I've gone back and forth on a few times. 

In the profile - it makes sense to be able to list affiliations. We can (and have planned to) certainly add that (is a verification step required in your mind? perhaps by email).

Having those affiliations automatically populate into the pub becomes a bit more cumbersome. What if an author has multiple affiliations, but for a given document, only wants to list a subset of them? What if there is an affiliation that makes sense on a pub, but wouldn't be something you'd list on your profile. Solutions to how we can better manage this are welcome.

One thing you can do for the pub at the moment is add new fields in the header (the header was designed to be flexible for things like this), eg:

```
author: travis_rich
    name: TS Rich
    affiliation: University of Candyland
    title: Research monkey in training
```

**Comment by devinberg** [comment]
I didn't realize that new fields in the header feature. That is great, though maybe a little unlikely to be utilized without a clear requirement or prompting to do so.

Verification would probably be nice. Particularly when it comes to addressing spam. Using an academic email domain is one possibility or also possibly using ORCiD. I know that www.scienceopen.com currently uses ORCiD as a verification method and in order to review/recieve a DOI you must have at least 5 articles on their ORCiD page.

**Comment by kyleniemeyer** [comment]
ORCID seems like a great way to do this.

**Comment by gsarma** [comment]
A related issue is for an author's degrees to be listed.  I realize that you can simply tack it onto the end of your name, but it might make sense to have a separate field. 

The main reason I mention this is that it is standard practice in medicine for everyone's degrees to be listed on a publication alongside their name.  The reason I think this is the norm in medicine is that MDs, MD/PhDs, PhDs, RNs, etc. all have very different roles in a hospital or research setting.  In many cases, it may be relevant information for a reader to know the extent to which the authors have direct interaction with patients and whether it is as an attending physician or nurse, just as an example.

**Comment by gabestein** [comment]
[Closing some old issues]
We now support a "title" field in user profiles that display in the contributor section in Pubs. This can be used for affiliation and degree as needed.
