### ISSUE TITLE
Deleting/adding characters at the end of a comment-highlighted selection behaves inconsistently

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#564]
I highlight "hello", and add a comment.  I delete the "o".  (intentionally or otherwise)
Sometimes the whole comment disappears, sometimes just that letter.

* I try to add back the "o" by placing the cursor after "hell" and typing **o**.  This does not extend the commented string.  
* I place the cursor after the first "l" and type "lo" --> **hellol**
* ... and delete the last "l".  sometimes this deletes the entire comment.

A specific workflow I captured but didn't screencast (see also #563):
* highlight "hello", comment, lose focus, delete removes 'o'. 
* Add 'o', but it is now not highlighted. Add 'o' after 'l' inside the highlight, works. 
* Delete the 'o' outside the highlight, lose the entire comment. No undo. Comment appears at bottom of page however. 
* Try again: highlight 'hello', type comment, arrow down (invisibly losing focus), delete. This time just immediately deletes the whole comment. No undo.
* Try again. Highlight 'hello', selecton comment icon. Now can't comment. (nothing happens)
Tested on this pub (with "word" instead of "hello", but that was confusing in the bug report): https://cess.pubpub.org/pub/nkshaxqi/branch/2

**Comment by gabestein** [comment]
We've made a lot of changes to the internals of discussions since then, and I am now, happily, unable to reproduce this! Feel free to reopen if it occurs again.
