### ISSUE TITLE
Losing state when working quickly: adding authors

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#565]
Updating a pub, adding authors to the credits list. 

Often, characters typed in the text field don't match what's in the hovertext (which is the string that gets created as the author's name).  This leads to last letters being cut off.   

This is related to keystroke handling: 
* cut&paste never produces the problem
* adding a space at the end of the name resolves the problem

Two examples:
* Often just the last letter is not captured in the hovertext. ("Jame" vs "James")
* Sometimes the full string starts to appear briefly in the hovertext and then the last characters are rapidly deleted from it.  ("Carleton Davie^B^B^B^B^B^B^B^B^B" --> "Car" vs "Carleton Davies")

**Comment by metasj** [comment]
![pub-name-bug](https://user-images.githubusercontent.com/1615548/66327242-8278d080-e8f8-11e9-9ba0-930c98a3b8b0.JPG)
![pub-bad-author-bug](https://user-images.githubusercontent.com/1615548/66327241-8278d080-e8f8-11e9-9d23-0810a1b1ed16.JPG)

**Comment by gabestein** [comment]
I believe this is resolved by Pub Header updates rolled into our Dashboard changes (#769).
