### ISSUE TITLE
Losing state: Unsaved updates to editable fields lost when following a link

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#566]
Working quickly, especially when creating a set of new pubs for the first time: edit a pub title, click 'Manage', lose changes to the title.

This should warn or autosave.  It is quite confusing: feels like a malfunction.  When this happens on the first creation of a few pubs, it is particularly frustrating: you create a set of pubs and it looks like you never did anything: they all have the identical default stub title.

Note this can happen by accident: Create new pub; edit title; try to open 'New pub' again in a new window; lack of context menu leads to following the link instead.  New pub created w/ the same stub title; old name-edit lost.

**Comment by gabestein** [comment]
I believe this is resolved by Pub Header updates rolled into our Dashboard changes (#769)
