### ISSUE TITLE
Warn on deleting a pub with history: currently looks like deleting a new one

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#568]
I have a set of pubs being worked on in parallel.  A few of them are duplicates and need to be [merged].  As there's no explicit merge option, one of the two has to be deleted -- generally a new one that was created when an old one full of content already exists. 

The confirmation to delete is just typing the name of the pub.  Here that's not helpful -- both have the same name! 
* Make it hard to unexpectedly delete a weeks-old 100kb pub, and easy to delete the 20th empty copy of "New Pub October 24".
* And per #281,  Make standard deletion (the kind that removes junk pubs from your feeds, pages, and search results) reversible

**Comment by gabestein** [comment]
Closing as dupe in favor of roadmap issue #2509
