### ISSUE TITLE
Cursor on pub page

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#57]
I'm not sure what this is but seems like maybe a bug? On this page, there is a flashing cursor after "University of California-Davis": http://www.tjoe.org/pub/editorial-board

On the "Source" page, it seems the cause is this bit of code `[[{"pluginType": "cursor"}]]`

However, editing the pub provides no options for deleting the cursor.

**Comment by ThariqS** [comment]
My bad! Just added this to the editor and I guess it publishes too! I'll remove it ASAP!
