### ISSUE TITLE
Allow reuse of ad-hoc collaborators (added to pub credits) across pubs

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#570]
I have a community of dozens of authors, not all on pubpub themselves.  They are collectively credited on a few dozen pubs.  Most are added by hand as collaborators where appropriate. 

* A pub-local list of ad-hoc authors, only showing up in name completion within that pub, would be welcome.  
* This might involve making ad-hoc author names editable rather than just strings that can be deleted and readded at will. 
* This would help streamline admins adding authors to pubs in a large network.

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/20
