### ISSUE TITLE
Add explicit "download" button to Pub export flow on mobile Safari

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#576]
As reported in #553, mobile Safari will not respect a `window.open()` call if it does not originate in a user-generated event handler, e.g. a click event. Because there's an intrinsic delay in our file exporter between selecting an export format and getting a URL to download with `window.open()`, we'll need to add a second button in the export flow for mobile Safari users to click once the export task completes.

**Comment by isTravis** [comment]
The UI of requiring the dropdown menu to stay open is problematic anyways. Perhaps we should move this into a Toast component that gives the loading status, a cancel button, and a download button when complete.

**Comment by gabestein** [comment]
This was implemented in #636
