### ISSUE TITLE
Re-enable horizontal_rule nodes in Pub exports when Pandoc 2.8 is released.

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#577]
[(See this issue in the Pandoc repo for context)](https://github.com/jgm/pandoc/issues/5801)

The Pandoc TeX exporter generates markup for horizontal rules that's apparently not accepted by the latest version of the `xelatex` PDF renderer, causing any PDF export with a horizontal rule to break. For the time being I'm just going to filter our `horizontal_rule` nodes out of PDF exports for Pubs. The issue has [already been fixed](https://github.com/jgm/pandoc/commit/d9db76dcf40d1930ad15317d76fd2c90d9114801) by the Pandoc developers, so once they cut a new release we should update the Pandoc binary that PubPub uses and re-enable horizontal rules.

**Comment by gabestein** [comment]
Resolved by #631
