### ISSUE TITLE
Pub structure and standardization

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#58]
PubPub's HTML needs to be more cleanly organized and standardized. We don't have a clean pipeline for adding metadata into elements or exporting to [InstantArticle](https://developers.facebook.com/docs/instant-articles), XML, or [JATS](http://jats.nlm.nih.gov/).

A bit of this is due to the fact that we didn't know _which_ standards would be important. Now that some time has passed, here are a list of html and xml standards that may be useful:

[JATS](http://jats.nlm.nih.gov/)
[NLM](http://dtd.nlm.nih.gov/)
[Scholarly HTML](http://scholarly.vernacular.io/)
[Instant Articles](https://developers.facebook.com/docs/instant-articles)

A few questions: 
1) On the backend, is markdown our common language from which we derive all outputs (HTML, PDF, XML, etc) - or do we convert markdown to another format (e.g. JSON) that we then derive outputs from?
2) For XML, Instant Articles, etc is the pipeline Markdown>HTML>InstantArticle - or do we instead write markdown processors that convert directly Markdown>InstantArticle?
3) What standards are we missing and what else should we be considering?

My hunch is 1) yes, and 2) create direct converters, and 3) lots. Thoughts on those are appreciated.

**Comment by tomerweller** [comment]
I.A can interface with an [RSS feed](https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed). Why not just make the pubpub feed XML compatible with I.A?
