### ISSUE TITLE
Make menus in the Collections editor keyboard-accessible

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#585]
Pending #582 and as a follow-on to #584.

This:
<img width="148" alt="the All Collections menu" src="https://user-images.githubusercontent.com/2208769/67601039-6b800e00-f741-11e9-83d1-86670cb621dc.png">

These:
<img width="163" alt="The '...' actions menu on each Collection tile" src="https://user-images.githubusercontent.com/2208769/67601050-72a71c00-f741-11e9-8cc7-b215821d0f9b.png">

These:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/2208769/67601128-a6824180-f741-11e9-9c9b-aff624375787.png">

And last and certainly least, these:
<img width="204" alt="the Use As menu attached to selected pubs in the collection editor" src="https://user-images.githubusercontent.com/2208769/67601105-91a5ae00-f741-11e9-8a45-2dcc06ac6ea7.png">

**Comment by gabestein** [comment]
Resolved by #584.
