### ISSUE TITLE
Link Lock while clicking on highly-linked text

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#587]
**What went wrong, step-by-step?**
1. While editing a document with lots of links (a linked TOC), I click on text with a link and it pops up the URL text-box with the target URL. 
2. Clicking outside of that box to dismiss it doesn't work: clicking on the end of the line with the link leaves focus inside the text-box.
3. Clicking on the end of a line ending with a different link closes the first text-box and opens a new one, with the link from the new line. 
4. As this is a linked TOC, every line ends with linked text, so clicking outside the text box anywhere on the page is likely to open a new text-box.
5. _Esc_ closes the text box.  
...

**What browser/operating system were you using?**
Chrome/Mac and Chrome/Win

**Comment by gabestein** [comment]
No longer reproducible, happily!
