### ISSUE TITLE
Change pubpub's general RSS feed

### ISSUE THREAD

**Issue by tomerweller** [pubpub/pubpub#59]
The current model of an RSS feed that features all pubpub publications is extremely cluttered. As an RSS user I would never subscribe to such a feed.
Journal feeds are great (already implemented). As for cross-pubpub feeds, they need to be a meaningful subset (featured, popular, etc.) .

**Comment by isTravis** [comment]
PubPub-global feeds are no longer offered. Journal-specific are the way to go!
