### ISSUE TITLE
Confusing error when logged out while editing private page

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#597]
I thought this issue was alread filed, but couldn't find it; apologies if this is a dupe.
When editing a pub, if you get logged out, on refresh the page simple disappears and says "doesn't exist", which is confusing.  For instance: editing on a computer, have a reboot + reopen tabs, the tab you were editing in just seems like a bad URL.

[Aside: human-readable page titles makes this slightly easier to sanity-check :) ]

**Comment by gabestein** [comment]
Closing this! I don't know when, but at some point we added this text to 404s when logged out:

`If you believe there should be a page at this URL, it may be private. Try logging in.`
