### ISSUE TITLE
Make it easier to tag via 'collections' tab

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#598]
As a community editor + designer, I want to help editors quickly tag articles so that they show up in pages.  This is the core workflow needed for someone's work to be visible to others.

Editors have a hard time finding the 'collections' tab to do this.  They look for a way to do this in the main 'manage' interface.

**Comment by idreyn** [comment]
There is a Collections tab in the Manage interface! If you click here:

![image](https://user-images.githubusercontent.com/2208769/68500434-ba41a380-0229-11ea-8a18-62704229c6c2.png)

and click on a tag of interest, there's an interface for bulk adding/removing Pubs from Tags.

**Comment by idreyn** [comment]
Sorry, I may have closed this prematurely. You may be asking for a way to tag articles from a Pub itself, without leaving the main Pub UI?

I think this will find its way into a refresh of the Pub header pretty soon. Deepak has been working on making it possible to edit the most common pieces of Pub metadata (tags, contributors, description) without leaving the main Pub document view. Stay tuned!

**Comment by metasj** [comment]
Yes, that's what I meant; glad to hear it is coming!  

I find I often also want to add descriptive tags to something without thinking of it as part of a new Collection -- for instance, I just wrote up a color-palette review and am sure there are other reviews and maybe other things on color.  But that might be a separate feature request...

**Comment by gabestein** [comment]
@idreyn did this randomly and it is great!
