### ISSUE TITLE
Losing edits to pages: Editors confused by different 'save' process

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#599]
As a community editor, when introducing new people to Pages, the most common problem they face is knowing whether or not they have saved an edit to a page. 

Only the page interface requires an explicit "save changes" button press, and that button is only visible at the very edge of the screen -- if you scroll down to work on various fields, it's easy to forget you haven't saved.  

Possibilities: A floating or larger 'save' button, or more catchy warning when leaving the page without saving, or explicit visual walkthrough of this difference on the first contribution to a Page.

**Comment by gabestein** [comment]
Duplicate of #558
