### ISSUE TITLE
Plaintext regularly becomes titletext, unintentionally

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#600]
As an editor, I often find that I'm typing titletext (H#) on a new line when I mean to be typing plaintext.

This is partly due to a confusion between linebreaks and newlines. If I am at the start of a new line after a linebreak, in the middle of a title, and I create a newline (to break style), the style often remains in the new paragraph, and there's an extra half line-spacing (cr + lf > lf).

Low priority, never seems to be an issue on cut+paste

**Comment by gabestein** [comment]
I'm unable to reproduce this one. I believe it's was addressed as part of some stability improvements last year.
