### ISSUE TITLE
New empty articles continuously created w/o meaning to

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#602]
As a writer or site admin, I often unintentionally start a new pub (it's easy to click the button) and then close the window or follow a link to cancel that action.  However the pub remains.  

As a result, especially on days with lots of editors experimenting, there may be a large number of empty pubs with identical default titles.

Not saving an empty untitled pub, or making it much easier to see and delete these, would make the list of recent pubs (and of one's own pubs) easier to use.

**Comment by idreyn** [comment]
I agree that we can handle this better — I'm not sure the answer is deleting empty pubs; it might be better tools for bulk-deleting pubs, so after a day of messing about with PubPub you're not left with a dozen useless documents that must be deleted one at a time. Our planned dashboard refresh will handle this use-case better!

**Comment by gabestein** [comment]
Going through and cleaning some things up...we have some plans to handle better that will focus more on the dashboard.
