### ISSUE TITLE
Tag names can't be edited? 

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#603]
As an editor, I can't see a way to edit tag names from the UI.  If I make a mistake in tagging and notice after some have been applied, I have to make a lot of changes: delete the old tag, create a new one, reapply the new one, update any Page filters.  

A way to edit tags would be  great.  As a reader, it's annoying to see a tag w/ a slight typo/quirk just because it would be hard for editors to update it ;)

**Comment by idreyn** [comment]
You should be able to change the name of a tag by visiting **Manage > Collections** and then finding the tag you'd like to rename and clicking on the **Details** tab. The screen looks like this:

![image](https://user-images.githubusercontent.com/2208769/68500127-d55fe380-0228-11ea-9836-772d03392005.png)

Good to know that this is difficult to find, though.
