### ISSUE TITLE
Feature Request: Discussion box follows scroll

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#61]
In leaving a lot of comments on various pubs I've discovered a minor annoyance. As I progress through the pub scrolling down, every time I want to leave a comment I have to return to the top to type it and then return down to where I was. It would be great if the comment box followed me down the page.

**Comment by isTravis** [comment]
Agree - it's been frustrating to me too. We're redesigning a chunk of the discussions already and this will be one of the added features.

**Comment by isTravis** [comment]
Discussion box now locks to the top of the page on scroll.
