### ISSUE TITLE
Selecting text has become slower

### ISSUE THREAD

**Issue by idreyn** [pubpub/pubpub#617]
I'm not sure if our recent editor changes triggered this or not, but a `selectionchange` event now triggers three (!) calls to `updateCollabData` and can take hundreds of ms on my machine. Happens in both FF and Chrome.

![image](https://user-images.githubusercontent.com/2208769/68782918-221c3380-0608-11ea-9fa1-43363cc75cb4.png)

**Comment by gabestein** [comment]
I am not as good at running these traces as you, but I just tried this and I'm pretty sure this is no longer an issue either?

**Comment by idreyn** [comment]
Yup. This trace looks like it's doing a React re-render synchronously with a Prosemirror transaction, which we don't do anymore.
