### ISSUE TITLE
Bulleted-list and numbered-list icons don't appear consistently

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#619]
**What went wrong, step-by-step?**
As an editor, when working w/  a bulleted list with sub-bullets:
1. Whether the bullet-list or numbered-list icons show up in the toolbar is inconsistent.  
2. Moving the cursor down the lines of a long bulleted list, I can get any of the following behavior:
* Neither icon appears
* Only the bulleted-icon appears
* Only the numbered-icon appears
* Both icons appear.
When the bulleted icon appears, it is highlighted.

**What URL can we use to see the issue?**
Reproducible on any old pub.

**What browser/operating system were you using?**
Chrome/Win and Chrome/Mac

**Have any screenshots? (Attach them by dragging the image here)**
![no-list-icon-bug](https://user-images.githubusercontent.com/1615548/68793057-86e08980-061a-11ea-9302-d66ff9362acb.JPG)

**Comment by gabestein** [comment]
Should be resolved with the toolbar update in #673.
