### ISSUE TITLE
Let editors get directly from viewing the list of authors to editing it

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#621]
Related tangentially to #604 : 

As an editor, when looking at the list of authors or contributors while reading a pub, I'd like to be able to click on something (the 'Contributors' title, or a small 'edit' icon next to it) and edit the authors in-place; or be taken to the page that lists the authors and lets me edit them.

Currently, it takes 2 clicks and some mouse movement from left to right screen: I have to change to the menu, choose Attribution, then edit.

**Comment by gabestein** [comment]
Resolved by Pub Header updates rolled into our Dashboard changes (#769)!
