### ISSUE TITLE
Old empty pub appears in my pubs, but cannot be viewed

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#623]
**What went wrong, step-by-step?**
1. On July 9, I created a new pub.  
2. Later, I deleted it.
3. Today, I can see it show up near the top of my list of pubs, but clicking on it returns a Page Not Found error.   It does not show up in the overall list of pubs in my community.

**What URL can we use to see the issue?**
https://www.underlay.org/user/samuel-klein

**Comment by gabestein** [comment]
I believe this was resolved by some search-cache updates a while ago.
