### ISSUE TITLE
non-descriptive "Error" message on pub reload 

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#624]
1. Using a pub w/ 6 other simultaneous editors,
2. The pub stoped updating and said "uh-oh... [please reload]"
3. On reload, there was only an unformatted "Error" message.
4. This happened to 2 other editors at the same time.

The error message should at least be more verbose and have visual formatting.

**Have any screenshots? (Attach them by dragging the image here)**
![non-descriptive-pub-error](https://user-images.githubusercontent.com/1615548/68878440-b43e3d80-06d5-11ea-914f-e94b8a81f493.JPG)

Seen by me, gabe, travis

**Comment by gabestein** [comment]
This was related to merge issues that should no longer be an issue with the new Release publishing flow introduced in Dashboard updates (#769).
