### ISSUE TITLE
Easier viewing of all pubs; without warning message

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#625]
**What went wrong, step-by-step?**
1. As a community admin, I want to see the latest pubs.
2. That's not possible, so I want to see the list of all pubs, and to search through it for the pub my friend was working on (I think I remember the title, though I suppose he may have changed it)
3a. I click "Search", and search for <space>, but can only see 20 at a time.
4a. At this point if I click "Manage" I see the full list of pubs, and find it.

3b. Instead I click "Manage", now it first shows me administrative options for the community (confusing that it's different).  
4b. I click "Pubs" and get a warning - '_Leave site? Changes that you made may not be saved._'
5b. I click "Leave" and spend 3 years debating whether and how to leave.

**Have any screenshots? (Attach them by dragging the image here)**
![seeing-list-of-pubs](https://user-images.githubusercontent.com/1615548/68903237-7d354f80-0708-11ea-8f53-c3a6eaa81840.JPG)

As a community admin I need to visit the full list of pubs often, and would like a single-click way to get to them.  Perhaps the "Pubs" list of all pubs could be the default search view before anything is entered in the search field to narrow it down -- reducing the total # of pages by 1.

**Comment by metasj** [comment]
Additionally: the "Leave site?" warning is spurious: it happens when I have made no changes to any fields.  At the least, it should warn only if there are changes to potentially save.  Which would avoid the interruption in the common case of passing through en route to a different management interface.

**Comment by gabestein** [comment]
Resolved in Dashboard updates (#769). We now show a searchable list of Pubs and have replaced manage with dashboards at different scopes.
