### ISSUE TITLE
"Manage" does different things depending on context; confusing

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#626]
Noted while filing #625 -- 
* If you are on the Home page of a community, or any other page, and click 'Manage', you are taken to the config-options-page for that Page. 
* If you are the config-options-page for any Page **other than the Home page** and click 'Manage', you stay where you are.  
* If you are on the config-options-page for the Home page, or any other page?, and click 'Manage', you are taken to the single-page list of all pubs.

As an editor or community admin, this is confusing.  Doubly so if explaining to another editor [over the phone/online] how to do something. 

This should be consistent; if the link is taking you somewhere new it should change its name.

**Comment by gabestein** [comment]
Resolved by Dashboard updates (#769). Manage is no longer a concept. We now have dashboards at different scopes, and settings.
