### ISSUE TITLE
EPUB export contains TeX markup

### ISSUE THREAD

**Issue by dbvisel** [pubpub/pubpub#627]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. I have a document in PubPub that seems fine. It was initially created by uploading a Word doc
2. I try exporting as an EPUB (after successfully exporting a PDF).
3. When I open the EPUB, there's a lot of TeX-y commands at the top of the first page; similar content appears elsewhere in the book if I go to different sections in the Table of Contents.
4. Probably related: the cover preview contains an error message (see attached screenshot)

The actual content of the document all appears to be there; I don't see anything that's missing (though I haven't checked exhaustively). 

Additionally, running the EPUB through an EPUB validator (such as https://www.ebookit.com/tools/bp/Bo/eBookIt/epub-validator ) brings up a long list of errors.

...

**What URL can we use to see the issue?**

https://dbvisel.pubpub.org/pub/zpggskcf

Choose Download > Epub, then open the downloaded EPUB. I'm opening in Calibre, though I don't think it matters that much.

**What browser/operating system were you using?**

OS X 10.14.6 / Firefox 71.0b9 

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

![Screen Shot 2019-11-15 at 10 41 42 AM](https://user-images.githubusercontent.com/3360195/68912930-94ba1a00-0794-11ea-8579-db2515680522.png)
![Screen Shot 2019-11-15 at 10 41 28 AM](https://user-images.githubusercontent.com/3360195/68912939-9b489180-0794-11ea-86b4-6a3ac83ac0d0.png)
![Screen Shot 2019-11-15 at 10 45 48 AM](https://user-images.githubusercontent.com/3360195/68913094-275ab900-0795-11ea-812e-dfba9ca45b76.png)
![Screen Shot 2019-11-15 at 10 44 16 AM](https://user-images.githubusercontent.com/3360195/68913099-2aee4000-0795-11ea-9132-2f8a45be5714.png)

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Thanks for the thorough report! We're aware of the issue and currently working on a fix in addition to improve export quality generally in #613.

**Comment by dbvisel** [comment]
great! Thanks.

**Comment by gabestein** [comment]
Hi @dbvisel -- this should be fixed now. Please let us know if you're still seeing the issue in epub exports.

**Comment by dbvisel** [comment]
Fixed! Thanks so much! There are other metadata/TOC issues, but I'll diagnose what's going on there & put it in separate reports.

**Comment by gabestein** [comment]
Thanks! Your bug reports and feature ideas are awesome, please feel free to add more as needed.
