### ISSUE TITLE
Fulltext search doesn't return valid matches

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#649]
As a reader or editor, when searching for a string, I expect to find all pubs that match in the title or body text.  Title matches work, but other matches are confusing.  Matches in general seem fuzzy rather than exact.

On the kfg community, I can search for a string and return a list of matches that includes pus where the string isn't found, while not including others where it is found.  

- searching for "curious" returns [this pub](https://kfg.mit.edu/pub/f33v7gbs), which may have had that string in the past [now has 'curiosity'] but doesn't now.
- search for "excrem" seems to turn up many pages with "experimental"
- a search for "freshs" turns up two pubs w the word "freshsales", but a search for "freshsales" turns up only one of them

**Comment by gabestein** [comment]
We've done a lot of work on search indexing in the last year to eliminate searching against past strings in particular, and as a result I think most of the examples here are fairly resolved. The search is definitely somewhat fuzzy, but that's by design.
