### ISSUE TITLE
Feature Request: connect assets to pubs

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#65]
Please correct me if I'm wrong but it seems that assets such as references are tied to users rather than pubs. Thus if two users are collaborating on the same pub, they have different assets in the list. This makes it challenging to work together on a pub. I would recommend connecting the assets to the pub itself.

**Comment by isTravis** [comment]
We used to have assets associated to pubs, but recently (a month ago or so) switched to having assets associated with users. This lets the user carry references, assets, etc across pubs and into discussions. I still think this is the right decision as long as we implement the following:

1. Assets can be assigned multiple 'owners'
1. Collaborators on a pub have access to all of the assets in the body of that pub.
1. We provide much better filtering options for assets (e.g. don't just show all of the assets in the assets modal by default, but instead filter by 'assets added or used in this pub')

Thoughts welcome. If you could expand 'work together' that may help us ensure that user-associated assets still provide all the utility you're looking for.

**Comment by devinberg** [comment]
I understand the utility of have users carry assets with them. My only issue with that is would be the clutter. I would quickly have hundreds of references and would need a good search functionality. Similar with images.

The issue I ran into here was working with another user and discussing a particular reference. There was a bunch of confusion until we realized that we were not seeing the same references when we looked under assets. I could also see this being an issue with images. User A uploads an image to use later. User B working on the pub at a different time wants to insert it but doesn't have access.

I think automatically giving all collaborators access to all assets in the pub would be helpful. I also would appreciate having access to my "user assets" if there is search functionality and filtering as you mentioned. Even better would be import and auto updating from things like Mendeley or Zotero. Overleaf imports my entire Zotero library and can update it with a click which is helpful.

**Comment by isTravis** [comment]
Great - thanks for the elaboration. 

Part of the move to user-centric assets was so we could build support for Mendeley/Zotero imports. It doesn't make much sense to import all your Zotero data into a pub for every pub, so user-centric seemed like the obvious route. 

Filters and searches sound like the right path here. Thanks!

**Comment by isTravis** [comment]
'Files' are now direct children of the given pub. All editors will have access to these assets as they are no-longer user-centric.
