### ISSUE TITLE
Provet accidental page deletion. A misclick permanently deletes page sections

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#651]
following #343 and expanding one of the requests in #555 to its own bug:

As an editor and community admin, pages are _volatile_ elements to have.  

- A misclick can permanently delete an entire section.  
- Accidentally removing the wrong section can permanently delete a very full and customized section rather than a newly-created empty one.  
- Removing a section gives no warning to the clicker, so you might not notice that you've even successfully removed it.  
- If you are removing a section that extends below the bottom of the screen, and there is another section below it, you can mistakenly think that your click was not received, and click again, deleting a second or third section.
- As there is no warning given, if a section is removed unintentionally, unless the editor remembers to check the full resulting page (perhaps they went in to make a small textual edit, clicked along the side of the screen at some point and accidentally removed a long section below) they may not discover the deletion.  
- As there is no edit history, if your site hasn't been archived by the Wayback Machine, you also have no record of what disappeared and what you now need to recreate, and must do it from memory.  

As a result, while I would trust community admins to create, modify, or delete pubs, at present I don't want anyone to be able to edit Pages on communities I administer (often including myself).

Quick fix options: 
~ require confirmation before deleting a section.   
~ add a visual notification, a popup or colored bar at the top of the screen, indicating that a section has been deleted (and offering a time-limited undo)

**Comment by metasj** [comment]
I ran into this again today with a page: accidentally removed a section, and had to recreate it.  As people make more elaborate pages (for the ease of customization) and make them a central part of their communities, this can become more than a nuisance.

**Comment by idreyn** [comment]
I agree we should fix this — on the next iteration of this tool I think we'll go for full undo/redo capabilities but for now I think a confirmation popup would get the job done nicely.
