### ISSUE TITLE
History does not offer diffs or timestamps

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#652]
As an editor or reader, I want to see the last editor, and timestamp of last edit, for a revision when I am looking at it.  

As an editor or reader, I want to see a diff between revisions, at least between a selected revision and the current one.    [I also want rough indicators of major revisions, or the start/end of lusters of revisions made by the same person, to simplify selection; a separate FR]

- The history interface currently shows limited information on the range of dates over which there are revisions -- if all are a single day, no further timestamp data is visible.   
- When I use a permalink to a specific revision, I don't see its timestamp or last editor anywhere.  It's also not obvious to someone following that link why they can't use most tools -- commenting, editing.  Nothing on the screen other than the end of the URL suggests that this is a past revision.
- There's no obvious way to see a diff, or how much of the document has changed recently.  This makes reviewing updates more a puzzle than a concrete task.

**Comment by idreyn** [comment]
Two separable concerns here:

- The first is the clunkiness of the history interface. We've learned a lot over the past six months about how to do this correctly and I'm tempted to take another pass at it in the near future. Date granularity and confusion about how permalinked versions look to visitors are good things to focus on!

- The second is diffs. We have [some code to make diffs possible](https://github.com/pubpub/prosemirror-diff), but it's not ready for production yet and it's so CPU-bound that I'm tempted to rewrite it in a faster language than JavaScript. The concept of diffing will probably hit PubPub first as part of a v1 editorial review flow, but the intention is definitely to port it back into the history viewer — and eventually create a full-featured "track changes" feature.

**Comment by gabestein** [comment]
We've completely rebuilt the history interface since this was created, so I'm going to close for now. Agreed that diffs are something we should work towards, but it's a fairly separate concern and there are lots of plans/tickets for it.
