### ISSUE TITLE
Feature Request: Ability to reject/decline submission

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#66]
For journals, the ability to reject/decline a submitted pub is necessary to clean up the curation list.

**Comment by isTravis** [comment]
Definitely. We've been working through this on our end a bit as we redesign and clean up the submission process. A couple questions:

1. Do we allow people to resubmit? If so, should we require a new version?
2. Do we make public the fact that a pub was submitted and declined? I'd like to discourage people from submitting blindly to 10,000 journals, hoping that a couple come through. But I also don't want there to be a lasting stigma if a journal happens to find the content inappropriate for reasons other than quality (perhaps we don't want to accept submissions in another language).

**Comment by devinberg** [comment]
1. Perhaps. I guess anyone could create a new pub and resubmit regardless of the policy you set. Allowing them to resubmit the same pub would at least retain the editing history. Though maybe this is a journal specific setting.
2. This is a tricky question. The pub could be submitted to multiple journals and an accepting journal may not like to see the "bad mark" from a journal that declined. Though if the discussion is eventually filtered by journal then maybe that covers it. On the other side, if a pub is submitted to multiple journals and has to make revisions for multiple, which version is for which journal? What if there are contradictory revisions requested by each journal? Can the pub be forked? I don't know the answers to these at the moment.

This might bring up a separate issue but is the version of the pub accepted by a journal then the version of record for that journal and closed to later edits?

**Comment by isTravis** [comment]
Thanks! Definitely tricky... 

The only thing I care to prevent in showing 'declined submissions' is the case where a user has submitted to 500 journals, and plays the probability game getting it accepted somewhere. Perhaps we could have a simple flag that states, "Less than 10% acceptance rate". This could deter the spamming of journals without too harshly penalizing for content/journal mismatch.

Re:Forking - yes, it is a bit of another topic, but something we're talking about. I like the idea of having pubs be forkable or branchable. It'd be great to have the 'Simple English' branch or the 'Japanese translation' branch, or a branch that is co-authored by a New York Times reporter for a wider audience, etc. In that case, I think a journal would be tied to a specific branch and future updates to that branch would be (by default) automatically included.

**Comment by isTravis** [comment]
This feature request is a bit deprecated because of changes in the review process on PubPub. Such functionality exists now - but in a different fashion than originally discussed in this issue due to architecture changes.
