### ISSUE TITLE
HTML importer loses spaces across linebreaks

### ISSUE THREAD

**Issue by pkgw** [pubpub/pubpub#674]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. I tried to import an HTML document into a Pub
2. Spaces between certain words disappeared

It seems that linebreaks inside element text are not converted into whitespace.

**What URL can we use to see the issue?**

Using <baas.pubpub.org>. Example document:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Linebreak demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  </head>
  <body>
    <p>These
      are
      all
      different
      words.</p>
  </body>
</html>

```

**What browser/operating system were you using?**

Linux / Firefox.

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

![Screenshot from 2020-01-15 18-34-03](https://user-images.githubusercontent.com/59598/72480517-a8e6bb80-37c5-11ea-87c3-bdb0ac676e31.png)

**Comment by gabestein** [comment]
I'm seeing this too in Markdown and LaTeX, both of which should treat newlines as spaces by default. Generic pandoc does not seem to have this problem interpreting md or tex, which makes me think it's our parser not handling newlines properly.

Here's an example markdown with some newline breaks:

```
# Testing

The performance of effect estimation methods will likely vary from
use-case to use-case. We therefore recommend that practitioners always
perform an evaluation within the study setting of interest, for
example, by including negative (Dusetzina, Brookhart, \& Maciejewski,
2015; Prasad \& Jena, 2013) and positive controls (Schuemie, Hripcsak,
Ryan, Madigan, \& Suchard, 2018; Schuemie, Ryan, Hripcsak, Madigan, \&
Suchard, 2018) to estimate residual bias. Nonetheless, characterizing
how a method performs across a wide range of settings also adds
value. This understanding can serve as a prior when a study-specific
evaluation is not (yet) available, and may aid development of novel
methodology. We establish the Observational Health Data Science and
Informatics (OHDSI) (Hripcsak et al., 2015) Methods Benchmark that
seeks to measure the performance and operating characteristics of
observational analysis methods against disparate observational data
for the task of population-level effect estimation. We subsequently
apply this benchmark to a wide range of commonly used study designs
and analysis approaches as implemented in the OHDSI Methods Library
(https://ohdsi.github.io/ MethodsLibrary), an open source collection
of R packages.
```

When you copy that into an md file and [import to PubPub](https://demo.duqduq.org/pub/4sq6up1e/branch/2), it doesn't preserve breaks.

<img width="703" alt="Screen Shot 2020-01-28 at 10 43 08" src="https://user-images.githubusercontent.com/639110/73279541-50e38800-41bb-11ea-81d9-c1ff864a1658.png">

If you run through pandoc locally (`pandoc ~/Desktop/test.md -f markdown -t html -o ~/Desktop/test.html` it produces html (and other formats) with breaks:

<img width="492" alt="Screen Shot 2020-01-28 at 10 48 52" src="https://user-images.githubusercontent.com/639110/73280114-14645c00-41bc-11ea-9765-a8effc00b148.png">

**Comment by gabestein** [comment]
Fixed by https://github.com/pubpub/pubpub/commit/13b75f5604de0187d9f5a59da99e4f64817e6c44

Thanks @idreyn!
