### ISSUE TITLE
Navigation bar cuts off on mobile

### ISSUE THREAD

**Issue by pkgw** [pubpub/pubpub#676]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. Looked at our site, baas.pubpub.org, in a mobile browser.
2. The nav bar is cut off. See screenshot. The full item is "Community Reports" and there should be several additional items.
...

**What URL can we use to see the issue?**

baas.pubpub.org

**What browser/operating system were you using?**

Android/Firefox.

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

![Screenshot_20200118-091213_Firefox](https://user-images.githubusercontent.com/59598/72665058-0439c900-39d3-11ea-8ca3-fd999127a8d7.jpg)

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Closing this out (for now, anyway), as we addressed it by adding some shading to the edges of navbars to indicated they're scrollable. A longer-term solution is to have navbars on mobile be more menu-like, which we're also taking a stab at soon.
