### ISSUE TITLE
Service interruption while editing

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#688]
As an editor, I was working on this doc:

1. I got an 'edits lost, please refresh' error.
2. Refresh, wait 30 seconds, and I got the first attached error. 
3. Wait 1 minute, refresh, and got the second one.
4. Wait another minute, and got the first error.
5. After a third minute, it loaded as expected.
6. This happened again 3 times (items 1+2, each time unavailable for ~3 min) while I finished writing this bug. 

**What URL can we use to see the issue?**
https://www.underlay.org/pub/b1rgpskb/branch/2

**What browser/operating system were you using?**
Chrome/Mac, then Chrome/Win

**Have any screenshots? (Attach them by dragging the image here)**
![ul-pub-error](https://user-images.githubusercontent.com/1615548/73402040-64c1e380-42ba-11ea-8f5d-e742056d4c9e.PNG)
![ul-pub-error-2](https://user-images.githubusercontent.com/1615548/73402081-773c1d00-42ba-11ea-8c39-5bf6c12ed416.PNG)

**Comment by gabestein** [comment]
Appears to have been temporary instability. Closing for now since we haven't seen it recur.
