### ISSUE TITLE
Long footnotes: lack of scroll makes them annoying

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#698]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

698 Required
---

**What went wrong, step-by-step?**

1. opened editor for fn 106 in https://design-justice.pubpub.org/pub/y2ymuvuk/branch/2
2. pasted author's long note into rich text box. Noticed errors in text of the note.
3. not possible to scroll down in the editor. Weird transparent effect for text outside the box.
<img width="1322" alt="Screen Shot 2020-02-06 at 8 45 58 AM" src="https://user-images.githubusercontent.com/60357197/73943513-e0292380-48be-11ea-8509-4fdd4657e7f3.png">

...

**What URL can we use to see the issue?**
https://design-justice.pubpub.org/pub/y2ymuvuk/branch/2

**What browser/operating system were you using?**
chrome

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Thank you very much for reporting this! We should have a fix out in the next day or so. In the meantime, one available workaround is to use Firefox, which seems not to have this issue.

**Comment by idreyn** [comment]
Looks like it should be fixed now. Thanks again for flagging!

**Comment by avanouse** [comment]
Thank you!!
