### ISSUE TITLE
Create a cross-community admin role to help clean up spam

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#699]
Let anyone flag a community as spam, and let cross-community admins monitor new ones that pop up and first lock them down (prevent pubs from being public) and second  tag them for deletion.  

A dev might still do the deletion itself.

**Comment by metasj** [comment]
The problem is growing.  There's a bit of a feedback loop: the harder it is to spam, the less likely new spam engines will include pubpub as a target. 
https://mangga2poker.pubpub.org - 10 days old

**Comment by gabestein** [comment]
Closed by #2252
