### ISSUE TITLE
Describe how the default sort works for pub-blocks on pages

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#718]
As an editor or community manager, when I create a pub block on a page I'd like to know roughly how the default sort works, to decide whether I can avoid having to manually set pubs or not.  

In particular: if I'm happy with the current look of a default sort, how will it changea s new pubs are created?  Is there any way for me to engineer creating a batch of pubs all at once so that the default sort does what I want? 

A description in the docs, linked to from a (?) icon on the page, would help.

**Comment by metasj** [comment]
Requested by a discourse user.

**Comment by gabestein** [comment]
Resolved in #1300!
