### ISSUE TITLE
Preserve pub URLs across renames

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#721]
URLs shouldn't break. 
Currently renaming a pub breaks URLs.

Renaming a pub is a first-class option in the UX: one of the most evident things you can do when reviewing its metadata.  Currently renaming a pub breaks the previous URL, for instance breaking links from other pubs linking to it, or for off-site links referencing it.  

By default, a rename should leave a redirect behind.  
- The original randomly-assigned namestring can be a unique ID that's permanently attached to the pub regardless of how it is renamed.  
- Changes to the prettyname may have the option of _not_ leaving a redirect behind (so that another pub could take that name), but the original autogenerated URL can then reliably always point to the most recent version of that pub. 

Until this is possible, a few changes to the UX could minimize broken the impact of this: 
- Invite the authors to name the pub during/after their first editing session. 
- Make it impossible to rename pubs without looking for advanced features, after a pub reaches a certain minimum age. 
- Add a warning by the pub-renaming textfield, noting that renames will break existing links.  (If possible, show editors how many people have come to the pub from those existing links)

**Comment by metasj** [comment]
Distantly related to #685.

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/22
