### ISSUE TITLE
Encourage communities to use human-readable pub names

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#722]
Currently, pub renaming breaks URLs. ( see #721 )
Renaming is also widely used, and most communities after discovering they can name pubs, will eventually name each pub.   Helping them do so early in the life of the pub will minimize their exposure to broken links.

This should ideally be fixed in such a way that the original randomly-assigned namestring remains always attached to the pub regardless of how it is renamed, so that the following becomes less of an issue.  But until then:
_ Give community managers a way to see how many of their pubs have their original randomly-assigned namestring
_ Encourage them to rename those pubs (before sharing the randomly assigned URL)

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/22
