### ISSUE TITLE
ReCaptcha & dev environment

### ISSUE THREAD

**Issue by Yomguithereal** [pubpub/pubpub#73]
Hello @pubpub. I am currently trying to locally installing the project so I can contribute but fail to pass the captcha when creating a pub. I tried indicating a personal recaptcha key in the configuration but this doesn't cut it. How do you setup this part on your personal dev envs?

**Comment by ThariqS** [comment]
@Yomguithereal I'll try removing the captcha UI for local, but it's designed such that if you don't have a captcha key, it will still pass. The problem might actually be that you have a personal recaptcha key, try not setting the recaptcha key in config.js 

`export const captchaKey = null;` 

After that, even if you fail the captcha or leave it blank, you can still hit submit.

**Comment by ThariqS** [comment]
Okay just added it in this commit! https://github.com/pubpub/pubpub/commit/2808f5b344c02b9a9da8fa55ca2f977319b06268

**Comment by Yomguithereal** [comment]
Thanks @ThariqS. Maybe just disabling captcha if the config is `null` would be better than just shutting it off in development?

**Comment by isTravis** [comment]
Captcha removed as signup process requires email verification first now.
