### ISSUE TITLE
Cannot install as-is on Node.js v13

### ISSUE THREAD

**Issue by stvnwn** [pubpub/pubpub#733]
**What went wrong, step-by-step?**
1. Clone PubPub git repo
2. cd into directory for PubPub git repo
3. Run `npm install`

Eventually, npm will emit an error message; a relevant line follows:

> npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`

I found what seems to be a relevant GitHub issue [here](https://github.com/grpc/grpc-node/issues/1315). I suggest that you either upgrade your `firebase` dependency (which `grpc` depends on) or document that PubPub only supports Node.js v12 for now. I was able to verify that upgrading `firebase` or downgrading Node.js to the "long term support" release resolves this issue.

**What URL can we use to see the issue?**
Not applicable

**What browser/operating system were you using?**
macOS v10.15.4

**Comment by kallewesterling** [comment]
Same issue here, and when trying to run `npm start`, here's my output:

> ERROR in ./client/utils/firebaseClient.js
Module not found: Error: Can't resolve 'firebase/app' in '_/path/to/my/pubpub/directory + /client/utils_'
 @ ./client/utils/firebaseClient.js 1:0-36 11:20-28 16:35-43 17:17-25 20:9-17
 @ ./client/containers/Pub/PubSyncManager.js
 @ ./client/containers/Pub/Pub.js

> ERROR in ./client/utils/firebaseClient.js
Module not found: Error: Can't resolve 'firebase/auth' in '_/path/to/my/pubpub/directory + /client/utils_'
 @ ./client/utils/firebaseClient.js 2:0-23
 @ ./client/containers/Pub/PubSyncManager.js
 @ ./client/containers/Pub/Pub.js

> ERROR in ./client/utils/firebaseClient.js
Module not found: Error: Can't resolve 'firebase/database' in '_/path/to/my/pubpub/directory + /client/utils_'
 @ ./client/utils/firebaseClient.js 3:0-27
 @ ./client/containers/Pub/PubSyncManager.js
 @ ./client/containers/Pub/Pub.js

**Comment by gabestein** [comment]
Closed by #1989
