### ISSUE TITLE
Error adding pub to collection from personal account

### ISSUE THREAD

**Issue by turnerandrasz** [pubpub/pubpub#748]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---

**What went wrong, step-by-step?**
1. I tried to add a pub that I created to a collection from my personal account but it just said "saving" for a very long time. Tried this a few times with the same error and it never added the pub to that collection.
2. I signed into our administrative login for the website and I had no problem adding that pub to the collection.
3. We are worried that when we are accepting submissions through PubPub, the users will not be able to add their entries to specific collections which is necessary for our submission process.
...

**What URL can we use to see the issue?**
https://association.aap.cornell.edu/
**What browser/operating system were you using?**
Google Chrome
### Optional

The submission page and pubs are locked right now. The first image below shows where it got stuck trying to save. The second image shows where it was successfully added to a collection using the administrative account.
---

**Have any screenshots? (Attach them by dragging the image here)**
![capture](https://user-images.githubusercontent.com/63427529/78942194-28172300-7a87-11ea-875b-c1da888a9685.jpg)
![capture 1](https://user-images.githubusercontent.com/63427529/78942214-2d746d80-7a87-11ea-87ef-e06b0a6dae3f.jpg)

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Hi, thanks for reporting this! We recently made a change that allows the Pub Managers of a pub — listed under the Managers tab of the Pub settings — to modify the list of collections that contains a pub. If your authors are creating the submission pubs themselves, they should be Managers by default.

If you have a second, please let us know whether this now works for you!
