### ISSUE TITLE
Comment won't post if entire text selection is a link

### ISSUE THREAD

**Issue by heatherKFG** [pubpub/pubpub#750]
_We use GitHub Issues for tracking active code development. If you have general questions or feedback about PubPub, we invite you to use our [Discourse forum](https://discourse.knowledgefutures.org)._

### Required
---
I'm on a Mac OS Mojave, 10.14.6  trying to post a comment on a Pub in Chrome  81.0.4044.92. If I select text that corresponds entirely to an underlying link, either the comment box won't even open, or it opens and lets me write the comment, but will not post.

**What went wrong, step-by-step?**
1. I select the text.
2. I hit the comment button to open the comment box on right side. (Sometimes it won't even open.)
3. I sometimes can complete the comment, but hitting "post discussion" causes nothing to happen. Link option sometimes stays "highlighted"
<img width="813" alt="Screen Shot 2020-04-13 at 12 09 51 PM" src="https://user-images.githubusercontent.com/63602846/79136942-d2d95b00-7d7f-11ea-9b1d-e459e99e82af.png">

...

**What URL can we use to see the issue?**
https://notes.knowledgefutures.org/pub/y7mmdhye/branch/2

**What browser/operating system were you using?**
Mac OS Mojave, 10.14.6  trying to post a comment on a Pub in Chrome  81.0.4044.92.
### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Likely fixed by one of our editor updates; in any case, no longer reproducible.
