### ISSUE TITLE
Allow images with links

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#762]
# Required

---

**What's your request?**
Allow users to add images that are wrapped in links.

**What would this feature help you accomplish, and why is that important to you?**
Use images as buttons on Pages, allow linking out to datasets or other versions of figures from static versions, etc.

**What's the URL to your PubPub community?**

### Optional

---

**Comment by jeffpooley** [comment]
Just want to bump this request. In addition to the Pub-level benefits mentioned above, the ability to add link targets to images would be a relatively simple way to introduce design flexibility to Pages and Collections.

**Comment by gabestein** [comment]
Superseded by #1522
