### ISSUE TITLE
Allow iframe embeds that adhere to the center-left margin (table hack)

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#763]
Offer a format option, when popping out an embedded iframe and setting a width%, to stick the left-margin of the frame to the left margin of the central column (instead of floating all the way to the left margin of the page.)

----

Motivation: As an author who likes working with tabular data, I usually want precise control over how my tables render.  Tables can be the most beautiful or the ugliest part of a dense document.

Currently, native tables get cramped on mobile. (See #754)  One hack is to embed a Google Sheet; for instance, use `File` -> `Publish to Web` from a spreadsheet, add `&chrome=false`, to get for each worksheet a clean, uneditable table to embed. ([example](https://docs.google.com/spreadsheets/d/e/2PACX-1vR-7LJHgAsWmVRVpiet6gVJEOCgqgKKEV-cCITceO5AXu4El-01WFa1uEYbvCSiAsz3MDIQOLmGDvQH/pubhtml?gid=0&chrome=false)).  

Multiple tables in a pub can be stored as different worksheets in a single sheet.   The standard format that I've found works well across man types of tables is popped-out w/ a width% of 50-80%.

The only problem: if the size of a sheet-embed is too small, the edges are cut off and it adds scrollbars.  If it is too large, in desktop view, the table floats to the left of the page [the iframe is centered, the table is left-aligned within it].  A table that crosses the left margin of the central column looks odd, moreso than other embeds, and the asymmetry amplifies that.

**Comment by gabestein** [comment]
Closing in favor of just fixing tables, and ultimately widening the pub body.
