### ISSUE TITLE
Feature Request: Use links in profile

### ISSUE THREAD

**Issue by gsarma** [pubpub/pubpub#77]
It would be nice to be able to link to a personal website, university research profile, etc.

**Comment by ThariqS** [comment]
Thanks, this is definitely something we want to put into the user profile as we iterate on it!

**Comment by isTravis** [comment]
Architecture2 allows you to list personal website, twiter, orcid, and google scholar links. This would limit you to adding multiple custom website URLs - but perhaps we could allow URLs in the description field? Will close this issue for now, but feel free to re-open after playing with architecture2 (live shortly!) if it still feels incomplete.
