### ISSUE TITLE
PDFs not generating from drafts or releases

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#777]
### Required
---
**What went wrong, step-by-step?**
1. Create a new pub and add some text (ie: https://demo.pubpub.org/pub/nno2oncz/draft)
2. Click download.
3. Worker times out
4. Create a new release.
5. Click download.
6. Release often times out, but sometimes generates pdf with title page but blank content (ie: https://www.mediastudies.press/pub/jpl4m2lo/release/1)
...

**What URL can we use to see the issue?**
https://www.mediastudies.press/pub/jpl4m2lo/release/1
https://demo.pubpub.org/pub/nno2oncz/release/1

**What browser/operating system were you using?**

### Optional

---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Jeff Pooley

**Comment by idreyn** [comment]
Fixed in 02b80d3
