### ISSUE TITLE
Easier navigation to Collection Dashboards

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#788]
**What's your request?**

Request is for easier navigation to Collection Dashboards.

Specifically:

* list the Primary Collection of a Pub on the Pub view (draft or latest release), in the Dashboard “Select Scope” drop-down menu (upper right). Currently Community and the Pub itself are the options. 
* include the Primary Collection of a Pub in the breadcrumb in the Pub Dashboard Overview 
* list the Collection linked to a designated Page on that Page view, in the Dashboard “Select Scope” drop-down menu (upper right). Currently Community is the only option.  

**What would this feature help you accomplish, and why is that important to you?**

The request is for easier and more intuitive navigation to Collection Dashboards. Currently it is challenging to navigate to the Collection Dashboard from Pubs and linked Pages, which can be frustrating since the navigation between PubPub elements is otherwise so seamless. 

From Pubs, the fastest current method is arguably too difficult and not intuitive: Selecting “Pub Settings” in the Pub Header, and then either (1) selecting the disclosure triangle on the Pub Dashboard (“Pub Dashboard”) and selecting the Collection; or (2) navigating to “Overview” in the Pub Dashboard, and then selecting the Collection under “Appears in collection”.

**What's the URL to your PubPub community?**

https://mediastudies.press

**Comment by gabestein** [comment]
Thanks Jeff! Agreed. I thought we did want to display collection scope (or at least primary collection scope) at one point. Not sure where that went, but we'll chat about it.

**Comment by djagdish** [comment]
[Here are some improved designs for Dashboard Popup Menu](https://www.figma.com/proto/Dm0hSzmJA8HbBdloDTGJzw/Dashboard-Popup-Menu?page-id=2%3A2664&node-id=2%3A2665&viewport=-1578%2C-501%2C0.53&scaling=min-zoom&starting-point-node-id=2%3A2665&show-proto-sidebar=1) that has direct link access to Collection dashboard views.
