### ISSUE TITLE
syntax highlighting for code blocks

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#799]
### Required

---

**What's your request?**
Syntax highlighting for code blocks, with user ability to select the language from a common set.

**What would this feature help you accomplish, and why is that important to you?**
Allows users to post technical articles that talk about or demonstrate code.

**What's the URL to your PubPub community?**

### Optional

---

**Are there any other products or services that do this well?**
GitHub's Gist

**Any attachments or reference images? (Drag them here)**

**Who requested this? (If not you)***
Irhum / irhum.pubpub.org

**Comment by shaunagm** [comment]
Continuing the conversation from https://github.com/pubpub/pubpub-editor/issues/47 do you have an updated eta on when this feature will be available for end users? 

(Thanks again for building this project! I know I keep commenting about this one feature we want, but we do also appreciate the many features PubPub already has.)

**Comment by gabestein** [comment]
Sorry it's taking longer than expected! CC'ing @howebenhowe, as he's working on getting it over the finish line and I'm at a conference this week so I don't know the latest.

**Comment by gabestein** [comment]
@shaunagm again, really sorry for the delay. This just hit prod! There's a small issue with initial page load flickering and exporting that we'll follow up with a fix for next week, but otherwise, let us know if this works for you and if there's anything else you'd like us to consider adding.

#2263 #2184

**Comment by shaunagm** [comment]
Thanks for the update! Looking forward to trying this once it's live.

**Comment by gabestein** [comment]
Sorry it took so much longer than expected. This is now live. Highlighting and formatting does not yet extend to exports, but we are working on that next in https://github.com/orgs/pubpub/projects/14.
