### ISSUE TITLE
Collection search broken

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#800]
### Required
---
This is a two-parter.

First, it looks like pre-filled search pages are no longer working. The page loads, but spins forever and no request is sent to our API. See: https://www.pubpub.org/search?q=hello

Second, it looks like we're not searching over and/or indexing collections anymore, which has had the effect of breaking collection "pages" if you don't explicit link them. E.g.:

**What went wrong, step-by-step?**
1. Visit https://www.keepcalmlogon.com/pub/digital-security-work-from-home-remote/release/2
1. Click security-all
1. (delete an l and add an l to resolve the issue above)
1. Notice that there are no results, despite the article being in that collection (and the collection has 24 pubs, so we would expect more)
...

**Who reported this? (If not you)**
Gus / Keep Calm

**Comment by isTravis** [comment]
The first part is addressed in #806. 

To my knowledge, the second part _never_ worked. Collections were never indexed by search, and clicking a Collection tab without a linked page always took you to a Search page that had shoddy results (i.e. it wasn't showing you the list of pubs within that collection). Navigating to the search page was a minimal attempt at answering: 'Where do we send folks that click on unlinked-collection buttons'. We could send them to the Collection Dashboard now if that seemed right.

**Comment by gabestein** [comment]
Hrm...I don't think sending folks to the dashboard seems quite right. Let's close this with the PR and return to it in the great Collection/Pages debate of 2020.
