### ISSUE TITLE
Redirect to new pub dash settings after slug change

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#804]
When you change the slug of a Pub, it invalidates all the old URLs, including the URL of the dash settings Page you use to change the slug and the "Go to Pub" button.

Ultimately, a more stable slug scheme will fix this.

But in the meantime, we should redirect to the new slug's pub settings page when you successfully change a slug.

**Who requested**
Peter / BAAS

**Comment by idreyn** [comment]
Fixed in 2fb5c13
