### ISSUE TITLE
Style for header links

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#818]
**What's your enhancement request?**
Add some better styling for headers that are linked. Right now linked and unlinked headers look the same.

**What would this enhancement help you accomplish?**
Make it easier to use headers to link to comments, as in: https://commonplace.knowledgefutures.org/pub/mzmdig00/release/5/

---

**Any attachments or reference images? (Drag them here)**
<img width="731" alt="Screen Shot 2020-05-12 at 09 44 09" src="https://user-images.githubusercontent.com/639110/81699377-416c1000-9435-11ea-874d-6d13af85507b.png">

**What's the URL to your PubPub

**Comment by coahearn** [comment]
Any way to bump this up in our priorities? idk how hard this is to do. But would be reallly useful for a book going live... next week.

**Comment by gabestein** [comment]
Pretty easy technically! @djagdish, how do you feel about just adding the same underline style for normal links, at least for now?
