### ISSUE TITLE
Intercept Ctrl+S in the draft editor

### ISSUE THREAD

**Issue by joeltg** [pubpub/pubpub#82]
Many users (like me!) obsessively mash Ctrl+S whenever editing long pieces of text, which by default pops up a very annoying "Save Page as..." dialog in browsers. Google Docs and most editors override this (even if just to do nothing).

**Comment by isTravis** [comment]
Added on new editor in architecture2.  c875caf7c8e6ab92bd73ad7309719a0a31b837bf
