### ISSUE TITLE
Reduce whitespace in header + footer

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#820]
As an author, I usually want compact headers and footers.  

Currently , the default header has, w/ a banner logo: 
* 4 linespaces above the logo, 
* 1 space below it, 
* 4 linespaces below the subtitle

at the bottom:
* 6 linespaces between the last visible block on the page and the footer

in the footer: 
* 2 linespaces above the community name,
* 0-1 below it, 
* 2-3 below RSS / Legal, 
* 4-5 below the hr

I want to customize this, or to have a standard togglable option for compact header and footers.

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/6
