### ISSUE TITLE
Submit buttons often disabled in Windows 10 / Edge

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#824]
**What went wrong, step-by-step?**
1. Visit a create user or reset password page in Windows 10 / Edge
2. Submit buttons are disabled and do not enable, even if you fill in required fields

Does not seem to be 100% consistent. But it's relatively frequent.

**What did you expect to happen?**
Submit buttons are enabled

**What URL can we use to see the issue?**
https://pubpub.org/signup

**What browser/operating system were you using?**
Windows 10 / Edge
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Fixed in a2370e2
