### ISSUE TITLE
Numbered list font size not same as body text

### ISSUE THREAD

**Issue by djagdish** [pubpub/pubpub#826]
**What went wrong, step-by-step?**
This bug was introduced when we intentionally reduced the size of the (originally oversized) bullet-list item to make it look similar in size to body text. 

**What did you expect to happen?**
Number of list item should have same font size as the text of the list item. 

**What URL can we use to see the issue?**

**What browser/operating system were you using?**
MacOS Mojave 10.14.6
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

---

**Have any screenshots? (Attach them by dragging the image here)**
![image](https://user-images.githubusercontent.com/316939/82223125-ddb77a80-993f-11ea-81f0-c74a86b55910.png)

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
Fixed in 453b83bd
