### ISSUE TITLE
Draft last edited in pub dash is unix epoch

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#830]
**What went wrong, step-by-step?**
1. Visited a pub dash
2. Noticed draft last edited on the dash is unix epoch
3. Clicked into draft, and the last updated date is correct (although it's updated in the header vs. edited in the dash, which is a tad confusing)

Pretty sure this is true for every Pub!

**What did you expect to happen?**
Draft edited is later than 1969.

**What URL can we use to see the issue?**
https://opf.pubpub.org/dash/pub/rdjsj8wd/overview?collectionSlug=opf-2020

**What browser/operating system were you using?**
Mac / Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
<img width="316" alt="Screen Shot 2020-05-18 at 19 37 30" src="https://user-images.githubusercontent.com/639110/82269323-5b2ebb00-993f-11ea-9790-75f4ce448d6b.png">

**Who reported this? (If not you)**

**Comment by idreyn** [comment]
This is one of my all-time greatest hits. Fixed in 2a5714418
