### ISSUE TITLE
working drafts no longer publicly viewable after upgrade 

### ISSUE THREAD

**Issue by schwettmann** [pubpub/pubpub#831]
Pubs that only had a draft (where the draft was set as viewable/editable by others) should still be publicly viewable, but are no longer - - after the update, they're locked. Do we now need to publish drafts in order for them to be viewable? Appreciated the old feature for works in progress.

**Comment by gabestein** [comment]
Closing as I'm not sure we plan to restore this functionality. We're not getting a ton of requests for it, and you can use the share link (and even add it to the body of the doc) to achieve open drafts.
