### ISSUE TITLE
Regression with Markdown import - no quotation marks and blank footnotes

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#836]
**What went wrong, step-by-step?**
1. Saved markdown file (note I changed extension to txt from md since Github wouldn’t upload md):
[test.txt](https://github.com/pubpub/pubpub/files/4678699/test.txt)
2. Imported to newly created
3. Import worked, EXCEPT
4. All quotation marks are stripped. (I have tested with both smart and dumb quotation marks.)
5. Footnote markers appear, but the footnote content is not imported
...

**What did you expect to happen?**

I expected quotation marks and footnotes to import.

**What URL can we use to see the issue?**

https://www.mediastudies.press/pub/sgb00hxw/release/1

**What browser/operating system were you using?**

Safari for iPadOS 13.4.5

**Comment by gabestein** [comment]
Thanks Jeff! Yup, looks like a little reversion due to some export improvements made last week. Fix is on the way courtesy of @idreyn.

**Comment by idreyn** [comment]
Hi Jeff, thanks very much for your report! We've just fixed the issues with quotation marks and footnotes — if you get a second, please feel free to let us know whether it's working for you now.

(Resolved in aab4c9a)

**Comment by jeffpooley** [comment]
Thanks so much for the quick fix! Just tested, and it’s working perfectly.

**Comment by idreyn** [comment]
Great to hear!
