### ISSUE TITLE
Editor error when returning to Draft after creating a Release

### ISSUE THREAD

**Issue by djagdish** [pubpub/pubpub#837]
**What went wrong, step-by-step?**
There is some odd behavior/error associated with the following workflow:
- user creates a Release.
- in the Published a Release successfully dialog, if the user opens the Release in a new tab (by right-clicking on the Go to Release button and open in new tab)
![image](https://user-images.githubusercontent.com/316939/82567223-b4def180-9b9a-11ea-9fa6-7f3b12f84b56.png)

- and then clicks on Cancel in that modal (with the intention being to return to the draft view in the same tab (while the Release is opened in a new tab)
- then within a few seconds of that modal disappearing in the draft view, the following error appears:
![image](https://user-images.githubusercontent.com/316939/82567000-616ca380-9b9a-11ea-832a-73d613ffe3ea.png)

**What did you expect to happen?**
Clicking on Cancel should just take the user back to the Draft view, without any error state requiring the user to refresh the page or asking to backup before refreshing the page.

**What URL can we use to see the issue?**
Any Draft -> Release and then back to Draft workflow in the same browser tab.
 
**What browser/operating system were you using?**
MacOS Mojave 10.14.6
Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by gabestein** [comment]
Can't replicate. I believe the release updates #932 took care of this!
