### ISSUE TITLE
Page blocks (author cutoff and connection UI)

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#848]
https://hdsr.mitpress.mit.edu/specialissue1

<img width="463" alt="Screen Shot 2020-06-01 at 10 16 50" src="https://user-images.githubusercontent.com/639110/83418102-0b48fd00-a3f1-11ea-8305-1cb51f0248e3.png">

**Comment by idreyn** [comment]
Does adding an expand toggle in #951 address this to our satisfaction?

**Comment by idreyn** [comment]
Does adding an expand toggle in #951 address this to our satisfaction?
