### ISSUE TITLE
Searching sometimes has strange behavior (Pubs vs Pages) with broken result links   

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#853]
When searching some communities (tested just now on _credcon_) , search indexing seems to have the following quirk:

Whether logged in or logged out, 
* Sometimes searching for a term in "Pubs" returns few or no results, while clicking on the "Pages" tab under the search bar produces results.  
* Sometimes an initial search (under "Pubs") produces results; then clicking on the "Pages" tab produces similar results, and then clicking on the "Pubs" tab no longer shows results (but results continue to appear under "Pages"). 
* In either case above, in the "Pages" results-view, search results include pubs, but the URL of each result is missing "/pub/",  and so does not resolve (generating a "**Page Not Found**" error).  Adding "/pub/" back in makes them resolve as expected.  [Example search](https://credcon.pubpub.org/search?q=citation)

**Comment by gabestein** [comment]
Resolved in #874.
