### ISSUE TITLE
Non-user author affiliations don't show in PDFs

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#857]
**What went wrong, step-by-step?**
1. Visit https://scottjacques.pubpub.org/pub/coffeeshopsvictimizationpolicemobilization/release/3
2. Download PDF
3. Only Scott's affiliation shows in the PDF, not the other author

**What did you expect to happen?**
All affiliations should show

**What URL can we use to see the issue?**
https://scottjacques.pubpub.org/pub/coffeeshopsvictimizationpolicemobilization/release/3

**What browser/operating system were you using?**
n/a
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Scott

**Comment by idreyn** [comment]
Fixed in c4eff71 (will regen the exports for the Pub in question)
