### ISSUE TITLE
Variable name upgrade: s/blacklist/exclusionList/ 

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#859]
[These 4 variables](https://github.com/search?q=org%3Apubpub+blacklist&type=Code) could do with a rename:

* tools/5to6/v5/index.js : const blacklist
* tools/backfillCheckpoints.js : const pubSlugBlacklist
* tools/5to6/v5/transformPub.js : const splitBlacklist 
* server/community/queries.js : const subdomainBlacklist

**Comment by idreyn** [comment]
Handled in e964ebf8
