### ISSUE TITLE
Add styling options for banner block images

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#862]
**What's your enhancement request?**
Would be great if we could have the topion to have a shadow over banner block images (used as backgrounds), like we can for pub banner blocks

**What would this enhancement help you accomplish?**
A lot more design flexibility
---

**Any attachments or reference images? (Drag them here)**

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
CA

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/7
