### ISSUE TITLE
Visiting the draft URL of a published pub returns an error

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#864]
**Problem**: 
* I have published a pub, and have the draft open.  I share a link to the draft URL with a collaborator.  He can't see the draft, and gets a "no access" message, without a way to see the current revision (or that one exists).  [If he deletes the "draft" directory, the resulting URL works. ]
* He tells me he can't see it; I click a button to publish the latest revision and ask him to try again.  Of course it again does not work, because the 'draft' URL will never be visible to the public without a 'read' key.
* I realize what is happening and send him the editable version (two clicks, once I find the right button).  
* Unlike previous iterations, where I didn't need to learn how to navigate the UX to share the working URL with someone, here I have to do so.

**Comment by metasj** [comment]
Similar to #852 and #853, gentler fallbacks for URLs that don't immediately resolve as expected, and error messages that suggest where else one might look, could directly if not transparently resolve this.

**Comment by gabestein** [comment]
As with #597, we now show more helpful error language in this scenario.
