### ISSUE TITLE
Old pub not rendering (WSOD)

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#868]
As a reader visiting this page : https://mmm.pubpub.org/pub/azuregen/  
I am redirected to https://mmm.pubpub.org/pub/azuregen/release/1  which initially loads text on the page, and then a split second later replaces it with a blank white screen.   

This is a published pub linked from the main page.  Tested on FF+Chrome on Win+Mac

**Comment by metasj** [comment]
Bumping this : it would be helpful for the authors to access the doc for current work.  

As it seems to be a JS issue, I tried to kill js and copy the text to another pub.   
Killing it at the right time pauses the page render before blanking it.  However cutting and pasting the text into a new pub produces an error:

<img width="428" alt="Screen Shot 2021-02-22 at 10 32 53" src="https://user-images.githubusercontent.com/1615548/108730177-451ae000-74f9-11eb-8cb6-519b760fabdb.png">

**Comment by gabestein** [comment]
I was able to restore to an earlier draft using our new-ish restore from history feature. You should now be able to edit, and hopefully, re-release.
