### ISSUE TITLE
orcid integration

### ISSUE THREAD

**Issue by jcolomb** [pubpub/pubpub#885]
**What's your request?**
I would like to be able to import information from orcid into the publication.

This includes:
- name
- affiliations
- funding information

This is  linked to #56, as the information may be imported to the profile first and then to the publications. But it would be great to import also information if the contributor does not have a pubpub profile.

This could be solved also using an external list creator application and an import list option (see #884), maybe as a pugin-kind of solution? For Ideas on implementation, see https://colomb.shinyapps.io/contributorlist_creator/

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/20 and https://github.com/pubpub/roadmap-repo/issues/12
