### ISSUE TITLE
Lists in tables

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#887]
**What went wrong, step-by-step?**
1. adding a bullet point list in a table causes the font to increase in size
2.
...

**What did you expect to happen?**

**What URL can we use to see the issue?**

**What browser/operating system were you using?**
chrome 83.0.4103.116
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
CA

**Comment by gabestein** [comment]
It looks like this one was resolved at some point!
