### ISSUE TITLE
Add a page block where all pubs link to the world-editable version of the latest draft

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#906]
In my ongoing quest to support real-time notetaking in a pub community without artificial draft/release distinctions, I would like a Page block that does the following:

* Offers the same options as a Pub block
* For each pub in the block, renders them world editable (by using a world-editable link to the latest draft)
* Displays a warning on save if any of the pubs in the block have no published revisions (in which case they would not show up at all in the block to logged-out users)

This would let me, for instance, create a pub for every session on a conference schedule, list them all in a block on the conference page, and have the links in that block take people to the realtime notes being taken in that pub, not the static notes from the last time someone (with publishing ability) remembered to publish.

The [CESS](https://cess.pubpub.org) community is an example of a conference where this was helpful, when this could be done with publicly-editable drafts.

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/7
