### ISSUE TITLE
[PC DOI Deposits] Deposit Status

### ISSUE THREAD

**Issue by 3mcd** [pubpub/pubpub#912]
Deposit status — adds a field to support different crossmark statuses (can be deposited with main pub deposit, see schema). For now, we should support:

Preprint

once deposited with this status, it cannot be changed, and should also update the type of submission to be posted_content with a type of preprint

Pending publication

Advanced online publication

Author accepted manuscript

Version of record

**Comment by jones56** [comment]
hallo. why is particl copay is not pemithing deposit
