### ISSUE TITLE
Routes code not refreshing with hotReloadServer

### ISSUE THREAD

**Issue by isTravis** [pubpub/pubpub#916]
The hotReload functionality doesn't seem to reload route functions. The edits in PR #915 to `utils/pub/metadata.js` would not take effect until I killed the server and ran `npm run start` fresh. I think this is because the function I was inspecting, `getGoogleScholarNotes`, is called from `server/routes/pubDocument.js` inside the `renderToNodeStream` function.

There's some odd caching behavior that we're missing. You can verify this by adding `console.log` statements to the `getGoogleScholarNotes` function and then loading a pub route (you'll notice those console statements don't run until you kill the server and run `npm run start`).

**Comment by idreyn** [comment]
Tentatively closing this because I think Eric found the problem — we didn't change a reference to `./shared` to `./utils` in the package.json scripts when that directory name change occurred.
