### ISSUE TITLE
Caption field not rendering in Edge

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#917]
**What went wrong, step-by-step?**
"When I insert media (usually an image), the “Caption” entry box is not only super-small (even on my huge screen) but the formatting options are invisible (again, at least on my screen). Any possibility you can enlarge that box or make it pop out and heighten the contrast on the formatting options?"

**What did you expect to happen?**
Caption should load with rich text options.

**What URL can we use to see the issue?**
Any pub on Edge
https://knowledgefutures.freshdesk.com/a/tickets/1577

**What browser/operating system were you using?**
Windows 10 / Edge latest
---

**Have any screenshots? (Attach them by dragging the image here)**
![attachment](https://user-images.githubusercontent.com/639110/87681602-d26ca980-c74c-11ea-92c5-b5696a8c74f5.png)

**Who reported this? (If not you)**
William Pate / SA Review

**Comment by idreyn** [comment]
Looks like this is in reference to the Page formatting bar, not the Pub one. This plus #930 represent a neat little chunk of work to get rich text editing in Pages up to speed with Pubs.

**Comment by gabestein** [comment]
Done in #1304!
