### ISSUE TITLE
Citation renders as "Error" in exports

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#918]
**What went wrong, step-by-step?**
1. Visit https://ojmp.pubpub.org/pub/time-orthogonal-space/release/2
1. See that citations render properly in the item
1. Download any export
1. See that citations render as 'error' in the export
...

**What did you expect to happen?**
Citations should render as 

**What URL can we use to see the issue?**
https://ojmp.pubpub.org/pub/time-orthogonal-space/release/2
https://knowledgefutures.freshdesk.com/a/tickets/1572

**What browser/operating system were you using?**
n/a
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Matheus / OJMP

**Comment by idreyn** [comment]
Fixed in 186af00
