### ISSUE TITLE
Saving a description longer than maximum results in deleted description

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#920]
**What went wrong, step-by-step?**
1. Visit a pub in draft mode (ie: https://demo.duqduq.org/pub/dvu74dm3/draft)
2. Attempt to set a very long description in the header, ie: 
```Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. ```
3. After clicking enter, description will be deleted.
...

**What did you expect to happen?**
To avoid this, the description field should not allow descriptions longer than the max (280 chars I believe) to be entered in, and there should be some kind of indication that you're getting close to the limit (perhaps a counter appearing in the corner of the box, ala twitter?

**What URL can we use to see the issue?**
Any pub
https://knowledgefutures.freshdesk.com/a/tickets/1637

**What browser/operating system were you using?**
OS X Latest / Chrome Latest
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**
Scott / Criminology

**Comment by Honoluluskye** [comment]
Yes, just an indication somewhere that there is a character limit of 280 would be helpful because I came in here to report this as a bug because I didn't know why the text I was copy pasting was just automatically disappearing.
