### ISSUE TITLE
Inline citation ‘Pub default’ in Author-Name and Author inline format reverts to Numbered in rich text citations

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#929]
**What went wrong, step-by-step?**

A small bug:

1. The ‘Pub default’ for inline citations in the *Author-Name* and *Author* inline citation formats is correct (e.g., (Jordan, 2015)) with **Structured Data** (like BibTeX) as the citation input (see screenshot). 
2. However, the ‘Pub default’ for inline citations in the *Author-Name* and *Author* inline citation formats incorrectly reverts to the *Numbered* inline citation format (e.g., [2]) if the citation input is **Rich Text** (see screenshot)
...

**What did you expect to happen?**

I expected the **Structured Data** and **Rich Text** citation input options to generate the same ‘Pub default’ output. Instead, only the **Structured Data** works as expected. 

*Of course it would be hard to generate the ‘Pub default’ with rich text, but perhaps the default could be, in the rich text case, something like “(author, YYYY)”?*

---

**Have any screenshots? (Attach them by dragging the image here)**

<img width="1366" alt="citations1" src="https://user-images.githubusercontent.com/6372329/87865573-0ca09b80-c945-11ea-94cd-5c4c59bd22fe.png">

<img width="1366" alt="2citations" src="https://user-images.githubusercontent.com/6372329/87865576-10342280-c945-11ea-8d99-c970018833b9.png">

**Comment by gabestein** [comment]
Closing as not planned. This would require us to parse the rich text and try to get any structure out of it, which we've rejected in the past because it's not particularly reliable. What we should probably do is set it to "Custom" in this case and default to the number. Or GPT3 it (mostly kidding).
