### ISSUE TITLE
Bug: Citation Creation Broken on Pages

### ISSUE THREAD

**Issue by writingpoli** [pubpub/pubpub#930]
**What went wrong, step-by-step?**
1. Inserted citation on sareview.org/about (formatting and link options still didn't show up -- even using Chrome)
2. No footnote or citation created on published page. 
...

**What did you expect to happen?**

Pop-up or footnote at bottom of page, like in Pub.

**What URL can we use to see the issue?**

www.sareview.org/about

**What browser/operating system were you using?**

Google Chrome, Windows 10

---

**Have any screenshots? (Attach them by dragging the image here)**
![image](https://user-images.githubusercontent.com/3883763/87881905-1f0cea80-c9c2-11ea-9bff-fead6dc5c9ab.png)

**Comment by idreyn** [comment]
Thanks for writing in about this. We restructured our citations code quite some time ago in a way that didn't account for their use on Pages. This is a somewhat rare usage, but one we definitely want to restore support for in the near future. In the interim, can a hyperlink serve this purpose?
