### ISSUE TITLE
Connection ignored author order and sorts alphabetically

### ISSUE THREAD

**Issue by ThomasJorna** [pubpub/pubpub#935]
Appears correct here
![image](https://user-images.githubusercontent.com/21983833/88085713-85426a80-cb86-11ea-8fa6-8d963415c77c.png)

But once apply is clicked:
![image](https://user-images.githubusercontent.com/21983833/88085797-a2773900-cb86-11ea-8ccd-b1922b1bb42a.png)

**Comment by ThomasJorna** [comment]
Using the DOI instead yields no problems
![image](https://user-images.githubusercontent.com/21983833/88085897-c8044280-cb86-11ea-9523-ec97790c0689.png)

**Comment by idreyn** [comment]
Fixed in 87bacd6b9c4078c5636be51777d31ac9617b99fd. Thomas, you should now be able to directly reference Pubs when creating Connections, rather than going through the DOI. Thanks for your report!

**Comment by ThomasJorna** [comment]
Fantastic, thanks for the quick turn-around!
