### ISSUE TITLE
Set Custom Order of Pubs Block in Table of Contents not working

### ISSUE THREAD

**Issue by Honoluluskye** [pubpub/pubpub#944]
**What went wrong, step-by-step?**
1. When I attempt to reorder the pubs to display differently, they do not stay in the order I arrange them into....

**What did you expect to happen?**
Expected to change the order of the pubs as they display in table of contents

**What URL can we use to see the issue?**
https://researchdatashare.pubpub.org/dash/pages/home

**What browser/operating system were you using?**
Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by gabestein** [comment]
Appears to have been fixed. Will also be getting more attention in https://github.com/pubpub/roadmap-repo/issues/7
