### ISSUE TITLE
Date picker in Connections creation interface returns the previous day’s date

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#945]
**What went wrong, step-by-step?**
1. When manually adding or editing publication date in the Connections pane in the Pub dashboard, the date picker returns the day before the selected date. E.g., July 24, 2020 returns July 23, 2020.
2. Tested in Safari for iPad and Chrome for Mac

**Comment by idreyn** [comment]
Thank you for the report, Jeff!
