### ISSUE TITLE
Zotero/Mendeley/Worldcat only able to find earliest PDF of Pub

### ISSUE THREAD

**Issue by ThomasJorna** [pubpub/pubpub#953]
**What went wrong, step-by-step?**
When importing the article via Zotero or Mendeley, only the earliest uploaded PDF is downloaded/recognized. Similarly, Worldcat is only able to find the earliest uploaded PDF.

...

**What did you expect to happen?**
To see the latest PDF downloaded/recognized.

**What URL can we use to see the issue?**
https://jtrialerror.pubpub.org/pub/alcoholcues

**What causes this?**
I'm relatively sure that this happens because in the `<meta>` tags only the first PDF is stored, as defined in `/server/utils/ssr.js`:
![image](https://user-images.githubusercontent.com/21983833/88658733-2b84f780-d0d4-11ea-975d-2ae9b70379d1.png)

This could be fixed by having this refer to the newest PDF link, which I assume is embedded somewhere in `pub.downloads`, although I haven't been able to figure out how and where this is done.

---

**Have any screenshots? (Attach them by dragging the image here)**
The current PDF tag is https://assets.pubpub.org/vpox2noi/51594136813036.pdf
![image](https://user-images.githubusercontent.com/21983833/88659414-4dcb4500-d0d5-11ea-9d70-2e32a80597b6.png)

Newest PDF link should be: https://assets.pubpub.org/5w13ggwn/01595410840198.pdf

**Comment by ThomasJorna** [comment]
This is a duplicate of https://github.com/pubpub/pubpub/issues/923, whoops!

**Comment by gabestein** [comment]
Thanks! Fix on the way, as you likely saw in #923. Fwiw, the issue was how we were (not) sorting downloads in `getPDFDownload` in `utils/pub/metadata.js`
