### ISSUE TITLE
Spare comma in author list in search results

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#957]
**What went wrong, step-by-step?**
1. Search for a result that returns a pub with multiple authors (ie https://hdsr.mitpress.mit.edu/search?q=covid)
2. Notice that Pubs with multiple authors have an extra comma in the results

**What did you expect to happen?**
Just the one comma

**What URL can we use to see the issue?**
https://hdsr.mitpress.mit.edu/search?q=covid

**What browser/operating system were you using?**
n/a
---

**Have any screenshots? (Attach them by dragging the image here)**
<img width="891" alt="Screen Shot 2020-07-28 at 18 10 01" src="https://user-images.githubusercontent.com/639110/88727711-2177ee80-d0fe-11ea-9dcf-5e7818f670be.png">

**Comment by idreyn** [comment]
Looks like the code that was causing this was replaced recently, but unfortunately we have to manually rebuild the Algolia index to get rid the values it produced. Someday soon we're going to want a more robust way to do this, but for now I just started individual `setPubSearchData` tasks from my local machine, and they should run over the next few days.

**Comment by idreyn** [comment]
That was absolutely not a good move, as our queue only supports 10k messages at a time. Looks like I'll have to write a task to batch these by community.

**Comment by idreyn** [comment]
Seems like my last run of `searchSync` took care of it

**Comment by gabestein** [comment]
hrm, I'm still seeing it here: https://wpiugpubs.pubpub.org/search?q=Weekes

**Comment by idreyn** [comment]
Serves me right for just checking one community...back to the drawing board

**Comment by idreyn** [comment]
I think I finally did it.
