### ISSUE TITLE
Let community managers publish pubs

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#958]
As a community admin, I want publishing a public version of a pub to be no big deal. (see also #959)  
I want to let community managers publish pubs as they see fit.

At the same time, I don't want them to be able to do irreversible things like deleting pubs, pages, or the entire community. 

In user management, I want to have a role that allows pub publishing but does not allow any deletion that canont be reversed by other managers or admins.  Either expand the current community-manager role, or add a new role.

Currently this is not an option, so I have to trade off the desire for publishing to be easy, with the extra risk of giving new people deletion rights.

**Comment by idreyn** [comment]
Agreed that it would be nice to have a `publish` role between `manage` and `admin`, and I think we'll get there eventually. In the meantime, if you actually want to allow this kind of interaction in a real community, I suggest the following workaround:

- Create a Collection to hold user-publishable Pubs, and give whoever you want admin access to that Collection.
- Visit **Community > Settings > Default 'Create Pub' Collections** in the dashboard, and add that Collection. This will cause any Pubs created with the global button in the top-right to be automatically added to this Collection

The effect is that practically speaking, everyone involved can publish a Pub.

**Comment by isTravis** [comment]
Also - see [this fanfic](https://discourse.knowledgefutures.org/t/fanfic-tidying-up-the-loose-ends-on-permissions/267) exploring some of these permission considerations [login required].

**Comment by metasj** [comment]
I ran into another (space) community today who had this issue of wanting managers to be able to publish.  They plan to have more than one collection, so will need to do this for each.  It was not easy to explain this workaround - I ended up demonstrating by making them an admin of a collection in an existing community - so I'm reopening to discuss.

**Comment by gabestein** [comment]
Closing as stale. A nicer workaround for this that also allows people to think of this stuff in terms of workflows is being planned for https://github.com/pubpub/roadmap-repo/issues/23
