### ISSUE TITLE
Make publication reversible: Allow users to unpublish a pub

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#959]
As an editor or community manager, I want publishing to be reversible.  
* This will make it less of a big deal, and an easier right to grant to more users.  
* This will also allow for correcting a mistaken publication while preserving its edit history -- the current alternative? being an admin deleting the first pub and creating a new one.

**Comment by nelszzp** [comment]
this is still a good idea. I found a bad workaround, which is to create a tag for "public" pubs, and then filter out non-public pubs from your pages just so the ones you don't want seen are a bit harder to find

**Comment by gabestein** [comment]
Closing as dupe. Will be addressed in https://github.com/pubpub/pubpub/issues/2509
