### ISSUE TITLE
Indicate character limit on description field in Pub header

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#971]
**What's your enhancement request?**
Add a character count (and perhaps description of where it's used) to the input for the description field in the pub header.

**What would this enhancement help you accomplish?**
Avoid confusion by folks who don't know what to do with the description field, or who try to paste in entire abstracts.

---

**Any attachments or reference images? (Drag them here)**

<img width="906" alt="Screen Shot 2020-08-04 at 09 30 52" src="https://user-images.githubusercontent.com/639110/89299856-4ce66600-d635-11ea-82eb-688af3aaa65e.png">

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
Scott Jacques

**Comment by idreyn** [comment]
Closed in #1007
