### ISSUE TITLE
Overlay on banner blocks

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#978]
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

**What's your enhancement request?**
Can we make this optional or changeable like in the pub banners?

**What would this enhancement help you accomplish?**
would make this into a space for better community branding and add nice design flexibility

---

**Any attachments or reference images? (Drag them here)**

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
Me!

**Comment by gabestein** [comment]
Closing as stale. Will receive attention in https://github.com/pubpub/roadmap-repo/issues/7
