### ISSUE TITLE
Uploading profile image hangs

### ISSUE THREAD

**Issue by hrothgar** [pubpub/pubpub#99]
On pubpub.org when I try to add a profile image at Account > Settings > Change Image, the upload hangs. Tested on Chrome and Firefox on a Macbook Pro running OS X 10.11.1.

I see that others have profile pictures, though, so I'm not sure what the deal is.

**Comment by isTravis** [comment]
Image uploads rebuilt on new architecture. Should be more stable now. Thanks!
