### ISSUE TITLE
Create Pub in Collection

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#994]
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. When I click on the collection-level create new pub button, it doesn't do anything
2. When the RRC19 team clicks on this button, it creates a new pub that is not within that collection (wasn't able to recreate this myself because of issue 1)
3. When you're in the collection, you see both the collection-level new pub button and community-level new pub, which has caused some confusion, but the RRC19 team tells me they have been clicking on the correct button. 
...

**What did you expect to happen?**
new pub in that collection!

**What URL can we use to see the issue?**
https://rapidreviewscovid19.mitpress.mit.edu/dash/collection/biological-and-chemical-sciences/overview

**What browser/operating system were you using?**
Chrome
---

**Have any screenshots? (Attach them by dragging the image here)**
https://recordit.co/ZryfuW30rY

**Who reported this? (If not you)**
CA/ Parmita @ RRC19

**Comment by isTravis** [comment]
Resolved in #1001
